OpenCog Framework: opencog::EvaluationLink Class Reference
opencog::EvaluationLink Class Reference
atomspace library
#include <EvaluationLink.h>
Public Member Functions
EvaluationLink (const HandleSeq &oset, TruthValuePtr tv=TruthValue::NULL_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
EvaluationLink (Handle schema, Handle args, TruthValuePtr tv=TruthValue::NULL_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
EvaluationLink (Link &l)
TruthValuePtr evaluate (AtomSpace *as)
Public Member Functions inherited from opencog::FreeLink
FreeLink (const HandleSeq &oset, TruthValuePtr tv=TruthValue::NULL_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
FreeLink (const Handle &a, TruthValuePtr tv=TruthValue::NULL_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
FreeLink (Link &l)
virtual ~FreeLink ()
const HandleSeq & get_vars (void)
virtual Handle reduce (void)
Public Member Functions inherited from opencog::Link
Link (Type t, const HandleSeq &oset, TruthValuePtr tv=TruthValue::DEFAULT_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
Link (Type t, const Handle &h, TruthValuePtr tv=TruthValue::DEFAULT_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
Link (Type t, const Handle &ha, const Handle &hb, TruthValuePtr tv=TruthValue::DEFAULT_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
Link (Type t, const Handle &ha, const Handle &hb, const Handle &hc, TruthValuePtr tv=TruthValue::DEFAULT_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
Link (Type t, const Handle &ha, const Handle &hb, const Handle &hc, const Handle &hd, TruthValuePtr tv=TruthValue::DEFAULT_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
Link (Link &l)
~Link ()
Arity getArity () const
const HandleSeq & getOutgoingSet () const
Handle getOutgoingAtom (Arity pos) const throw (RuntimeException)
template<class T >
bool foreach_outgoing (bool(T::*cb)(const Handle &), T *data)
std::string toString (std::string indent="")
std::string toShortString (std::string indent="")
bool isSource (Handle) const throw (InvalidParamException)
bool isSource (size_t) const throw (IndexErrorException, InvalidParamException)
bool isTarget (Handle) const throw (InvalidParamException)
bool isTarget (size_t) const throw (IndexErrorException, InvalidParamException)
virtual bool operator== (const Atom &) const
virtual bool operator!= (const Atom &) const
Public Member Functions inherited from opencog::Atom
virtual ~Atom ()
Type getType () const
bool isType (Type t, bool subclass) const
Handle getHandle ()
AttentionValuePtr getAttentionValue ()
void setAttentionValue (AttentionValuePtr)
Sets the AttentionValue object of the atom.
AttentionValue::sti_t getSTI ()
Handy-dandy convenience getters for attention values.
AttentionValue::lti_t getLTI ()
AttentionValue::vlti_t getVLTI ()
void setSTI (AttentionValue::sti_t stiValue)
void setLTI (AttentionValue::lti_t ltiValue)
void incVLTI ()
void decVLTI ()
TruthValuePtr getTruthValue ()
void setTruthValue (TruthValuePtr)
Sets the TruthValue object of the atom.
void merge (TruthValuePtr)
Handle tvmerge (TruthValuePtr tv)
size_t getIncomingSetSize ()
Get the size of the incoming set.
IncomingSet getIncomingSet ()
template<typename OutputIterator >
OutputIterator getIncomingSet (OutputIterator result)
template<class T >
bool foreach_incoming (bool(T::*cb)(const Handle &), T *data)
template<typename OutputIterator >
OutputIterator getIncomingSetByType (OutputIterator result, Type type, bool subclass=false)
IncomingSet getIncomingSetByType (Type type, bool subclass=false)
Static Public Member Functions
static TruthValuePtr do_evaluate (AtomSpace *, Handle)
static TruthValuePtr do_evaluate (AtomSpace *, const HandleSeq &schema_and_args)
static TruthValuePtr do_evaluate (AtomSpace *, Handle schema, Handle args)
Additional Inherited Members
Protected Types inherited from opencog::Atom
typedef std::shared_ptr< InSet > InSetPtr
Protected Member Functions inherited from opencog::FreeLink
void init (void)
void find_vars (std::set< Handle > &, const HandleSeq &)
void build_index (void)
FreeLink (Type, const HandleSeq &oset, TruthValuePtr tv=TruthValue::NULL_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
FreeLink (Type, const Handle &a, TruthValuePtr tv=TruthValue::NULL_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
FreeLink (Type, const Handle &a, const Handle &b, TruthValuePtr tv=TruthValue::NULL_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
Protected Member Functions inherited from opencog::Atom
Atom (Type t, TruthValuePtr tv=TruthValue::DEFAULT_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
void keep_incoming_set ()
void drop_incoming_set ()
void insert_atom (LinkPtr)
Add an atom to the incoming set.
void remove_atom (LinkPtr)
Remove an atom from the incoming set.
Protected Attributes inherited from opencog::FreeLink
HandleSeq _varseq
std::map< Handle, unsigned int > _index
Protected Attributes inherited from opencog::Link
HandleSeq _outgoing
Protected Attributes inherited from opencog::Atom
UUID _uuid
AtomTable * _atomTable
Type _type
char _flags
TruthValuePtr _truthValue
AttentionValuePtr _attentionValue
std::mutex _mtx
InSetPtr _incoming_set
Detailed Description
Definition at line 35 of file EvaluationLink.h.
Constructor & Destructor Documentation
EvaluationLink::EvaluationLink (const HandleSeq & oset, TruthValuePtr tv = TruthValue::NULL_TV(), AttentionValuePtr av = AttentionValue::DEFAULT_AV())
Definition at line 34 of file EvaluationLink.cc.
References opencog::Atom::getType().
EvaluationLink::EvaluationLink (Handle schema, Handle args, TruthValuePtr tv = TruthValue::NULL_TV(), AttentionValuePtr av = AttentionValue::DEFAULT_AV())
Definition at line 47 of file EvaluationLink.cc.
References opencog::Atom::getType().
EvaluationLink::EvaluationLink (Link & l)
Definition at line 58 of file EvaluationLink.cc.
References opencog::Atom::getType().
Member Function Documentation
TruthValuePtr EvaluationLink::do_evaluate (AtomSpace * as, Handle execlnk) static
do_evaluate – evaluate the GroundedPredicateNode of the EvaluationLink
Expects the argument to be an EvaluationLink, which should have the following structure:
EvaluationLink
    GroundedPredicateNode "lang: func_name"
    ListLink
        SomeAtom
        OtherAtom
The "lang:" should be either "scm:" for scheme, or "py:" for python. This method will then invoke "func_name" on the provided ListLink of arguments to the function.
Definition at line 127 of file EvaluationLink.cc.
References opencog::SimpleTruthValue::createTV(), equal(), opencog::Atom::getType(), greater(), opencog::LinkCast(), python.undocumented.blocksworld::t, and tv.
TruthValuePtr EvaluationLink::do_evaluate (AtomSpace * as, const HandleSeq & sna) static
do_evaluate – evaluate the GroundedPredicateNode of the EvaluationLink
Expects the sequence to be exactly two atoms long. Expects the first handle of the sequence to be a GroundedPredicateNode Expects the second handle of the sequence to be a ListLink Executes the GroundedPredicateNode, supplying the second handle as argument
Definition at line 160 of file EvaluationLink.cc.
References do_evaluate().
TruthValuePtr EvaluationLink::do_evaluate (AtomSpace * as, Handle gsn, Handle args) static
do_evaluate – evaluate the GroundedPredicateNode of the EvaluationLink
Expects "gsn" to be a GroundedPredicateNode Expects "args" to be a ListLink Executes the GroundedPredicateNode, supplying the args as argument
Definition at line 176 of file EvaluationLink.cc.
References opencog::SchemeEval::apply_tv(), opencog::PythonEval::apply_tv(), benchmark::args, opencog::TruthValue::FALSE_TV(), opencog::SchemeEval::get_evaluator(), opencog::Atom::getType(), greater(), opencog::PythonEval::instance(), opencog::LinkCast(), opencog::NodeCast(), and opencog::TruthValue::TRUE_TV().
TruthValuePtr opencog::EvaluationLink::evaluate (AtomSpace * as) inline
Definition at line 48 of file EvaluationLink.h.
References do_evaluate(), and opencog::Atom::Handle.
The documentation for this class was generated from the following files:
opencog/atoms/execution/EvaluationLink.h
opencog/atoms/execution/EvaluationLink.cc