OpenCog Framework: opencog::ZMQServer Class Reference
opencog::ZMQServer Class Reference
atomspace library
#include <ZMQServer.h>
Public Member Functions
ZMQServer (AtomSpace *atomSpace1, string networkAddress="tcp://*:5555")
~ZMQServer ()
Private Member Functions
void zmqLoop (string networkAddress)
Private Attributes
zmq::context_t * zmqContext
zmq::socket_t * zmqClientSocket
boost::thread zmqServerThread
AtomSpace * atomSpace
Detailed Description
Definition at line 137 of file ZMQServer.h.
Constructor & Destructor Documentation
ZMQServer::ZMQServer (AtomSpace * atomSpace1, string networkAddress = "tcp://*:5555")
Definition at line 29 of file ZMQServer.cc.
References atomSpace, zmqContext, zmqLoop(), and zmqServerThread.
ZMQServer::~ZMQServer ()
TODO send signal to exit gracefully
zmqServerThread.join();
Definition at line 36 of file ZMQServer.cc.
Member Function Documentation
void ZMQServer::zmqLoop (string networkAddress) private
Definition at line 43 of file ZMQServer.cc.
References python.atom_type_names::atom, atomSpace, ZMQRequestMessage::function(), ZMQRequestMessage::handle(), ZMQReplyMessage::mutable_atom(), opencog::ProtocolBufferSerializer::serialize(), zmqContext, and ZMQgetAtom.
Member Data Documentation
AtomSpace* opencog::ZMQServer::atomSpace private
Definition at line 141 of file ZMQServer.h.
zmq::socket_t* opencog::ZMQServer::zmqClientSocket private
Definition at line 139 of file ZMQServer.h.
zmq::context_t* opencog::ZMQServer::zmqContext private
Definition at line 138 of file ZMQServer.h.
boost::thread opencog::ZMQServer::zmqServerThread private
Definition at line 140 of file ZMQServer.h.
The documentation for this class was generated from the following files:
opencog/persist/zmq/atomspace/ZMQServer.h
opencog/persist/zmq/atomspace/ZMQServer.cc