OpenCog Framework: opencog::NameIndex Class Reference
opencog::NameIndex Class Reference
#include <NameIndex.h>
Public Member Functions
void insertAtom (Atom *a)
void removeAtom (Atom *a)
Public Member Functions inherited from opencog::StringIndex
void insert (const std::string &str, Atom *a)
Atom * get (const std::string &str) const
void remove (const std::string &str)
size_t size (void) const
Detailed Description
Implements an atom name index as an RB-tree (C++ map) That is, given an atom name, this returns an AtomPtr to that atom. This class can only hold one AtomPtr for a given name. For a multi-name storage, use the NodeIndex, which keys by name and atom type.
Definition at line 40 of file NameIndex.h.
Member Function Documentation
void opencog::NameIndex::insertAtom (Atom * a) inline
Definition at line 44 of file NameIndex.h.
References python.create_atoms_by_type::a, opencog::Node::getName(), and opencog::StringIndex::insert().
void opencog::NameIndex::removeAtom (Atom * a) inline
Definition at line 50 of file NameIndex.h.
References python.create_atoms_by_type::a, and opencog::Node::getName().
The documentation for this class was generated from the following file:
opencog/atomspace/NameIndex.h