OpenCog Framework: opencog::LambdaLink Class Reference
opencog::LambdaLink Class Reference
atomspace library
#include <LambdaLink.h>
Public Member Functions
LambdaLink (const HandleSeq &, TruthValuePtr tv=TruthValue::DEFAULT_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
LambdaLink (const Handle &varcdecls, const Handle &body, TruthValuePtr tv=TruthValue::DEFAULT_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
LambdaLink (Link &l)
Handle substitute (const HandleSeq &vals) const
Public Member Functions inherited from opencog::VariableList
VariableList (const HandleSeq &vardecls, TruthValuePtr tv=TruthValue::DEFAULT_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
VariableList (Link &)
const Variables & get_variables (void) const
bool is_type (const Handle &) const
bool is_type (const HandleSeq &) const
Handle substitute (const Handle &tree, const HandleSeq &vals) const
Public Member Functions inherited from opencog::Link
Link (Type t, const HandleSeq &oset, TruthValuePtr tv=TruthValue::DEFAULT_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
Link (Type t, const Handle &h, TruthValuePtr tv=TruthValue::DEFAULT_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
Link (Type t, const Handle &ha, const Handle &hb, TruthValuePtr tv=TruthValue::DEFAULT_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
Link (Type t, const Handle &ha, const Handle &hb, const Handle &hc, TruthValuePtr tv=TruthValue::DEFAULT_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
Link (Type t, const Handle &ha, const Handle &hb, const Handle &hc, const Handle &hd, TruthValuePtr tv=TruthValue::DEFAULT_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
Link (Link &l)
~Link ()
Arity getArity () const
const HandleSeq & getOutgoingSet () const
Handle getOutgoingAtom (Arity pos) const throw (RuntimeException)
template<class T >
bool foreach_outgoing (bool(T::*cb)(const Handle &), T *data)
std::string toString (std::string indent="")
std::string toShortString (std::string indent="")
bool isSource (Handle) const throw (InvalidParamException)
bool isSource (size_t) const throw (IndexErrorException, InvalidParamException)
bool isTarget (Handle) const throw (InvalidParamException)
bool isTarget (size_t) const throw (IndexErrorException, InvalidParamException)
virtual bool operator== (const Atom &) const
virtual bool operator!= (const Atom &) const
Public Member Functions inherited from opencog::Atom
virtual ~Atom ()
Type getType () const
bool isType (Type t, bool subclass) const
Handle getHandle ()
AttentionValuePtr getAttentionValue ()
void setAttentionValue (AttentionValuePtr)
Sets the AttentionValue object of the atom.
AttentionValue::sti_t getSTI ()
Handy-dandy convenience getters for attention values.
AttentionValue::lti_t getLTI ()
AttentionValue::vlti_t getVLTI ()
void setSTI (AttentionValue::sti_t stiValue)
void setLTI (AttentionValue::lti_t ltiValue)
void incVLTI ()
void decVLTI ()
TruthValuePtr getTruthValue ()
void setTruthValue (TruthValuePtr)
Sets the TruthValue object of the atom.
void merge (TruthValuePtr)
Handle tvmerge (TruthValuePtr tv)
size_t getIncomingSetSize ()
Get the size of the incoming set.
IncomingSet getIncomingSet ()
template<typename OutputIterator >
OutputIterator getIncomingSet (OutputIterator result)
template<class T >
bool foreach_incoming (bool(T::*cb)(const Handle &), T *data)
template<typename OutputIterator >
OutputIterator getIncomingSetByType (OutputIterator result, Type type, bool subclass=false)
IncomingSet getIncomingSetByType (Type type, bool subclass=false)
Protected Member Functions
LambdaLink (Type, const HandleSeq &, TruthValuePtr tv=TruthValue::DEFAULT_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
void init (const HandleSeq &)
Protected Member Functions inherited from opencog::VariableList
void get_vartype (const Handle &)
void validate_vardecl (const Handle &)
void validate_vardecl (const HandleSeq &)
VariableList (Type, const HandleSeq &, TruthValuePtr tv=TruthValue::DEFAULT_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
void build_index (void)
Handle substitute_nocheck (const Handle &, const HandleSeq &) const
Protected Member Functions inherited from opencog::Atom
Atom (Type t, TruthValuePtr tv=TruthValue::DEFAULT_TV(), AttentionValuePtr av=AttentionValue::DEFAULT_AV())
void keep_incoming_set ()
void drop_incoming_set ()
void insert_atom (LinkPtr)
Add an atom to the incoming set.
void remove_atom (LinkPtr)
Remove an atom from the incoming set.
Static Protected Member Functions
static void prt (const Handle &h)
Protected Attributes
Handle _body
Handle of the body of the expression.
Protected Attributes inherited from opencog::VariableList
Variables _varlist
Unbundled variables and types for them.
Protected Attributes inherited from opencog::Link
HandleSeq _outgoing
Protected Attributes inherited from opencog::Atom
UUID _uuid
AtomTable * _atomTable
Type _type
char _flags
TruthValuePtr _truthValue
AttentionValuePtr _attentionValue
std::mutex _mtx
InSetPtr _incoming_set
Additional Inherited Members
Protected Types inherited from opencog::Atom
typedef std::shared_ptr< InSet > InSetPtr
Detailed Description
The LambdaLink consitsts of two parts: An optional variable declaration, follwed by an expression body. If a variable declaration is present, then it must conform to current variable declaration standards: i.e. it must be either a single VariableNode, a single TypedVariableLink, or a VariableList. This is then followed by a body, of any arbitrary form. This class does little other than to check for the above-described format, and unpacke the variable decalrations, if present; it will throw an error if an ill-formed LambdaLink is inserted into the atomspace. (As usual, the point of unpacked variables is to act as a memo or cache, speeding up later calculations.)
Definition at line 47 of file LambdaLink.h.
Constructor & Destructor Documentation
LambdaLink::LambdaLink (Type t, const HandleSeq & oset, TruthValuePtr tv = TruthValue::DEFAULT_TV(), AttentionValuePtr av = AttentionValue::DEFAULT_AV()) protected
Definition at line 58 of file LambdaLink.cc.
References init().
LambdaLink::LambdaLink (const HandleSeq & oset, TruthValuePtr tv = TruthValue::DEFAULT_TV(), AttentionValuePtr av = AttentionValue::DEFAULT_AV())
Definition at line 44 of file LambdaLink.cc.
References init().
LambdaLink::LambdaLink (const Handle & varcdecls, const Handle & body, TruthValuePtr tv = TruthValue::DEFAULT_TV(), AttentionValuePtr av = AttentionValue::DEFAULT_AV())
Definition at line 51 of file LambdaLink.cc.
LambdaLink::LambdaLink (Link & l)
Definition at line 67 of file LambdaLink.cc.
References opencog::classserver(), opencog::Link::getOutgoingSet(), opencog::Atom::getType(), opencog::ClassServer::getTypeName(), and init().
Member Function Documentation
void LambdaLink::init (const HandleSeq & oset) protected
Definition at line 33 of file LambdaLink.cc.
References _body, and opencog::VariableList::validate_vardecl().
static void opencog::LambdaLink::prt (const Handle & h) inline static protected
Definition at line 60 of file LambdaLink.h.
References opencog::Atom::toShortString().
Handle opencog::LambdaLink::substitute (const HandleSeq & vals) const inline
Definition at line 78 of file LambdaLink.h.
References _body, and opencog::VariableList::substitute().
Member Data Documentation
Handle opencog::LambdaLink::_body protected
Handle of the body of the expression.
Definition at line 51 of file LambdaLink.h.
The documentation for this class was generated from the following files:
opencog/atoms/bind/LambdaLink.h
opencog/atoms/bind/LambdaLink.cc