var annotated =
[
    [ "benchmark", "de/dd8/namespacebenchmark.html", "de/dd8/namespacebenchmark" ],
    [ "google", "df/d40/namespacegoogle.html", "df/d40/namespacegoogle" ],
    [ "make_benchmark_graphs", "da/d4f/namespacemake__benchmark__graphs.html", null ],
    [ "my_py_func", "d5/dc6/namespacemy__py__func.html", null ],
    [ "opencog", "dc/d0d/namespaceopencog.html", "dc/d0d/namespaceopencog" ],
    [ "python", "de/d4a/namespacepython.html", "de/d4a/namespacepython" ],
    [ "reorder_log", "d0/d91/namespacereorder__log.html", null ],
    [ "sokoban", "de/d49/namespacesokoban.html", "de/d49/namespacesokoban" ],
    [ "std", "d8/dcc/namespacestd.html", "d8/dcc/namespacestd" ],
    [ "update-links", "d5/d85/namespaceupdate-links.html", null ],
    [ "viz_graph", "db/da6/namespaceviz__graph.html", "db/da6/namespaceviz__graph" ],
    [ "HandleComparison", "d3/d40/structHandleComparison.html", "d3/d40/structHandleComparison" ],
    [ "MyTestClass", "da/d30/classMyTestClass.html", "da/d30/classMyTestClass" ],
    [ "ODBCConnection", "de/d4a/classODBCConnection.html", "de/d4a/classODBCConnection" ],
    [ "ODBCRecordSet", "d6/da0/classODBCRecordSet.html", "d6/da0/classODBCRecordSet" ],
    [ "option", "d6/d43/structoption.html", "d6/d43/structoption" ],
    [ "PMCGroundings", "de/d28/classPMCGroundings.html", "de/d28/classPMCGroundings" ],
    [ "StaticDescriptorInitializer_ZMQMessages_2eproto", "d3/d4b/structStaticDescriptorInitializer__ZMQMessages__2eproto.html", "d3/d4b/structStaticDescriptorInitializer__ZMQMessages__2eproto" ],
    [ "ZMQAtomMessage", "df/db6/classZMQAtomMessage.html", "df/db6/classZMQAtomMessage" ],
    [ "ZMQAttentionValueHolderMessage", "d1/d9c/classZMQAttentionValueHolderMessage.html", "d1/d9c/classZMQAttentionValueHolderMessage" ],
    [ "ZMQReplyMessage", "d1/dbd/classZMQReplyMessage.html", "d1/dbd/classZMQReplyMessage" ],
    [ "ZMQRequestMessage", "d5/d28/classZMQRequestMessage.html", "d5/d28/classZMQRequestMessage" ],
    [ "ZMQSingleTruthValueMessage", "dd/d3a/classZMQSingleTruthValueMessage.html", "dd/d3a/classZMQSingleTruthValueMessage" ],
    [ "ZMQTrailMessage", "dc/d9a/classZMQTrailMessage.html", "dc/d9a/classZMQTrailMessage" ],
    [ "ZMQTruthValueMessage", "d0/d4d/classZMQTruthValueMessage.html", "d0/d4d/classZMQTruthValueMessage" ],
    [ "ZMQVersionHandleMessage", "de/df2/classZMQVersionHandleMessage.html", "de/df2/classZMQVersionHandleMessage" ]
];