OpenCog Framework: opencog/atoms/execution/EvaluationLink.cc File Reference
EvaluationLink.cc File Reference
#include <opencog/atomspace/atom_types.h>
#include <opencog/atomspace/AtomSpace.h>
#include <opencog/atomspace/SimpleTruthValue.h>
#include <opencog/atoms/NumberNode.h>
#include <opencog/atoms/reduct/FunctionLink.h>
#include <opencog/cython/PythonEval.h>
#include <opencog/guile/SchemeEval.h>
#include "EvaluationLink.h"
Functions
static TruthValuePtr greater (AtomSpace *as, LinkPtr ll)
static TruthValuePtr equal (AtomSpace *as, LinkPtr ll)
Function Documentation
static TruthValuePtr equal (AtomSpace * as, LinkPtr ll) static
Definition at line 100 of file EvaluationLink.cc.
References opencog::TruthValue::FALSE_TV(), and opencog::TruthValue::TRUE_TV().
static TruthValuePtr greater (AtomSpace * as, LinkPtr ll) static
Definition at line 69 of file EvaluationLink.cc.
References opencog::FunctionLink::do_execute(), opencog::TruthValue::FALSE_TV(), opencog::NumberNodeCast(), and opencog::TruthValue::TRUE_TV().