OpenCog Framework: opencog::TypeIndex::iterator Class Reference
opencog::TypeIndex::iterator Class Reference
#include <TypeIndex.h>
Public Member Functions
iterator (Type, bool)
iterator & operator++ ()
iterator & operator++ (int)
iterator & operator= (iterator)
bool operator== (iterator)
bool operator!= (iterator)
Handle operator* (void)
Private Attributes
Type type
bool subclass
std::vector< UnorderedAtomSet >
::const_iterator s
std::vector< UnorderedAtomSet >
::const_iterator send
Type currtype
UnorderedAtomSet::const_iterator se
Friends
class TypeIndex
Detailed Description
Definition at line 69 of file TypeIndex.h.
Constructor & Destructor Documentation
TypeIndex::iterator::iterator (Type t, bool sub)
Definition at line 99 of file TypeIndex.cc.
References subclass, python.undocumented.blocksworld::t, and type.
Member Function Documentation
bool TypeIndex::iterator::operator!= (iterator v)
Definition at line 128 of file TypeIndex.cc.
References s, se, and send.
Handle TypeIndex::iterator::operator* (void)
Definition at line 116 of file TypeIndex.cc.
References opencog::Atom::getHandle(), and opencog::Handle::UNDEFINED.
TypeIndex::iterator & TypeIndex::iterator::operator++ ()
Definition at line 135 of file TypeIndex.cc.
TypeIndex::iterator & TypeIndex::iterator::operator++ (int i)
Definition at line 140 of file TypeIndex.cc.
References opencog::classserver(), and opencog::ClassServer::isA().
TypeIndex::iterator & TypeIndex::iterator::operator= (iterator v)
Definition at line 105 of file TypeIndex.cc.
References currtype, s, se, send, subclass, and type.
bool TypeIndex::iterator::operator== (iterator v)
Definition at line 122 of file TypeIndex.cc.
References s, se, and send.
Friends And Related Function Documentation
friend class TypeIndex friend
Definition at line 72 of file TypeIndex.h.
Member Data Documentation
Type opencog::TypeIndex::iterator::currtype private
Definition at line 86 of file TypeIndex.h.
std::vector<UnorderedAtomSet>::const_iterator opencog::TypeIndex::iterator::s private
Definition at line 84 of file TypeIndex.h.
UnorderedAtomSet::const_iterator opencog::TypeIndex::iterator::se private
Definition at line 87 of file TypeIndex.h.
std::vector<UnorderedAtomSet>::const_iterator opencog::TypeIndex::iterator::send private
Definition at line 85 of file TypeIndex.h.
bool opencog::TypeIndex::iterator::subclass private
Definition at line 83 of file TypeIndex.h.
Type opencog::TypeIndex::iterator::type private
Definition at line 82 of file TypeIndex.h.
The documentation for this class was generated from the following files:
opencog/atomspace/TypeIndex.h
opencog/atomspace/TypeIndex.cc