OpenCog Framework: ZMQAtomMessage Class Reference
ZMQAtomMessage Class Reference
#include <ZMQMessages.pb.h>
Public Member Functions
ZMQAtomMessage ()
virtual ~ZMQAtomMessage ()
ZMQAtomMessage (const ZMQAtomMessage &from)
ZMQAtomMessage & operator= (const ZMQAtomMessage &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (ZMQAtomMessage *other)
ZMQAtomMessage * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const ZMQAtomMessage &from)
void MergeFrom (const ZMQAtomMessage &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_atomtype () const
void clear_atomtype ()
ZMQAtomType atomtype () const
void set_atomtype (ZMQAtomType value)
bool has_attentionvalueholder () const
void clear_attentionvalueholder ()
const
::ZMQAttentionValueHolderMessage & attentionvalueholder () const
inline::ZMQAttentionValueHolderMessage * mutable_attentionvalueholder ()
inline::ZMQAttentionValueHolderMessage * release_attentionvalueholder ()
bool has_handle () const
void clear_handle ()
inline::google::protobuf::uint64 handle () const
void set_handle (::google::protobuf::uint64 value)
int incoming_size () const
void clear_incoming ()
inline::google::protobuf::uint64 incoming (int index) const
void set_incoming (int index,::google::protobuf::uint64 value)
void add_incoming (::google::protobuf::uint64 value)
const
::google::protobuf::RepeatedField
< ::google::protobuf::uint64 > & incoming () const
inline::google::protobuf::RepeatedField
< ::google::protobuf::uint64 > * mutable_incoming ()
bool has_type () const
void clear_type ()
inline::google::protobuf::int32 type () const
void set_type (::google::protobuf::int32 value)
bool has_flags () const
void clear_flags ()
inline::google::protobuf::int32 flags () const
void set_flags (::google::protobuf::int32 value)
bool has_truthvalue () const
void clear_truthvalue ()
const ::ZMQTruthValueMessage & truthvalue () const
inline::ZMQTruthValueMessage * mutable_truthvalue ()
inline::ZMQTruthValueMessage * release_truthvalue ()
bool has_name () const
void clear_name ()
const ::std::string & name () const
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
inline::std::string * mutable_name ()
inline::std::string * release_name ()
int outgoing_size () const
void clear_outgoing ()
inline::google::protobuf::uint64 outgoing (int index) const
void set_outgoing (int index,::google::protobuf::uint64 value)
void add_outgoing (::google::protobuf::uint64 value)
const
::google::protobuf::RepeatedField
< ::google::protobuf::uint64 > & outgoing () const
inline::google::protobuf::RepeatedField
< ::google::protobuf::uint64 > * mutable_outgoing ()
bool has_trail () const
void clear_trail ()
const ::ZMQTrailMessage & trail () const
inline::ZMQTrailMessage * mutable_trail ()
inline::ZMQTrailMessage * release_trail ()
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const ZMQAtomMessage & default_instance ()
Static Public Attributes
static const int kAtomtypeFieldNumber = 1
static const int kAttentionvalueholderFieldNumber = 2
static const int kHandleFieldNumber = 3
static const int kIncomingFieldNumber = 4
static const int kTypeFieldNumber = 5
static const int kFlagsFieldNumber = 6
static const int kTruthValueFieldNumber = 7
static const int kNameFieldNumber = 8
static const int kOutgoingFieldNumber = 9
static const int kTrailFieldNumber = 10
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_atomtype ()
void clear_has_atomtype ()
void set_has_attentionvalueholder ()
void clear_has_attentionvalueholder ()
void set_has_handle ()
void clear_has_handle ()
void set_has_type ()
void clear_has_type ()
void set_has_flags ()
void clear_has_flags ()
void set_has_truthvalue ()
void clear_has_truthvalue ()
void set_has_name ()
void clear_has_name ()
void set_has_trail ()
void clear_has_trail ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::ZMQAttentionValueHolderMessage * attentionvalueholder_
::google::protobuf::uint64 handle_
int atomtype_
::google::protobuf::int32 type_
::google::protobuf::RepeatedField
< ::google::protobuf::uint64 > incoming_
::ZMQTruthValueMessage * truthvalue_
::std::string * name_
::google::protobuf::RepeatedField
< ::google::protobuf::uint64 > outgoing_
::ZMQTrailMessage * trail_
::google::protobuf::int32 flags_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(10+31)/32]
Static Private Attributes
static ZMQAtomMessage * default_instance_ = NULL
Friends
void protobuf_AddDesc_ZMQMessages_2eproto ()
void protobuf_AssignDesc_ZMQMessages_2eproto ()
void protobuf_ShutdownFile_ZMQMessages_2eproto ()
Detailed Description
Definition at line 664 of file ZMQMessages.pb.h.
Constructor & Destructor Documentation
ZMQAtomMessage::ZMQAtomMessage ()
Definition at line 1998 of file ZMQMessages.pb.cc.
References SharedCtor().
ZMQAtomMessage::~ZMQAtomMessage () virtual
Definition at line 2028 of file ZMQMessages.pb.cc.
References SharedDtor().
ZMQAtomMessage::ZMQAtomMessage (const ZMQAtomMessage & from)
Definition at line 2009 of file ZMQMessages.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
void ZMQAtomMessage::add_incoming (::google::protobuf::uint64 value) inline
Definition at line 1585 of file ZMQMessages.pb.h.
References incoming_.
void ZMQAtomMessage::add_outgoing (::google::protobuf::uint64 value) inline
Definition at line 1741 of file ZMQMessages.pb.h.
References outgoing_.
ZMQAtomType ZMQAtomMessage::atomtype () const inline
Definition at line 1512 of file ZMQMessages.pb.h.
References atomtype_.
const ::ZMQAttentionValueHolderMessage & ZMQAtomMessage::attentionvalueholder () const inline
Definition at line 1535 of file ZMQMessages.pb.h.
References attentionvalueholder_, and default_instance_.
int ZMQAtomMessage::ByteSize () const
Definition at line 2426 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, atomtype(), attentionvalueholder(), flags(), handle(), has_atomtype(), has_attentionvalueholder(), has_flags(), has_handle(), has_name(), has_trail(), has_truthvalue(), has_type(), incoming(), incoming_size(), name(), outgoing(), outgoing_size(), trail(), truthvalue(), type(), and unknown_fields().
void ZMQAtomMessage::Clear ()
Definition at line 2063 of file ZMQMessages.pb.cc.
References _has_bits_, atomtype_, attentionvalueholder_, flags_, handle_, has_attentionvalueholder(), has_name(), has_trail(), has_truthvalue(), incoming_, mutable_unknown_fields(), name_, outgoing_, trail_, truthvalue_, and type_.
void ZMQAtomMessage::clear_atomtype () inline
Definition at line 1508 of file ZMQMessages.pb.h.
References atomtype_, and clear_has_atomtype().
void ZMQAtomMessage::clear_attentionvalueholder () inline
Definition at line 1531 of file ZMQMessages.pb.h.
References attentionvalueholder_, and clear_has_attentionvalueholder().
void ZMQAtomMessage::clear_flags () inline
Definition at line 1629 of file ZMQMessages.pb.h.
References clear_has_flags(), and flags_.
void ZMQAtomMessage::clear_handle () inline
Definition at line 1560 of file ZMQMessages.pb.h.
References clear_has_handle(), and handle_.
void ZMQAtomMessage::clear_has_atomtype () inline private
Definition at line 1505 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAtomMessage::clear_has_attentionvalueholder () inline private
Definition at line 1528 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAtomMessage::clear_has_flags () inline private
Definition at line 1626 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAtomMessage::clear_has_handle () inline private
Definition at line 1557 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAtomMessage::clear_has_name () inline private
Definition at line 1677 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAtomMessage::clear_has_trail () inline private
Definition at line 1760 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAtomMessage::clear_has_truthvalue () inline private
Definition at line 1648 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAtomMessage::clear_has_type () inline private
Definition at line 1604 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAtomMessage::clear_incoming () inline
Definition at line 1576 of file ZMQMessages.pb.h.
References incoming_.
void ZMQAtomMessage::clear_name () inline
Definition at line 1680 of file ZMQMessages.pb.h.
References clear_has_name(), and name_.
void ZMQAtomMessage::clear_outgoing () inline
Definition at line 1732 of file ZMQMessages.pb.h.
References outgoing_.
void ZMQAtomMessage::clear_trail () inline
Definition at line 1763 of file ZMQMessages.pb.h.
References clear_has_trail(), and trail_.
void ZMQAtomMessage::clear_truthvalue () inline
Definition at line 1651 of file ZMQMessages.pb.h.
References clear_has_truthvalue(), and truthvalue_.
void ZMQAtomMessage::clear_type () inline
Definition at line 1607 of file ZMQMessages.pb.h.
References clear_has_type(), and type_.
void ZMQAtomMessage::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 2566 of file ZMQMessages.pb.cc.
References Clear(), and MergeFrom().
void ZMQAtomMessage::CopyFrom (const ZMQAtomMessage & from)
Definition at line 2572 of file ZMQMessages.pb.cc.
References Clear(), and MergeFrom().
const ZMQAtomMessage & ZMQAtomMessage::default_instance () static
Definition at line 2053 of file ZMQMessages.pb.cc.
References default_instance_, and protobuf_AddDesc_ZMQMessages_2eproto.
const ::google::protobuf::Descriptor * ZMQAtomMessage::descriptor () static
Definition at line 2048 of file ZMQMessages.pb.cc.
google::protobuf::int32 ZMQAtomMessage::flags () const inline
Definition at line 1633 of file ZMQMessages.pb.h.
References flags_.
int ZMQAtomMessage::GetCachedSize () const inline
Definition at line 705 of file ZMQMessages.pb.h.
References _cached_size_.
google::protobuf::Metadata ZMQAtomMessage::GetMetadata () const
Definition at line 2611 of file ZMQMessages.pb.cc.
google::protobuf::uint64 ZMQAtomMessage::handle () const inline
Definition at line 1564 of file ZMQMessages.pb.h.
References handle_.
bool ZMQAtomMessage::has_atomtype () const inline
Definition at line 1499 of file ZMQMessages.pb.h.
References _has_bits_.
bool ZMQAtomMessage::has_attentionvalueholder () const inline
Definition at line 1522 of file ZMQMessages.pb.h.
References _has_bits_.
bool ZMQAtomMessage::has_flags () const inline
Definition at line 1620 of file ZMQMessages.pb.h.
References _has_bits_.
bool ZMQAtomMessage::has_handle () const inline
Definition at line 1551 of file ZMQMessages.pb.h.
References _has_bits_.
bool ZMQAtomMessage::has_name () const inline
Definition at line 1671 of file ZMQMessages.pb.h.
References _has_bits_.
bool ZMQAtomMessage::has_trail () const inline
Definition at line 1754 of file ZMQMessages.pb.h.
References _has_bits_.
bool ZMQAtomMessage::has_truthvalue () const inline
Definition at line 1642 of file ZMQMessages.pb.h.
References _has_bits_.
bool ZMQAtomMessage::has_type () const inline
Definition at line 1598 of file ZMQMessages.pb.h.
References _has_bits_.
google::protobuf::uint64 ZMQAtomMessage::incoming (int index) const inline
Definition at line 1579 of file ZMQMessages.pb.h.
References incoming_.
const ::google::protobuf::RepeatedField<::google::protobuf::uint64 > & ZMQAtomMessage::incoming () const inline
Definition at line 1589 of file ZMQMessages.pb.h.
References incoming_.
int ZMQAtomMessage::incoming_size () const inline
Definition at line 1573 of file ZMQMessages.pb.h.
References incoming_.
void ZMQAtomMessage::InitAsDefaultInstance () private
Definition at line 2003 of file ZMQMessages.pb.cc.
References attentionvalueholder_, ZMQAttentionValueHolderMessage::default_instance(), ZMQTruthValueMessage::default_instance(), ZMQTrailMessage::default_instance(), trail_, and truthvalue_.
bool ZMQAtomMessage::IsInitialized () const
Definition at line 2578 of file ZMQMessages.pb.cc.
References _has_bits_, attentionvalueholder(), has_attentionvalueholder(), has_trail(), has_truthvalue(), trail(), and truthvalue().
void ZMQAtomMessage::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 2519 of file ZMQMessages.pb.cc.
void ZMQAtomMessage::MergeFrom (const ZMQAtomMessage & from)
Definition at line 2531 of file ZMQMessages.pb.cc.
References _has_bits_, atomtype(), attentionvalueholder(), flags(), handle(), has_atomtype(), has_attentionvalueholder(), has_flags(), has_handle(), has_name(), has_trail(), has_truthvalue(), has_type(), incoming_, mutable_attentionvalueholder(), mutable_trail(), mutable_truthvalue(), mutable_unknown_fields(), name(), outgoing_, set_atomtype(), set_flags(), set_handle(), set_name(), set_type(), trail(), truthvalue(), type(), and unknown_fields().
bool ZMQAtomMessage::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 2092 of file ZMQMessages.pb.cc.
References python.atom_type_names::data, DO_, flags_, handle_, mutable_attentionvalueholder(), mutable_incoming(), mutable_name(), mutable_outgoing(), mutable_trail(), mutable_truthvalue(), mutable_unknown_fields(), name(), set_atomtype(), set_has_flags(), set_has_handle(), set_has_type(), type_, and ZMQAtomType_IsValid().
ZMQAttentionValueHolderMessage * ZMQAtomMessage::mutable_attentionvalueholder () inline
Definition at line 1538 of file ZMQMessages.pb.h.
References attentionvalueholder_, and set_has_attentionvalueholder().
google::protobuf::RepeatedField<::google::protobuf::uint64 > * ZMQAtomMessage::mutable_incoming () inline
Definition at line 1593 of file ZMQMessages.pb.h.
References incoming_.
std::string * ZMQAtomMessage::mutable_name () inline
Definition at line 1710 of file ZMQMessages.pb.h.
References name_, and set_has_name().
google::protobuf::RepeatedField<::google::protobuf::uint64 > * ZMQAtomMessage::mutable_outgoing () inline
Definition at line 1749 of file ZMQMessages.pb.h.
References outgoing_.
ZMQTrailMessage * ZMQAtomMessage::mutable_trail () inline
Definition at line 1770 of file ZMQMessages.pb.h.
References set_has_trail(), and trail_.
ZMQTruthValueMessage * ZMQAtomMessage::mutable_truthvalue () inline
Definition at line 1658 of file ZMQMessages.pb.h.
References set_has_truthvalue(), and truthvalue_.
inline ::google::protobuf::UnknownFieldSet* ZMQAtomMessage::mutable_unknown_fields () inline
Definition at line 680 of file ZMQMessages.pb.h.
References _unknown_fields_.
const ::std::string & ZMQAtomMessage::name () const inline
Definition at line 1686 of file ZMQMessages.pb.h.
References name_.
ZMQAtomMessage * ZMQAtomMessage::New () const
Definition at line 2059 of file ZMQMessages.pb.cc.
References ZMQAtomMessage().
ZMQAtomMessage& ZMQAtomMessage::operator= (const ZMQAtomMessage & from) inline
Definition at line 671 of file ZMQMessages.pb.h.
References CopyFrom().
google::protobuf::uint64 ZMQAtomMessage::outgoing (int index) const inline
Definition at line 1735 of file ZMQMessages.pb.h.
References outgoing_.
const ::google::protobuf::RepeatedField<::google::protobuf::uint64 > & ZMQAtomMessage::outgoing () const inline
Definition at line 1745 of file ZMQMessages.pb.h.
References outgoing_.
int ZMQAtomMessage::outgoing_size () const inline
Definition at line 1729 of file ZMQMessages.pb.h.
References outgoing_.
ZMQAttentionValueHolderMessage * ZMQAtomMessage::release_attentionvalueholder () inline
Definition at line 1543 of file ZMQMessages.pb.h.
References attentionvalueholder_, and clear_has_attentionvalueholder().
std::string * ZMQAtomMessage::release_name () inline
Definition at line 1717 of file ZMQMessages.pb.h.
References clear_has_name(), and name_.
ZMQTrailMessage * ZMQAtomMessage::release_trail () inline
Definition at line 1775 of file ZMQMessages.pb.h.
References clear_has_trail(), and trail_.
ZMQTruthValueMessage * ZMQAtomMessage::release_truthvalue () inline
Definition at line 1663 of file ZMQMessages.pb.h.
References clear_has_truthvalue(), and truthvalue_.
void ZMQAtomMessage::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 2285 of file ZMQMessages.pb.cc.
References atomtype(), attentionvalueholder(), python.atom_type_names::data, flags(), handle(), has_atomtype(), has_attentionvalueholder(), has_flags(), has_handle(), has_name(), has_trail(), has_truthvalue(), has_type(), incoming(), incoming_size(), name(), outgoing(), outgoing_size(), trail(), truthvalue(), type(), and unknown_fields().
google::protobuf::uint8 * ZMQAtomMessage::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 2353 of file ZMQMessages.pb.cc.
References atomtype(), attentionvalueholder(), python.atom_type_names::data, flags(), handle(), has_atomtype(), has_attentionvalueholder(), has_flags(), has_handle(), has_name(), has_trail(), has_truthvalue(), has_type(), incoming(), incoming_size(), name(), outgoing(), outgoing_size(), trail(), truthvalue(), type(), and unknown_fields().
void ZMQAtomMessage::set_atomtype (ZMQAtomType value) inline
Definition at line 1515 of file ZMQMessages.pb.h.
References atomtype_, set_has_atomtype(), and ZMQAtomType_IsValid().
void ZMQAtomMessage::set_flags (::google::protobuf::int32 value) inline
Definition at line 1636 of file ZMQMessages.pb.h.
References flags_, and set_has_flags().
void ZMQAtomMessage::set_handle (::google::protobuf::uint64 value) inline
Definition at line 1567 of file ZMQMessages.pb.h.
References handle_, and set_has_handle().
void ZMQAtomMessage::set_has_atomtype () inline private
Definition at line 1502 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAtomMessage::set_has_attentionvalueholder () inline private
Definition at line 1525 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAtomMessage::set_has_flags () inline private
Definition at line 1623 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAtomMessage::set_has_handle () inline private
Definition at line 1554 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAtomMessage::set_has_name () inline private
Definition at line 1674 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAtomMessage::set_has_trail () inline private
Definition at line 1757 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAtomMessage::set_has_truthvalue () inline private
Definition at line 1645 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAtomMessage::set_has_type () inline private
Definition at line 1601 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAtomMessage::set_incoming (int index, ::google::protobuf::uint64 value) inline
Definition at line 1582 of file ZMQMessages.pb.h.
References incoming_.
void ZMQAtomMessage::set_name (const ::std::string & value) inline
Definition at line 1689 of file ZMQMessages.pb.h.
References name_, and set_has_name().
void ZMQAtomMessage::set_name (const char * value) inline
Definition at line 1696 of file ZMQMessages.pb.h.
References name_, and set_has_name().
void ZMQAtomMessage::set_name (const char * value, size_t size) inline
Definition at line 1703 of file ZMQMessages.pb.h.
References name_, and set_has_name().
void ZMQAtomMessage::set_outgoing (int index, ::google::protobuf::uint64 value) inline
Definition at line 1738 of file ZMQMessages.pb.h.
References outgoing_.
void ZMQAtomMessage::set_type (::google::protobuf::int32 value) inline
Definition at line 1614 of file ZMQMessages.pb.h.
References set_has_type(), and type_.
void ZMQAtomMessage::SetCachedSize (int size) const private
Definition at line 2043 of file ZMQMessages.pb.cc.
References _cached_size_.
void ZMQAtomMessage::SharedCtor () private
Definition at line 2015 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, atomtype_, attentionvalueholder_, flags_, handle_, name_, trail_, truthvalue_, and type_.
void ZMQAtomMessage::SharedDtor () private
Definition at line 2032 of file ZMQMessages.pb.cc.
References attentionvalueholder_, default_instance_, name_, trail_, and truthvalue_.
void ZMQAtomMessage::Swap (ZMQAtomMessage * other)
Definition at line 2593 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, atomtype_, attentionvalueholder_, flags_, handle_, incoming_, name_, outgoing_, trail_, truthvalue_, and type_.
const ::ZMQTrailMessage & ZMQAtomMessage::trail () const inline
Definition at line 1767 of file ZMQMessages.pb.h.
References default_instance_, and trail_.
const ::ZMQTruthValueMessage & ZMQAtomMessage::truthvalue () const inline
Definition at line 1655 of file ZMQMessages.pb.h.
References default_instance_, and truthvalue_.
google::protobuf::int32 ZMQAtomMessage::type () const inline
Definition at line 1611 of file ZMQMessages.pb.h.
References type_.
const ::google::protobuf::UnknownFieldSet& ZMQAtomMessage::unknown_fields () const inline
Definition at line 676 of file ZMQMessages.pb.h.
References _unknown_fields_.
Friends And Related Function Documentation
void protobuf_AddDesc_ZMQMessages_2eproto () friend
Definition at line 254 of file ZMQMessages.pb.cc.
void protobuf_AssignDesc_ZMQMessages_2eproto () friend
Definition at line 49 of file ZMQMessages.pb.cc.
void protobuf_ShutdownFile_ZMQMessages_2eproto () friend
Definition at line 235 of file ZMQMessages.pb.cc.
Member Data Documentation
int ZMQAtomMessage::_cached_size_ mutable private
Definition at line 837 of file ZMQMessages.pb.h.
::google::protobuf::uint32 ZMQAtomMessage::_has_bits_[(10+31)/32] private
Definition at line 838 of file ZMQMessages.pb.h.
::google::protobuf::UnknownFieldSet ZMQAtomMessage::_unknown_fields_ private
Definition at line 824 of file ZMQMessages.pb.h.
int ZMQAtomMessage::atomtype_ private
Definition at line 828 of file ZMQMessages.pb.h.
::ZMQAttentionValueHolderMessage* ZMQAtomMessage::attentionvalueholder_ private
Definition at line 826 of file ZMQMessages.pb.h.
ZMQAtomMessage * ZMQAtomMessage::default_instance_ = NULL static private
Definition at line 845 of file ZMQMessages.pb.h.
::google::protobuf::int32 ZMQAtomMessage::flags_ private
Definition at line 835 of file ZMQMessages.pb.h.
::google::protobuf::uint64 ZMQAtomMessage::handle_ private
Definition at line 827 of file ZMQMessages.pb.h.
::google::protobuf::RepeatedField< ::google::protobuf::uint64 > ZMQAtomMessage::incoming_ private
Definition at line 830 of file ZMQMessages.pb.h.
const int ZMQAtomMessage::kAtomtypeFieldNumber = 1 static
Definition at line 721 of file ZMQMessages.pb.h.
const int ZMQAtomMessage::kAttentionvalueholderFieldNumber = 2 static
Definition at line 728 of file ZMQMessages.pb.h.
const int ZMQAtomMessage::kFlagsFieldNumber = 6 static
Definition at line 762 of file ZMQMessages.pb.h.
const int ZMQAtomMessage::kHandleFieldNumber = 3 static
Definition at line 736 of file ZMQMessages.pb.h.
const int ZMQAtomMessage::kIncomingFieldNumber = 4 static
Definition at line 743 of file ZMQMessages.pb.h.
const int ZMQAtomMessage::kNameFieldNumber = 8 static
Definition at line 777 of file ZMQMessages.pb.h.
const int ZMQAtomMessage::kOutgoingFieldNumber = 9 static
Definition at line 788 of file ZMQMessages.pb.h.
const int ZMQAtomMessage::kTrailFieldNumber = 10 static
Definition at line 800 of file ZMQMessages.pb.h.
const int ZMQAtomMessage::kTruthValueFieldNumber = 7 static
Definition at line 769 of file ZMQMessages.pb.h.
const int ZMQAtomMessage::kTypeFieldNumber = 5 static
Definition at line 755 of file ZMQMessages.pb.h.
::std::string* ZMQAtomMessage::name_ private
Definition at line 832 of file ZMQMessages.pb.h.
::google::protobuf::RepeatedField< ::google::protobuf::uint64 > ZMQAtomMessage::outgoing_ private
Definition at line 833 of file ZMQMessages.pb.h.
::ZMQTrailMessage* ZMQAtomMessage::trail_ private
Definition at line 834 of file ZMQMessages.pb.h.
::ZMQTruthValueMessage* ZMQAtomMessage::truthvalue_ private
Definition at line 831 of file ZMQMessages.pb.h.
::google::protobuf::int32 ZMQAtomMessage::type_ private
Definition at line 829 of file ZMQMessages.pb.h.
The documentation for this class was generated from the following files:
opencog/persist/zmq/atomspace/ZMQMessages.pb.h
opencog/persist/zmq/atomspace/ZMQMessages.pb.cc