OpenCog Framework: ZMQTruthValueMessage Class Reference
ZMQTruthValueMessage Class Reference
#include <ZMQMessages.pb.h>
Public Member Functions
ZMQTruthValueMessage ()
virtual ~ZMQTruthValueMessage ()
ZMQTruthValueMessage (const ZMQTruthValueMessage &from)
ZMQTruthValueMessage & operator= (const ZMQTruthValueMessage &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (ZMQTruthValueMessage *other)
ZMQTruthValueMessage * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const ZMQTruthValueMessage &from)
void MergeFrom (const ZMQTruthValueMessage &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
int singletruthvalue_size () const
void clear_singletruthvalue ()
const
::ZMQSingleTruthValueMessage & singletruthvalue (int index) const
inline::ZMQSingleTruthValueMessage * mutable_singletruthvalue (int index)
inline::ZMQSingleTruthValueMessage * add_singletruthvalue ()
const
::google::protobuf::RepeatedPtrField
< ::ZMQSingleTruthValueMessage > & singletruthvalue () const
inline::google::protobuf::RepeatedPtrField
< ::ZMQSingleTruthValueMessage > * mutable_singletruthvalue ()
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const ZMQTruthValueMessage & default_instance ()
Static Public Attributes
static const int kSingleTruthValueFieldNumber = 1
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::google::protobuf::RepeatedPtrField
< ::ZMQSingleTruthValueMessage > singletruthvalue_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(1+31)/32]
Static Private Attributes
static ZMQTruthValueMessage * default_instance_ = NULL
Friends
void protobuf_AddDesc_ZMQMessages_2eproto ()
void protobuf_AssignDesc_ZMQMessages_2eproto ()
void protobuf_ShutdownFile_ZMQMessages_2eproto ()
Detailed Description
Definition at line 484 of file ZMQMessages.pb.h.
Constructor & Destructor Documentation
ZMQTruthValueMessage::ZMQTruthValueMessage ()
Definition at line 1528 of file ZMQMessages.pb.cc.
References SharedCtor().
ZMQTruthValueMessage::~ZMQTruthValueMessage () virtual
Definition at line 1547 of file ZMQMessages.pb.cc.
References SharedDtor().
ZMQTruthValueMessage::ZMQTruthValueMessage (const ZMQTruthValueMessage & from)
Definition at line 1536 of file ZMQMessages.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
ZMQSingleTruthValueMessage * ZMQTruthValueMessage::add_singletruthvalue () inline
Definition at line 1431 of file ZMQMessages.pb.h.
References singletruthvalue_.
int ZMQTruthValueMessage::ByteSize () const
Definition at line 1649 of file ZMQMessages.pb.cc.
References _cached_size_, singletruthvalue(), singletruthvalue_size(), and unknown_fields().
void ZMQTruthValueMessage::Clear ()
Definition at line 1576 of file ZMQMessages.pb.cc.
References _has_bits_, mutable_unknown_fields(), and singletruthvalue_.
void ZMQTruthValueMessage::clear_singletruthvalue () inline
Definition at line 1422 of file ZMQMessages.pb.h.
References singletruthvalue_.
void ZMQTruthValueMessage::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 1689 of file ZMQMessages.pb.cc.
References Clear(), and MergeFrom().
void ZMQTruthValueMessage::CopyFrom (const ZMQTruthValueMessage & from)
Definition at line 1695 of file ZMQMessages.pb.cc.
References Clear(), and MergeFrom().
const ZMQTruthValueMessage & ZMQTruthValueMessage::default_instance () static
Definition at line 1566 of file ZMQMessages.pb.cc.
References default_instance_, and protobuf_AddDesc_ZMQMessages_2eproto.
const ::google::protobuf::Descriptor * ZMQTruthValueMessage::descriptor () static
Definition at line 1561 of file ZMQMessages.pb.cc.
int ZMQTruthValueMessage::GetCachedSize () const inline
Definition at line 525 of file ZMQMessages.pb.h.
References _cached_size_.
google::protobuf::Metadata ZMQTruthValueMessage::GetMetadata () const
Definition at line 1718 of file ZMQMessages.pb.cc.
void ZMQTruthValueMessage::InitAsDefaultInstance () private
Definition at line 1533 of file ZMQMessages.pb.cc.
bool ZMQTruthValueMessage::IsInitialized () const
Definition at line 1701 of file ZMQMessages.pb.cc.
References singletruthvalue(), and singletruthvalue_size().
void ZMQTruthValueMessage::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 1671 of file ZMQMessages.pb.cc.
void ZMQTruthValueMessage::MergeFrom (const ZMQTruthValueMessage & from)
Definition at line 1683 of file ZMQMessages.pb.cc.
References mutable_unknown_fields(), singletruthvalue_, and unknown_fields().
bool ZMQTruthValueMessage::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 1582 of file ZMQMessages.pb.cc.
References add_singletruthvalue(), DO_, and mutable_unknown_fields().
ZMQSingleTruthValueMessage * ZMQTruthValueMessage::mutable_singletruthvalue (int index) inline
Definition at line 1428 of file ZMQMessages.pb.h.
References singletruthvalue_.
google::protobuf::RepeatedPtrField<::ZMQSingleTruthValueMessage > * ZMQTruthValueMessage::mutable_singletruthvalue () inline
Definition at line 1439 of file ZMQMessages.pb.h.
References singletruthvalue_.
inline ::google::protobuf::UnknownFieldSet* ZMQTruthValueMessage::mutable_unknown_fields () inline
Definition at line 500 of file ZMQMessages.pb.h.
References _unknown_fields_.
ZMQTruthValueMessage * ZMQTruthValueMessage::New () const
Definition at line 1572 of file ZMQMessages.pb.cc.
References ZMQTruthValueMessage().
ZMQTruthValueMessage& ZMQTruthValueMessage::operator= (const ZMQTruthValueMessage & from) inline
Definition at line 491 of file ZMQMessages.pb.h.
References CopyFrom().
void ZMQTruthValueMessage::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 1619 of file ZMQMessages.pb.cc.
References singletruthvalue(), singletruthvalue_size(), and unknown_fields().
google::protobuf::uint8 * ZMQTruthValueMessage::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 1633 of file ZMQMessages.pb.cc.
References singletruthvalue(), singletruthvalue_size(), and unknown_fields().
void ZMQTruthValueMessage::SetCachedSize (int size) const private
Definition at line 1556 of file ZMQMessages.pb.cc.
References _cached_size_.
void ZMQTruthValueMessage::SharedCtor () private
Definition at line 1542 of file ZMQMessages.pb.cc.
References _cached_size_, and _has_bits_.
void ZMQTruthValueMessage::SharedDtor () private
Definition at line 1551 of file ZMQMessages.pb.cc.
References default_instance_.
const ::ZMQSingleTruthValueMessage & ZMQTruthValueMessage::singletruthvalue (int index) const inline
Definition at line 1425 of file ZMQMessages.pb.h.
References singletruthvalue_.
const ::google::protobuf::RepeatedPtrField<::ZMQSingleTruthValueMessage > & ZMQTruthValueMessage::singletruthvalue () const inline
Definition at line 1435 of file ZMQMessages.pb.h.
References singletruthvalue_.
int ZMQTruthValueMessage::singletruthvalue_size () const inline
Definition at line 1419 of file ZMQMessages.pb.h.
References singletruthvalue_.
void ZMQTruthValueMessage::Swap (ZMQTruthValueMessage * other)
Definition at line 1709 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, and singletruthvalue_.
const ::google::protobuf::UnknownFieldSet& ZMQTruthValueMessage::unknown_fields () const inline
Definition at line 496 of file ZMQMessages.pb.h.
References _unknown_fields_.
Friends And Related Function Documentation
void protobuf_AddDesc_ZMQMessages_2eproto () friend
Definition at line 254 of file ZMQMessages.pb.cc.
void protobuf_AssignDesc_ZMQMessages_2eproto () friend
Definition at line 49 of file ZMQMessages.pb.cc.
void protobuf_ShutdownFile_ZMQMessages_2eproto () friend
Definition at line 235 of file ZMQMessages.pb.cc.
Member Data Documentation
int ZMQTruthValueMessage::_cached_size_ mutable private
Definition at line 557 of file ZMQMessages.pb.h.
::google::protobuf::uint32 ZMQTruthValueMessage::_has_bits_[(1+31)/32] private
Definition at line 558 of file ZMQMessages.pb.h.
::google::protobuf::UnknownFieldSet ZMQTruthValueMessage::_unknown_fields_ private
Definition at line 553 of file ZMQMessages.pb.h.
ZMQTruthValueMessage * ZMQTruthValueMessage::default_instance_ = NULL static private
Definition at line 565 of file ZMQMessages.pb.h.
const int ZMQTruthValueMessage::kSingleTruthValueFieldNumber = 1 static
Definition at line 541 of file ZMQMessages.pb.h.
::google::protobuf::RepeatedPtrField< ::ZMQSingleTruthValueMessage > ZMQTruthValueMessage::singletruthvalue_ private
Definition at line 555 of file ZMQMessages.pb.h.
The documentation for this class was generated from the following files:
opencog/persist/zmq/atomspace/ZMQMessages.pb.h
opencog/persist/zmq/atomspace/ZMQMessages.pb.cc