OpenCog Framework: opencog/atoms/execution/ExecSCM.cc File Reference
ExecSCM.cc File Reference
#include <cstddef>
#include <opencog/atomspace/Link.h>
#include <opencog/atomspace/AtomSpace.h>
#include <opencog/atoms/execution/EvaluationLink.h>
#include <opencog/atoms/execution/Instantiator.h>
#include <opencog/atoms/reduct/FunctionLink.h>
#include <opencog/guile/SchemeModule.h>
#include "ExecSCM.h"
Functions
static Handle ss_execute (AtomSpace *atomspace, const Handle &h)
static TruthValuePtr ss_evaluate (AtomSpace *atomspace, const Handle &h)
static Handle ss_reduce (AtomSpace *atomspace, const Handle &h)
void opencog_exec_init (void)
Function Documentation
void opencog_exec_init (void)
Definition at line 112 of file ExecSCM.cc.
References opencog::ModuleWrap::module_init().
static TruthValuePtr ss_evaluate (AtomSpace * atomspace, const Handle & h) static
cog-evaluate! evaluates an EvaluationLink with a GPN in it.
Definition at line 39 of file ExecSCM.cc.
References opencog::EvaluationLink::do_evaluate().
static Handle ss_execute (AtomSpace * atomspace, const Handle & h) static
cog-execute! executes an ExecutionOutputLink
Definition at line 27 of file ExecSCM.cc.
References opencog::AtomSpace::add_atom(), and opencog::Instantiator::execute().
static Handle ss_reduce (AtomSpace * atomspace, const Handle & h) static
cog-reduce! reduces a FreeLink with free variables in it.
Definition at line 47 of file ExecSCM.cc.
References opencog::AtomSpace::add_atom(), opencog::classserver(), opencog::FunctionLink::factory(), opencog::FreeLinkCast(), opencog::Atom::getType(), opencog::LinkCast(), opencog::AtomSpace::remove_atom(), python.undocumented.blocksworld::t, and opencog::Handle::UNDEFINED.