OpenCog Framework: viz_graph.Graph_Abserver Class Reference
viz_graph.Graph_Abserver Class Reference
Public Member Functions
def __init__
def write
def filter_graph
def graph_info
def valid_edge
Public Attributes
source
valid_edge_types
valid_node_types
graph
inheritance
Private Member Functions
def _nodes_from_edge
def _get_edges
def _edge_type
def _node_type
def _edge_is_a
def _node_is_a
Detailed Description
abstract class that help to abserve the graph according to the given filter imfo
Definition at line 297 of file viz_graph.py.
Constructor & Destructor Documentation
def viz_graph.Graph_Abserver.__init__ (self, source, e_types, n_types, inheritance = True)
Definition at line 299 of file viz_graph.py.
Member Function Documentation
def viz_graph.Graph_Abserver._edge_is_a (self, source, target) private
type of source and target is consistency with valid_edge_types
Definition at line 357 of file viz_graph.py.
def viz_graph.Graph_Abserver._edge_type (self, edge) private
type of edge should be consistency with valid_edge_types
Definition at line 349 of file viz_graph.py.
def viz_graph.Graph_Abserver._get_edges (self, e_type) private
type of e_type should be consistency with valid_edge_types
Definition at line 346 of file viz_graph.py.
def viz_graph.Graph_Abserver._node_is_a (self, source, target) private
type of source and target is consistency with valid_node_types
Definition at line 361 of file viz_graph.py.
def viz_graph.Graph_Abserver._node_type (self, node) private
type of node should be consistency with valid_node_types
Definition at line 353 of file viz_graph.py.
def viz_graph.Graph_Abserver._nodes_from_edge (self, edge) private
Definition at line 343 of file viz_graph.py.
def viz_graph.Graph_Abserver.filter_graph (self)
docstring for run()
Definition at line 311 of file viz_graph.py.
References viz_graph.Graph_Abserver._get_edges(), viz_graph.Graph_Abserver._nodes_from_edge(), viz_graph.Graph_Abserver.valid_edge(), and viz_graph.Graph_Abserver.valid_edge_types.
def viz_graph.Graph_Abserver.graph_info (self)
docstring for graph_info
Definition at line 326 of file viz_graph.py.
def viz_graph.Graph_Abserver.valid_edge (self, edge, nodes)
Definition at line 366 of file viz_graph.py.
References viz_graph.Graph_Abserver._edge_is_a(), viz_graph.Graph_Abserver._edge_type(), viz_graph.Graph_Abserver._node_is_a(), viz_graph.Graph_Abserver._node_type(), viz_graph.Graph_Abserver.valid_edge_types, and viz_graph.Graph_Abserver.valid_node_types.
def viz_graph.Graph_Abserver.write (self, filename)
docstring for write_dot
Definition at line 307 of file viz_graph.py.
Member Data Documentation
viz_graph.Graph_Abserver.graph
Definition at line 303 of file viz_graph.py.
viz_graph.Graph_Abserver.inheritance
Definition at line 304 of file viz_graph.py.
viz_graph.Graph_Abserver.source
Definition at line 300 of file viz_graph.py.
viz_graph.Graph_Abserver.valid_edge_types
Definition at line 301 of file viz_graph.py.
viz_graph.Graph_Abserver.valid_node_types
Definition at line 302 of file viz_graph.py.
The documentation for this class was generated from the following file:
examples/python/untested/viz_graph.py