OpenCog Framework: opencog::FCMemory Class Reference
opencog::FCMemory Class Reference
#include <FCMemory.h>
Public Member Functions
FCMemory (AtomSpace *as)
~FCMemory ()
vector< Rule * > & get_rules ()
void set_rules (const vector< Rule * > &rules)
void set_rules (vector< Rule > &rules)
Rule * get_cur_rule ()
void set_cur_rule (Rule *r)
void set_source (Handle source)
HandleSeq get_selected_sources (void)
bool isin_selected_sources (Handle h)
HandleSeq get_potential_sources (void)
void update_potential_sources (HandleSeq input)
bool isin_potential_sources (Handle h)
Handle get_cur_source (void)
void set_search_in_af (bool val)
bool is_search_in_af ()
void add_rules_product (int iteration, HandleSeq product)
void add_inference (int iteration, HandleSeq product, HandleSeq matched_nodes)
vector< Inference > & get_inf_history ()
HandleSeq get_result ()
vector< Rule * > get_applied_rules (void)
Private Attributes
bool _search_in_af
vector< Rule * > _rules
Rule * _cur_rule
Handle _cur_source
HandleSeq _selected_sources
HandleSeq _potential_sources
vector< Inference > _inf_history
AtomSpace * _as
Detailed Description
Definition at line 38 of file FCMemory.h.
Constructor & Destructor Documentation
FCMemory::FCMemory (AtomSpace * as)
Definition at line 29 of file FCMemory.cc.
References _as.
FCMemory::~FCMemory ()
Definition at line 34 of file FCMemory.cc.
Member Function Documentation
void FCMemory::add_inference (int iteration, HandleSeq product, HandleSeq matched_nodes)
Definition at line 110 of file FCMemory.cc.
References _cur_rule, _inf_history, opencog::Inference::applied_rule, opencog::Inference::inf_product, opencog::Inference::iter_step, and opencog::Inference::matched_nodes.
void FCMemory::add_rules_product (int iteration, HandleSeq product)
Definition at line 99 of file FCMemory.cc.
References _cur_rule, _inf_history, opencog::Inference::applied_rule, opencog::Inference::inf_product, and opencog::Inference::iter_step.
vector< Rule * > FCMemory::get_applied_rules (void)
Definition at line 170 of file FCMemory.cc.
References _inf_history.
Rule * FCMemory::get_cur_rule ()
Definition at line 89 of file FCMemory.cc.
References _cur_rule.
Handle FCMemory::get_cur_source (void)
Definition at line 123 of file FCMemory.cc.
References _cur_source.
vector< Inference > & FCMemory::get_inf_history ()
Definition at line 165 of file FCMemory.cc.
References _inf_history.
HandleSeq FCMemory::get_potential_sources (void)
Definition at line 74 of file FCMemory.cc.
References _potential_sources.
HandleSeq FCMemory::get_result ()
Definition at line 157 of file FCMemory.cc.
References _inf_history, and python.bindlink::result.
vector< Rule * > & FCMemory::get_rules ()
Definition at line 46 of file FCMemory.cc.
References _rules.
HandleSeq FCMemory::get_selected_sources (void)
Definition at line 69 of file FCMemory.cc.
References _selected_sources.
bool FCMemory::is_search_in_af ()
Definition at line 84 of file FCMemory.cc.
References _search_in_af.
bool FCMemory::isin_potential_sources (Handle h)
Definition at line 133 of file FCMemory.cc.
References _as, _potential_sources, opencog::AtomSpace::get_outgoing(), opencog::LinkCast(), and opencog::Handle::value().
bool FCMemory::isin_selected_sources (Handle h)
Definition at line 128 of file FCMemory.cc.
References _selected_sources.
void FCMemory::set_cur_rule (Rule * r)
Definition at line 94 of file FCMemory.cc.
References _cur_rule.
void FCMemory::set_rules (const vector< Rule * > & rules)
Definition at line 51 of file FCMemory.cc.
References _rules.
void FCMemory::set_rules (vector< Rule > & rules)
Definition at line 56 of file FCMemory.cc.
References _rules.
void FCMemory::set_search_in_af (bool val)
Definition at line 79 of file FCMemory.cc.
References _search_in_af.
void FCMemory::set_source (Handle source)
Definition at line 63 of file FCMemory.cc.
References _cur_source, and _selected_sources.
void FCMemory::update_potential_sources (HandleSeq input)
Definition at line 38 of file FCMemory.cc.
References _potential_sources.
Member Data Documentation
AtomSpace* opencog::FCMemory::_as private
Definition at line 49 of file FCMemory.h.
Rule* opencog::FCMemory::_cur_rule private
Definition at line 42 of file FCMemory.h.
Handle opencog::FCMemory::_cur_source private
Definition at line 43 of file FCMemory.h.
vector<Inference> opencog::FCMemory::_inf_history private
Definition at line 47 of file FCMemory.h.
HandleSeq opencog::FCMemory::_potential_sources private
Definition at line 46 of file FCMemory.h.
vector<Rule*> opencog::FCMemory::_rules private
Definition at line 41 of file FCMemory.h.
bool opencog::FCMemory::_search_in_af private
Definition at line 40 of file FCMemory.h.
HandleSeq opencog::FCMemory::_selected_sources private
Definition at line 45 of file FCMemory.h.
The documentation for this class was generated from the following files:
opencog/rule-engine/forwardchainer/FCMemory.h
opencog/rule-engine/forwardchainer/FCMemory.cc