OpenCog Framework: opencog/benchmark/atomspace_bm.cc File Reference
atomspace_bm.cc File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <cstdlib>
#include "AtomSpaceBenchmark.h"
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 12 of file atomspace_bm.cc.
References opencog::AtomSpaceBenchmark::atomCount, opencog::AtomSpaceBenchmark::BENCH_AS, opencog::AtomSpaceBenchmark::BENCH_PYTHON, opencog::AtomSpaceBenchmark::BENCH_SCM, opencog::AtomSpaceBenchmark::BENCH_TABLE, opencog::AtomSpaceBenchmark::buildTestData, opencog::AtomSpaceBenchmark::chanceUseDefaultTV, opencog::AtomSpaceBenchmark::compile, opencog::AtomSpaceBenchmark::doStats, opencog::AtomSpaceBenchmark::memoize, opencog::AtomSpaceBenchmark::Nloops, opencog::AtomSpaceBenchmark::Nreps, opencog::AtomSpaceBenchmark::percentLinks, opencog::AtomSpaceBenchmark::randomseed, opencog::AtomSpaceBenchmark::saveInterval, opencog::AtomSpaceBenchmark::saveToFile, opencog::AtomSpaceBenchmark::setMethod(), opencog::AtomSpaceBenchmark::setTestAllMethods(), opencog::AtomSpaceBenchmark::showMethods(), opencog::AtomSpaceBenchmark::showTypeSizes, opencog::AtomSpaceBenchmark::sizeIncrease, opencog::AtomSpaceBenchmark::startBenchmark(), and opencog::AtomSpaceBenchmark::testKind.