OpenCog Framework: opencog::SQLPersistSCM Class Reference
opencog::SQLPersistSCM Class Reference
Communications and Persistence
#include <SQLPersistSCM.h>
Public Member Functions
SQLPersistSCM (AtomSpace *)
~SQLPersistSCM ()
void do_open (const std::string &, const std::string &, const std::string &)
void do_close (void)
void do_load (void)
void do_store (void)
Private Member Functions
void init (void)
Static Private Member Functions
static void * init_in_guile (void *)
static void init_in_module (void *)
Private Attributes
SQLBackingStore * _backing
AtomStorage * _store
AtomSpace * _as
Detailed Description
Definition at line 41 of file SQLPersistSCM.h.
Constructor & Destructor Documentation
SQLPersistSCM::SQLPersistSCM (AtomSpace * as)
Definition at line 99 of file SQLPersistSCM.cc.
References _as, _backing, opencog::BackingStore::_ignored_types, _store, and init_in_guile().
SQLPersistSCM::~SQLPersistSCM ()
Definition at line 164 of file SQLPersistSCM.cc.
References _backing.
Member Function Documentation
void SQLPersistSCM::do_close (void)
Definition at line 197 of file SQLPersistSCM.cc.
References _as, _backing, _store, opencog::SQLBackingStore::set_store(), opencog::SchemeSmob::ss_get_env_as(), and opencog::AtomSpace::unregisterBackingStore().
void SQLPersistSCM::do_load (void)
Definition at line 215 of file SQLPersistSCM.cc.
References _as, _store, opencog::AtomSpace::get_atomtable(), opencog::AtomStorage::load(), and opencog::SchemeSmob::ss_get_env_as().
void SQLPersistSCM::do_open (const std::string & dbname, const std::string & username, const std::string & auth)
Definition at line 169 of file SQLPersistSCM.cc.
References _as, _backing, _store, opencog::AtomStorage::connected(), opencog::AtomSpace::registerBackingStore(), opencog::AtomStorage::reserve(), opencog::SQLBackingStore::set_store(), and opencog::SchemeSmob::ss_get_env_as().
void SQLPersistSCM::do_store (void)
Definition at line 231 of file SQLPersistSCM.cc.
References _as, _store, opencog::AtomSpace::get_atomtable(), opencog::SchemeSmob::ss_get_env_as(), and opencog::AtomStorage::store().
void SQLPersistSCM::init (void) private
Definition at line 154 of file SQLPersistSCM.cc.
References do_close(), do_load(), do_open(), and do_store().
void * SQLPersistSCM::init_in_guile (void * self) static private
Definition at line 139 of file SQLPersistSCM.cc.
References init_in_module().
void SQLPersistSCM::init_in_module (void * data) static private
Definition at line 148 of file SQLPersistSCM.cc.
References init().
Member Data Documentation
AtomSpace* opencog::SQLPersistSCM::_as private
Definition at line 50 of file SQLPersistSCM.h.
SQLBackingStore* opencog::SQLPersistSCM::_backing private
Definition at line 48 of file SQLPersistSCM.h.
AtomStorage* opencog::SQLPersistSCM::_store private
Definition at line 49 of file SQLPersistSCM.h.
The documentation for this class was generated from the following files:
opencog/persist/sql/SQLPersistSCM.h
opencog/persist/sql/SQLPersistSCM.cc