OpenCog Framework: opencog/persist/zmq/atomspace/ZMQMessages.pb.cc File Reference
ZMQMessages.pb.cc File Reference
#include "ZMQMessages.pb.h"
#include <algorithm>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
Classes
struct StaticDescriptorInitializer_ZMQMessages_2eproto
Macros
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
Functions
void protobuf_AssignDesc_ZMQMessages_2eproto ()
void protobuf_ShutdownFile_ZMQMessages_2eproto ()
void protobuf_AddDesc_ZMQMessages_2eproto ()
const
::google::protobuf::EnumDescriptor * ZMQTruthValueType_descriptor ()
bool ZMQTruthValueType_IsValid (int value)
const
::google::protobuf::EnumDescriptor * ZMQAtomType_descriptor ()
bool ZMQAtomType_IsValid (int value)
const
::google::protobuf::EnumDescriptor * ZMQFunctionType_descriptor ()
bool ZMQFunctionType_IsValid (int value)
Variables
struct
StaticDescriptorInitializer_ZMQMessages_2eproto static_descriptor_initializer_ZMQMessages_2eproto_
Macro Definition Documentation
#define DO_ (EXPRESSION) if (!(EXPRESSION)) return false
#define DO_ (EXPRESSION) if (!(EXPRESSION)) return false
#define DO_ (EXPRESSION) if (!(EXPRESSION)) return false
#define DO_ (EXPRESSION) if (!(EXPRESSION)) return false
#define DO_ (EXPRESSION) if (!(EXPRESSION)) return false
#define DO_ (EXPRESSION) if (!(EXPRESSION)) return false
#define DO_ (EXPRESSION) if (!(EXPRESSION)) return false
#define DO_ (EXPRESSION) if (!(EXPRESSION)) return false
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
Definition at line 3 of file ZMQMessages.pb.cc.
Function Documentation
void protobuf_AddDesc_ZMQMessages_2eproto ()
Definition at line 254 of file ZMQMessages.pb.cc.
References ZMQAttentionValueHolderMessage::default_instance_, ZMQVersionHandleMessage::default_instance_, ZMQSingleTruthValueMessage::default_instance_, ZMQTruthValueMessage::default_instance_, ZMQTrailMessage::default_instance_, ZMQAtomMessage::default_instance_, ZMQRequestMessage::default_instance_, ZMQReplyMessage::default_instance_, ZMQAttentionValueHolderMessage::InitAsDefaultInstance(), ZMQVersionHandleMessage::InitAsDefaultInstance(), ZMQSingleTruthValueMessage::InitAsDefaultInstance(), ZMQTruthValueMessage::InitAsDefaultInstance(), ZMQTrailMessage::InitAsDefaultInstance(), ZMQAtomMessage::InitAsDefaultInstance(), ZMQRequestMessage::InitAsDefaultInstance(), ZMQReplyMessage::InitAsDefaultInstance(), and protobuf_ShutdownFile_ZMQMessages_2eproto().
void protobuf_AssignDesc_ZMQMessages_2eproto ()
Definition at line 49 of file ZMQMessages.pb.cc.
References ZMQAttentionValueHolderMessage::default_instance_, ZMQVersionHandleMessage::default_instance_, ZMQSingleTruthValueMessage::default_instance_, ZMQTruthValueMessage::default_instance_, ZMQTrailMessage::default_instance_, ZMQAtomMessage::default_instance_, ZMQRequestMessage::default_instance_, ZMQReplyMessage::default_instance_, and protobuf_AddDesc_ZMQMessages_2eproto().
void protobuf_ShutdownFile_ZMQMessages_2eproto ()
Definition at line 235 of file ZMQMessages.pb.cc.
References ZMQAttentionValueHolderMessage::default_instance_, ZMQVersionHandleMessage::default_instance_, ZMQSingleTruthValueMessage::default_instance_, ZMQTruthValueMessage::default_instance_, ZMQTrailMessage::default_instance_, ZMQAtomMessage::default_instance_, ZMQRequestMessage::default_instance_, and ZMQReplyMessage::default_instance_.
const ::google::protobuf::EnumDescriptor* ZMQAtomType_descriptor ()
Definition at line 338 of file ZMQMessages.pb.cc.
bool ZMQAtomType_IsValid (int value)
Definition at line 342 of file ZMQMessages.pb.cc.
const ::google::protobuf::EnumDescriptor* ZMQFunctionType_descriptor ()
Definition at line 352 of file ZMQMessages.pb.cc.
bool ZMQFunctionType_IsValid (int value)
Definition at line 356 of file ZMQMessages.pb.cc.
const ::google::protobuf::EnumDescriptor* ZMQTruthValueType_descriptor ()
Definition at line 321 of file ZMQMessages.pb.cc.
bool ZMQTruthValueType_IsValid (int value)
Definition at line 325 of file ZMQMessages.pb.cc.
Variable Documentation
struct StaticDescriptorInitializer_ZMQMessages_2eproto static_descriptor_initializer_ZMQMessages_2eproto_