OpenCog Framework: ZMQTrailMessage Class Reference
ZMQTrailMessage Class Reference
#include <ZMQMessages.pb.h>
Public Member Functions
ZMQTrailMessage ()
virtual ~ZMQTrailMessage ()
ZMQTrailMessage (const ZMQTrailMessage &from)
ZMQTrailMessage & operator= (const ZMQTrailMessage &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (ZMQTrailMessage *other)
ZMQTrailMessage * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const ZMQTrailMessage &from)
void MergeFrom (const ZMQTrailMessage &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_maxsize () const
void clear_maxsize ()
inline::google::protobuf::int32 maxsize () const
void set_maxsize (::google::protobuf::int32 value)
int trail_size () const
void clear_trail ()
inline::google::protobuf::uint64 trail (int index) const
void set_trail (int index,::google::protobuf::uint64 value)
void add_trail (::google::protobuf::uint64 value)
const
::google::protobuf::RepeatedField
< ::google::protobuf::uint64 > & trail () const
inline::google::protobuf::RepeatedField
< ::google::protobuf::uint64 > * mutable_trail ()
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const ZMQTrailMessage & default_instance ()
Static Public Attributes
static const int kMaxSizeFieldNumber = 1
static const int kTrailFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_maxsize ()
void clear_has_maxsize ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::google::protobuf::RepeatedField
< ::google::protobuf::uint64 > trail_
::google::protobuf::int32 maxsize_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(2+31)/32]
Static Private Attributes
static ZMQTrailMessage * default_instance_ = NULL
Friends
void protobuf_AddDesc_ZMQMessages_2eproto ()
void protobuf_AssignDesc_ZMQMessages_2eproto ()
void protobuf_ShutdownFile_ZMQMessages_2eproto ()
Detailed Description
Definition at line 569 of file ZMQMessages.pb.h.
Constructor & Destructor Documentation
ZMQTrailMessage::ZMQTrailMessage ()
Definition at line 1734 of file ZMQMessages.pb.cc.
References SharedCtor().
ZMQTrailMessage::~ZMQTrailMessage () virtual
Definition at line 1754 of file ZMQMessages.pb.cc.
References SharedDtor().
ZMQTrailMessage::ZMQTrailMessage (const ZMQTrailMessage & from)
Definition at line 1742 of file ZMQMessages.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
void ZMQTrailMessage::add_trail (::google::protobuf::uint64 value) inline
Definition at line 1482 of file ZMQMessages.pb.h.
References trail_.
int ZMQTrailMessage::ByteSize () const
Definition at line 1890 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, has_maxsize(), maxsize(), trail(), trail_size(), and unknown_fields().
void ZMQTrailMessage::Clear ()
Definition at line 1783 of file ZMQMessages.pb.cc.
References _has_bits_, maxsize_, mutable_unknown_fields(), and trail_.
void ZMQTrailMessage::clear_has_maxsize () inline private
Definition at line 1454 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQTrailMessage::clear_maxsize () inline
Definition at line 1457 of file ZMQMessages.pb.h.
References clear_has_maxsize(), and maxsize_.
void ZMQTrailMessage::clear_trail () inline
Definition at line 1473 of file ZMQMessages.pb.h.
References trail_.
void ZMQTrailMessage::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 1946 of file ZMQMessages.pb.cc.
References Clear(), and MergeFrom().
void ZMQTrailMessage::CopyFrom (const ZMQTrailMessage & from)
Definition at line 1952 of file ZMQMessages.pb.cc.
References Clear(), and MergeFrom().
const ZMQTrailMessage & ZMQTrailMessage::default_instance () static
Definition at line 1773 of file ZMQMessages.pb.cc.
References default_instance_, and protobuf_AddDesc_ZMQMessages_2eproto.
const ::google::protobuf::Descriptor * ZMQTrailMessage::descriptor () static
Definition at line 1768 of file ZMQMessages.pb.cc.
int ZMQTrailMessage::GetCachedSize () const inline
Definition at line 610 of file ZMQMessages.pb.h.
References _cached_size_.
google::protobuf::Metadata ZMQTrailMessage::GetMetadata () const
Definition at line 1974 of file ZMQMessages.pb.cc.
bool ZMQTrailMessage::has_maxsize () const inline
Definition at line 1448 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQTrailMessage::InitAsDefaultInstance () private
Definition at line 1739 of file ZMQMessages.pb.cc.
bool ZMQTrailMessage::IsInitialized () const
Definition at line 1958 of file ZMQMessages.pb.cc.
References _has_bits_.
google::protobuf::int32 ZMQTrailMessage::maxsize () const inline
Definition at line 1461 of file ZMQMessages.pb.h.
References maxsize_.
void ZMQTrailMessage::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 1923 of file ZMQMessages.pb.cc.
void ZMQTrailMessage::MergeFrom (const ZMQTrailMessage & from)
Definition at line 1935 of file ZMQMessages.pb.cc.
References _has_bits_, has_maxsize(), maxsize(), mutable_unknown_fields(), set_maxsize(), trail_, and unknown_fields().
bool ZMQTrailMessage::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 1792 of file ZMQMessages.pb.cc.
References DO_, maxsize_, mutable_trail(), mutable_unknown_fields(), and set_has_maxsize().
google::protobuf::RepeatedField<::google::protobuf::uint64 > * ZMQTrailMessage::mutable_trail () inline
Definition at line 1490 of file ZMQMessages.pb.h.
References trail_.
inline ::google::protobuf::UnknownFieldSet* ZMQTrailMessage::mutable_unknown_fields () inline
Definition at line 585 of file ZMQMessages.pb.h.
References _unknown_fields_.
ZMQTrailMessage * ZMQTrailMessage::New () const
Definition at line 1779 of file ZMQMessages.pb.cc.
References ZMQTrailMessage().
ZMQTrailMessage& ZMQTrailMessage::operator= (const ZMQTrailMessage & from) inline
Definition at line 576 of file ZMQMessages.pb.h.
References CopyFrom().
void ZMQTrailMessage::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 1851 of file ZMQMessages.pb.cc.
References has_maxsize(), maxsize(), trail(), trail_size(), and unknown_fields().
google::protobuf::uint8 * ZMQTrailMessage::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 1870 of file ZMQMessages.pb.cc.
References has_maxsize(), maxsize(), trail(), trail_size(), and unknown_fields().
void ZMQTrailMessage::set_has_maxsize () inline private
Definition at line 1451 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQTrailMessage::set_maxsize (::google::protobuf::int32 value) inline
Definition at line 1464 of file ZMQMessages.pb.h.
References maxsize_, and set_has_maxsize().
void ZMQTrailMessage::set_trail (int index, ::google::protobuf::uint64 value) inline
Definition at line 1479 of file ZMQMessages.pb.h.
References trail_.
void ZMQTrailMessage::SetCachedSize (int size) const private
Definition at line 1763 of file ZMQMessages.pb.cc.
References _cached_size_.
void ZMQTrailMessage::SharedCtor () private
Definition at line 1748 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, and maxsize_.
void ZMQTrailMessage::SharedDtor () private
Definition at line 1758 of file ZMQMessages.pb.cc.
References default_instance_.
void ZMQTrailMessage::Swap (ZMQTrailMessage * other)
Definition at line 1964 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, maxsize_, and trail_.
google::protobuf::uint64 ZMQTrailMessage::trail (int index) const inline
Definition at line 1476 of file ZMQMessages.pb.h.
References trail_.
const ::google::protobuf::RepeatedField<::google::protobuf::uint64 > & ZMQTrailMessage::trail () const inline
Definition at line 1486 of file ZMQMessages.pb.h.
References trail_.
int ZMQTrailMessage::trail_size () const inline
Definition at line 1470 of file ZMQMessages.pb.h.
References trail_.
const ::google::protobuf::UnknownFieldSet& ZMQTrailMessage::unknown_fields () const inline
Definition at line 581 of file ZMQMessages.pb.h.
References _unknown_fields_.
Friends And Related Function Documentation
void protobuf_AddDesc_ZMQMessages_2eproto () friend
Definition at line 254 of file ZMQMessages.pb.cc.
void protobuf_AssignDesc_ZMQMessages_2eproto () friend
Definition at line 49 of file ZMQMessages.pb.cc.
void protobuf_ShutdownFile_ZMQMessages_2eproto () friend
Definition at line 235 of file ZMQMessages.pb.cc.
Member Data Documentation
int ZMQTrailMessage::_cached_size_ mutable private
Definition at line 652 of file ZMQMessages.pb.h.
::google::protobuf::uint32 ZMQTrailMessage::_has_bits_[(2+31)/32] private
Definition at line 653 of file ZMQMessages.pb.h.
::google::protobuf::UnknownFieldSet ZMQTrailMessage::_unknown_fields_ private
Definition at line 647 of file ZMQMessages.pb.h.
ZMQTrailMessage * ZMQTrailMessage::default_instance_ = NULL static private
Definition at line 660 of file ZMQMessages.pb.h.
const int ZMQTrailMessage::kMaxSizeFieldNumber = 1 static
Definition at line 626 of file ZMQMessages.pb.h.
const int ZMQTrailMessage::kTrailFieldNumber = 2 static
Definition at line 633 of file ZMQMessages.pb.h.
::google::protobuf::int32 ZMQTrailMessage::maxsize_ private
Definition at line 650 of file ZMQMessages.pb.h.
::google::protobuf::RepeatedField< ::google::protobuf::uint64 > ZMQTrailMessage::trail_ private
Definition at line 649 of file ZMQMessages.pb.h.
The documentation for this class was generated from the following files:
opencog/persist/zmq/atomspace/ZMQMessages.pb.h
opencog/persist/zmq/atomspace/ZMQMessages.pb.cc