OpenCog Framework: examples/c++-guile/PrimitiveExample.cc File Reference
PrimitiveExample.cc File Reference
#include <opencog/atomspace/AtomSpace.h>
#include <opencog/guile/SchemeEval.h>
#include <opencog/guile/SchemePrimitive.h>
Classes
class MyTestClass
Functions
int main ()
Function Documentation
int main ()
Definition at line 55 of file PrimitiveExample.cc.
References opencog::SchemeEval::eval(), opencog::GenericEval::eval_error(), MyTestClass::my_func(), and MyTestClass::my_other_func().