OpenCog Framework: examples/c++-guile/ExampleSCM.cc File Reference
ExampleSCM.cc File Reference
#include <cstddef>
#include <opencog/atomspace/AtomSpace.h>
#include <opencog/guile/SchemeModule.h>
#include "ExampleSCM.h"
Functions
static Handle ss_print (AtomSpace *atomspace, const Handle &h)
static TruthValuePtr ss_printmore (AtomSpace *atomspace, const Handle &h)
void opencog_example_init (void)
Function Documentation
void opencog_example_init (void)
Definition at line 78 of file ExampleSCM.cc.
References opencog::ModuleWrap::module_init().
static Handle ss_print (AtomSpace * atomspace, const Handle & h) static
Definition at line 31 of file ExampleSCM.cc.
References opencog::Atom::toShortString().
static TruthValuePtr ss_printmore (AtomSpace * atomspace, const Handle & h) static
Definition at line 38 of file ExampleSCM.cc.
References opencog::Atom::getTruthValue(), and opencog::Atom::toString().