OpenCog Framework: std Namespace Reference
std Namespace Reference
atomspace library
Classes
struct hash< opencog::Handle >
struct less< PatternTermPtr >
Functions
ostream & operator<< (ostream &out, const opencog::AtomSpace &as)
std::ostream & operator<< (std::ostream &out, const opencog::Handle &h)
template<typename Out >
Out & operator<< (Out &out, const opencog::TruthValue &tv)
Function Documentation
template<typename Out > Out& std::operator<< (Out & out, const opencog::TruthValue & tv)
Definition at line 186 of file TruthValue.h.
References opencog::TruthValue::toString().
std::ostream& std::operator<< (std::ostream & out, const opencog::Handle & h) inline
Definition at line 288 of file Handle.h.
References opencog::Handle::value().
ostream & std::operator<< (ostream & , const opencog::AtomSpace &)
Output the whole atomspace, actually all orphans as the others are output by of their parents (incoming sets).
Definition at line 382 of file AtomSpace.cc.
References opencog::AtomSpace::get_handles_by_type().