OpenCog Framework: opencog/persist/zmq/atomspace/ZMQMessages.pb.h File Reference
ZMQMessages.pb.h File Reference
#include <string>
#include <google/protobuf/stubs/common.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
Classes
class ZMQAttentionValueHolderMessage
class ZMQVersionHandleMessage
class ZMQSingleTruthValueMessage
class ZMQTruthValueMessage
class ZMQTrailMessage
class ZMQAtomMessage
class ZMQRequestMessage
class ZMQReplyMessage
Namespaces
google
google::protobuf
Enumerations
enum ZMQTruthValueType {
ZMQTruthValueTypeSimple = 0, ZMQTruthValueTypeCount = 1, ZMQTruthValueTypeNull = 2, ZMQTruthValueTypeIndefinite = 3,
ZMQTruthValueTypeComposite = 4
}
enum ZMQAtomType { ZMQAtomTypeNode = 0, ZMQAtomTypeLink = 1 }
enum ZMQFunctionType { ZMQgetAtom = 0, ZMQgetName = 1 }
Functions
void protobuf_AddDesc_ZMQMessages_2eproto ()
void protobuf_AssignDesc_ZMQMessages_2eproto ()
void protobuf_ShutdownFile_ZMQMessages_2eproto ()
bool ZMQTruthValueType_IsValid (int value)
const
::google::protobuf::EnumDescriptor * ZMQTruthValueType_descriptor ()
const ::std::string & ZMQTruthValueType_Name (ZMQTruthValueType value)
bool ZMQTruthValueType_Parse (const ::std::string &name, ZMQTruthValueType *value)
bool ZMQAtomType_IsValid (int value)
const
::google::protobuf::EnumDescriptor * ZMQAtomType_descriptor ()
const ::std::string & ZMQAtomType_Name (ZMQAtomType value)
bool ZMQAtomType_Parse (const ::std::string &name, ZMQAtomType *value)
bool ZMQFunctionType_IsValid (int value)
const
::google::protobuf::EnumDescriptor * ZMQFunctionType_descriptor ()
const ::std::string & ZMQFunctionType_Name (ZMQFunctionType value)
bool ZMQFunctionType_Parse (const ::std::string &name, ZMQFunctionType *value)
template<>
const EnumDescriptor * google::protobuf::GetEnumDescriptor< ZMQTruthValueType > ()
template<>
const EnumDescriptor * google::protobuf::GetEnumDescriptor< ZMQAtomType > ()
template<>
const EnumDescriptor * google::protobuf::GetEnumDescriptor< ZMQFunctionType > ()
Variables
const ZMQTruthValueType ZMQTruthValueType_MIN = ZMQTruthValueTypeSimple
const ZMQTruthValueType ZMQTruthValueType_MAX = ZMQTruthValueTypeComposite
const int ZMQTruthValueType_ARRAYSIZE = ZMQTruthValueType_MAX + 1
const ZMQAtomType ZMQAtomType_MIN = ZMQAtomTypeNode
const ZMQAtomType ZMQAtomType_MAX = ZMQAtomTypeLink
const int ZMQAtomType_ARRAYSIZE = ZMQAtomType_MAX + 1
const ZMQFunctionType ZMQFunctionType_MIN = ZMQgetAtom
const ZMQFunctionType ZMQFunctionType_MAX = ZMQgetName
const int ZMQFunctionType_ARRAYSIZE = ZMQFunctionType_MAX + 1
Enumeration Type Documentation
enum ZMQAtomType
Enumerator
ZMQAtomTypeNode
ZMQAtomTypeLink
Definition at line 64 of file ZMQMessages.pb.h.
enum ZMQFunctionType
Enumerator
ZMQgetAtom
ZMQgetName
Definition at line 83 of file ZMQMessages.pb.h.
enum ZMQTruthValueType
Enumerator
ZMQTruthValueTypeSimple
ZMQTruthValueTypeCount
ZMQTruthValueTypeNull
ZMQTruthValueTypeIndefinite
ZMQTruthValueTypeComposite
Definition at line 42 of file ZMQMessages.pb.h.
Function Documentation
void protobuf_AddDesc_ZMQMessages_2eproto ()
Definition at line 254 of file ZMQMessages.pb.cc.
References ZMQAttentionValueHolderMessage::default_instance_, ZMQVersionHandleMessage::default_instance_, ZMQSingleTruthValueMessage::default_instance_, ZMQTruthValueMessage::default_instance_, ZMQTrailMessage::default_instance_, ZMQAtomMessage::default_instance_, ZMQRequestMessage::default_instance_, ZMQReplyMessage::default_instance_, ZMQAttentionValueHolderMessage::InitAsDefaultInstance(), ZMQVersionHandleMessage::InitAsDefaultInstance(), ZMQSingleTruthValueMessage::InitAsDefaultInstance(), ZMQTruthValueMessage::InitAsDefaultInstance(), ZMQTrailMessage::InitAsDefaultInstance(), ZMQAtomMessage::InitAsDefaultInstance(), ZMQRequestMessage::InitAsDefaultInstance(), ZMQReplyMessage::InitAsDefaultInstance(), and protobuf_ShutdownFile_ZMQMessages_2eproto().
void protobuf_AssignDesc_ZMQMessages_2eproto ()
Definition at line 49 of file ZMQMessages.pb.cc.
References ZMQAttentionValueHolderMessage::default_instance_, ZMQVersionHandleMessage::default_instance_, ZMQSingleTruthValueMessage::default_instance_, ZMQTruthValueMessage::default_instance_, ZMQTrailMessage::default_instance_, ZMQAtomMessage::default_instance_, ZMQRequestMessage::default_instance_, ZMQReplyMessage::default_instance_, and protobuf_AddDesc_ZMQMessages_2eproto().
void protobuf_ShutdownFile_ZMQMessages_2eproto ()
Definition at line 235 of file ZMQMessages.pb.cc.
References ZMQAttentionValueHolderMessage::default_instance_, ZMQVersionHandleMessage::default_instance_, ZMQSingleTruthValueMessage::default_instance_, ZMQTruthValueMessage::default_instance_, ZMQTrailMessage::default_instance_, ZMQAtomMessage::default_instance_, ZMQRequestMessage::default_instance_, and ZMQReplyMessage::default_instance_.
const ::google::protobuf::EnumDescriptor* ZMQAtomType_descriptor ()
Definition at line 338 of file ZMQMessages.pb.cc.
bool ZMQAtomType_IsValid (int value)
Definition at line 342 of file ZMQMessages.pb.cc.
const ::std::string& ZMQAtomType_Name (ZMQAtomType value) inline
Definition at line 74 of file ZMQMessages.pb.h.
References ZMQAtomType_descriptor().
bool ZMQAtomType_Parse (const ::std::string & name, ZMQAtomType * value) inline
Definition at line 78 of file ZMQMessages.pb.h.
References ZMQAtomType_descriptor().
const ::google::protobuf::EnumDescriptor* ZMQFunctionType_descriptor ()
Definition at line 352 of file ZMQMessages.pb.cc.
bool ZMQFunctionType_IsValid (int value)
Definition at line 356 of file ZMQMessages.pb.cc.
const ::std::string& ZMQFunctionType_Name (ZMQFunctionType value) inline
Definition at line 93 of file ZMQMessages.pb.h.
References ZMQFunctionType_descriptor().
bool ZMQFunctionType_Parse (const ::std::string & name, ZMQFunctionType * value) inline
Definition at line 97 of file ZMQMessages.pb.h.
References ZMQFunctionType_descriptor().
const ::google::protobuf::EnumDescriptor* ZMQTruthValueType_descriptor ()
Definition at line 321 of file ZMQMessages.pb.cc.
bool ZMQTruthValueType_IsValid (int value)
Definition at line 325 of file ZMQMessages.pb.cc.
const ::std::string& ZMQTruthValueType_Name (ZMQTruthValueType value) inline
Definition at line 55 of file ZMQMessages.pb.h.
References ZMQTruthValueType_descriptor().
bool ZMQTruthValueType_Parse (const ::std::string & name, ZMQTruthValueType * value) inline
Definition at line 59 of file ZMQMessages.pb.h.
References ZMQTruthValueType_descriptor().
Variable Documentation
const int ZMQAtomType_ARRAYSIZE = ZMQAtomType_MAX + 1
Definition at line 71 of file ZMQMessages.pb.h.
const ZMQAtomType ZMQAtomType_MAX = ZMQAtomTypeLink
Definition at line 70 of file ZMQMessages.pb.h.
const ZMQAtomType ZMQAtomType_MIN = ZMQAtomTypeNode
Definition at line 69 of file ZMQMessages.pb.h.
const int ZMQFunctionType_ARRAYSIZE = ZMQFunctionType_MAX + 1
Definition at line 90 of file ZMQMessages.pb.h.
const ZMQFunctionType ZMQFunctionType_MAX = ZMQgetName
Definition at line 89 of file ZMQMessages.pb.h.
const ZMQFunctionType ZMQFunctionType_MIN = ZMQgetAtom
Definition at line 88 of file ZMQMessages.pb.h.
const int ZMQTruthValueType_ARRAYSIZE = ZMQTruthValueType_MAX + 1
Definition at line 52 of file ZMQMessages.pb.h.
const ZMQTruthValueType ZMQTruthValueType_MAX = ZMQTruthValueTypeComposite
Definition at line 51 of file ZMQMessages.pb.h.
const ZMQTruthValueType ZMQTruthValueType_MIN = ZMQTruthValueTypeSimple
Definition at line 50 of file ZMQMessages.pb.h.