OpenCog Framework: sokoban Namespace Reference
sokoban Namespace Reference
Classes
class Block
class Level
Functions
def add_socoban_level_to_atomspace_from_file
def add_socoban_level_to_atomspace_from_url
def _add_globals_to_atomspace
def generate_levels_from_file
def generate_levels_from_url
def _generate_levels
Variables
string __author__ = 'keyvan-m-sadeghi'
tuple atomspace = AtomSpace()
Detailed Description
Created on 5 Jun, 2012
@author: keyvan
Usage Instructions
The following methods can be used for generating Sokoban atoms from a file/url:
- add_socoban_level_to_atomspace_from_file
- add_socoban_level_to_atomspace_from_url
Use levels from http://www.sourcecode.se/sokoban/levels.php
Function Documentation
def sokoban._add_globals_to_atomspace (atomspace) private
Definition at line 35 of file sokoban.py.
def sokoban._generate_levels (open_xml_stream) private
Definition at line 52 of file sokoban.py.
def sokoban.add_socoban_level_to_atomspace_from_file (atomspace, file_path, level_index)
Definition at line 21 of file sokoban.py.
References _add_globals_to_atomspace(), and generate_levels_from_file().
def sokoban.add_socoban_level_to_atomspace_from_url (atomspace, url, level_index)
Url should point to 'http://www.sourcecode.se/sokoban/' database
e.g. 'httpd://www.sourcecode.se/sokoban/dnldlevel.php?LevelFile=100Boxes.slc'
Definition at line 26 of file sokoban.py.
References _add_globals_to_atomspace(), and generate_levels_from_url().
def sokoban.generate_levels_from_file (xml_file_path)
Definition at line 45 of file sokoban.py.
References _generate_levels().
def sokoban.generate_levels_from_url (url)
Definition at line 48 of file sokoban.py.
References _generate_levels().
Variable Documentation
string sokoban.__author__ = 'keyvan-m-sadeghi'
Definition at line 15 of file sokoban.py.
tuple sokoban.atomspace = AtomSpace()
Definition at line 171 of file sokoban.py.