OpenCog Framework: ZMQVersionHandleMessage Class Reference
ZMQVersionHandleMessage Class Reference
#include <ZMQMessages.pb.h>
Public Member Functions
ZMQVersionHandleMessage ()
virtual ~ZMQVersionHandleMessage ()
ZMQVersionHandleMessage (const ZMQVersionHandleMessage &from)
ZMQVersionHandleMessage & operator= (const ZMQVersionHandleMessage &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (ZMQVersionHandleMessage *other)
ZMQVersionHandleMessage * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const ZMQVersionHandleMessage &from)
void MergeFrom (const ZMQVersionHandleMessage &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_indicator () const
void clear_indicator ()
inline::google::protobuf::uint32 indicator () const
void set_indicator (::google::protobuf::uint32 value)
bool has_substantive () const
void clear_substantive ()
inline::google::protobuf::uint64 substantive () const
void set_substantive (::google::protobuf::uint64 value)
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const
ZMQVersionHandleMessage & default_instance ()
Static Public Attributes
static const int kIndicatorFieldNumber = 1
static const int kSubstantiveFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_indicator ()
void clear_has_indicator ()
void set_has_substantive ()
void clear_has_substantive ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::google::protobuf::uint64 substantive_
::google::protobuf::uint32 indicator_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(2+31)/32]
Static Private Attributes
static ZMQVersionHandleMessage * default_instance_ = NULL
Friends
void protobuf_AddDesc_ZMQMessages_2eproto ()
void protobuf_AssignDesc_ZMQMessages_2eproto ()
void protobuf_ShutdownFile_ZMQMessages_2eproto ()
Detailed Description
Definition at line 206 of file ZMQMessages.pb.h.
Constructor & Destructor Documentation
ZMQVersionHandleMessage::ZMQVersionHandleMessage ()
Definition at line 662 of file ZMQMessages.pb.cc.
References SharedCtor().
ZMQVersionHandleMessage::~ZMQVersionHandleMessage () virtual
Definition at line 683 of file ZMQMessages.pb.cc.
References SharedDtor().
ZMQVersionHandleMessage::ZMQVersionHandleMessage (const ZMQVersionHandleMessage & from)
Definition at line 670 of file ZMQMessages.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
int ZMQVersionHandleMessage::ByteSize () const
Definition at line 811 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, has_indicator(), has_substantive(), indicator(), substantive(), and unknown_fields().
void ZMQVersionHandleMessage::Clear ()
Definition at line 712 of file ZMQMessages.pb.cc.
References _has_bits_, indicator_, mutable_unknown_fields(), and substantive_.
void ZMQVersionHandleMessage::clear_has_indicator () inline private
Definition at line 1120 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQVersionHandleMessage::clear_has_substantive () inline private
Definition at line 1142 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQVersionHandleMessage::clear_indicator () inline
Definition at line 1123 of file ZMQMessages.pb.h.
References clear_has_indicator(), and indicator_.
void ZMQVersionHandleMessage::clear_substantive () inline
Definition at line 1145 of file ZMQMessages.pb.h.
References clear_has_substantive(), and substantive_.
void ZMQVersionHandleMessage::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 866 of file ZMQMessages.pb.cc.
References Clear(), and MergeFrom().
void ZMQVersionHandleMessage::CopyFrom (const ZMQVersionHandleMessage & from)
Definition at line 872 of file ZMQMessages.pb.cc.
References Clear(), and MergeFrom().
const ZMQVersionHandleMessage & ZMQVersionHandleMessage::default_instance () static
Definition at line 702 of file ZMQMessages.pb.cc.
References default_instance_, and protobuf_AddDesc_ZMQMessages_2eproto.
const ::google::protobuf::Descriptor * ZMQVersionHandleMessage::descriptor () static
Definition at line 697 of file ZMQMessages.pb.cc.
int ZMQVersionHandleMessage::GetCachedSize () const inline
Definition at line 247 of file ZMQMessages.pb.h.
References _cached_size_.
google::protobuf::Metadata ZMQVersionHandleMessage::GetMetadata () const
Definition at line 894 of file ZMQMessages.pb.cc.
bool ZMQVersionHandleMessage::has_indicator () const inline
Definition at line 1114 of file ZMQMessages.pb.h.
References _has_bits_.
bool ZMQVersionHandleMessage::has_substantive () const inline
Definition at line 1136 of file ZMQMessages.pb.h.
References _has_bits_.
google::protobuf::uint32 ZMQVersionHandleMessage::indicator () const inline
Definition at line 1127 of file ZMQMessages.pb.h.
References indicator_.
void ZMQVersionHandleMessage::InitAsDefaultInstance () private
Definition at line 667 of file ZMQMessages.pb.cc.
bool ZMQVersionHandleMessage::IsInitialized () const
Definition at line 878 of file ZMQMessages.pb.cc.
References _has_bits_.
void ZMQVersionHandleMessage::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 841 of file ZMQMessages.pb.cc.
void ZMQVersionHandleMessage::MergeFrom (const ZMQVersionHandleMessage & from)
Definition at line 853 of file ZMQMessages.pb.cc.
References _has_bits_, has_indicator(), has_substantive(), indicator(), mutable_unknown_fields(), set_indicator(), set_substantive(), substantive(), and unknown_fields().
bool ZMQVersionHandleMessage::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 721 of file ZMQMessages.pb.cc.
References DO_, indicator_, mutable_unknown_fields(), set_has_indicator(), set_has_substantive(), and substantive_.
inline ::google::protobuf::UnknownFieldSet* ZMQVersionHandleMessage::mutable_unknown_fields () inline
Definition at line 222 of file ZMQMessages.pb.h.
References _unknown_fields_.
ZMQVersionHandleMessage * ZMQVersionHandleMessage::New () const
Definition at line 708 of file ZMQMessages.pb.cc.
References ZMQVersionHandleMessage().
ZMQVersionHandleMessage& ZMQVersionHandleMessage::operator= (const ZMQVersionHandleMessage & from) inline
Definition at line 213 of file ZMQMessages.pb.h.
References CopyFrom().
void ZMQVersionHandleMessage::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 774 of file ZMQMessages.pb.cc.
References has_indicator(), has_substantive(), indicator(), substantive(), and unknown_fields().
google::protobuf::uint8 * ZMQVersionHandleMessage::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 792 of file ZMQMessages.pb.cc.
References has_indicator(), has_substantive(), indicator(), substantive(), and unknown_fields().
void ZMQVersionHandleMessage::set_has_indicator () inline private
Definition at line 1117 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQVersionHandleMessage::set_has_substantive () inline private
Definition at line 1139 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQVersionHandleMessage::set_indicator (::google::protobuf::uint32 value) inline
Definition at line 1130 of file ZMQMessages.pb.h.
References indicator_, and set_has_indicator().
void ZMQVersionHandleMessage::set_substantive (::google::protobuf::uint64 value) inline
Definition at line 1152 of file ZMQMessages.pb.h.
References set_has_substantive(), and substantive_.
void ZMQVersionHandleMessage::SetCachedSize (int size) const private
Definition at line 692 of file ZMQMessages.pb.cc.
References _cached_size_.
void ZMQVersionHandleMessage::SharedCtor () private
Definition at line 676 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, indicator_, and substantive_.
void ZMQVersionHandleMessage::SharedDtor () private
Definition at line 687 of file ZMQMessages.pb.cc.
References default_instance_.
google::protobuf::uint64 ZMQVersionHandleMessage::substantive () const inline
Definition at line 1149 of file ZMQMessages.pb.h.
References substantive_.
void ZMQVersionHandleMessage::Swap (ZMQVersionHandleMessage * other)
Definition at line 884 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, indicator_, and substantive_.
const ::google::protobuf::UnknownFieldSet& ZMQVersionHandleMessage::unknown_fields () const inline
Definition at line 218 of file ZMQMessages.pb.h.
References _unknown_fields_.
Friends And Related Function Documentation
void protobuf_AddDesc_ZMQMessages_2eproto () friend
Definition at line 254 of file ZMQMessages.pb.cc.
void protobuf_AssignDesc_ZMQMessages_2eproto () friend
Definition at line 49 of file ZMQMessages.pb.cc.
void protobuf_ShutdownFile_ZMQMessages_2eproto () friend
Definition at line 235 of file ZMQMessages.pb.cc.
Member Data Documentation
int ZMQVersionHandleMessage::_cached_size_ mutable private
Definition at line 286 of file ZMQMessages.pb.h.
::google::protobuf::uint32 ZMQVersionHandleMessage::_has_bits_[(2+31)/32] private
Definition at line 287 of file ZMQMessages.pb.h.
::google::protobuf::UnknownFieldSet ZMQVersionHandleMessage::_unknown_fields_ private
Definition at line 281 of file ZMQMessages.pb.h.
ZMQVersionHandleMessage * ZMQVersionHandleMessage::default_instance_ = NULL static private
Definition at line 294 of file ZMQMessages.pb.h.
::google::protobuf::uint32 ZMQVersionHandleMessage::indicator_ private
Definition at line 284 of file ZMQMessages.pb.h.
const int ZMQVersionHandleMessage::kIndicatorFieldNumber = 1 static
Definition at line 263 of file ZMQMessages.pb.h.
const int ZMQVersionHandleMessage::kSubstantiveFieldNumber = 2 static
Definition at line 270 of file ZMQMessages.pb.h.
::google::protobuf::uint64 ZMQVersionHandleMessage::substantive_ private
Definition at line 283 of file ZMQMessages.pb.h.
The documentation for this class was generated from the following files:
opencog/persist/zmq/atomspace/ZMQMessages.pb.h
opencog/persist/zmq/atomspace/ZMQMessages.pb.cc