OpenCog Framework: opencog::IncomingIndex Class Reference
opencog::IncomingIndex Class Reference
atomspace library
#include <IncomingIndex.h>
Classes
class iterator
Public Member Functions
IncomingIndex (void)
void insertAtom (const AtomPtr &a)
void removeAtom (const AtomPtr &a)
void resize ()
const UnorderedHandleSet & getIncomingSet (Handle) const
iterator begin (Handle) const
iterator end (void) const
Private Attributes
HandleSetIndex idx
Detailed Description
Implements a Handle index array of RB-trees (C++ set) Given a Handle, this returns the incoming set of that handle.
Todo:
The iterator is NOT thread-safe against the insertion or removal of atoms! Either inserting or removing an atom will cause the iterator references to be freed, leading to mystery crashes!
The const UnorderedHandleSet& returned by the getIncomingSet() method will also become invalid if an atom is inserted or deleted (for that particular IncomingSet).
Definition at line 49 of file IncomingIndex.h.
Constructor & Destructor Documentation
IncomingIndex::IncomingIndex (void)
Definition at line 29 of file IncomingIndex.cc.
Member Function Documentation
IncomingIndex::iterator IncomingIndex::begin (Handle h) const
Definition at line 111 of file IncomingIndex.cc.
References opencog::IncomingIndex::iterator::_e, opencog::IncomingIndex::iterator::_iset, opencog::IncomingIndex::iterator::_s, opencog::HandleSetIndex::get(), idx, and opencog::Handle::UNDEFINED.
IncomingIndex::iterator IncomingIndex::end (void) const
Definition at line 121 of file IncomingIndex.cc.
References opencog::IncomingIndex::iterator::_e, opencog::IncomingIndex::iterator::_iset, opencog::IncomingIndex::iterator::_s, and opencog::Handle::UNDEFINED.
const UnorderedHandleSet & IncomingIndex::getIncomingSet (Handle h) const
Definition at line 104 of file IncomingIndex.cc.
References opencog::HandleSetIndex::get(), and idx.
void IncomingIndex::insertAtom (const AtomPtr & a)
Definition at line 37 of file IncomingIndex.cc.
References opencog::HandleSetIndex::get(), opencog::Atom::getHandle(), idx, opencog::HandleSetIndex::insert(), opencog::LinkCast(), and opencog::HandleSetIndex::remove().
void IncomingIndex::removeAtom (const AtomPtr & a)
Definition at line 70 of file IncomingIndex.cc.
References opencog::HandleSetIndex::get(), opencog::Atom::getHandle(), idx, opencog::HandleSetIndex::insert(), opencog::LinkCast(), and opencog::HandleSetIndex::remove().
void IncomingIndex::resize ()
Definition at line 33 of file IncomingIndex.cc.
Member Data Documentation
HandleSetIndex opencog::IncomingIndex::idx private
Definition at line 52 of file IncomingIndex.h.
The documentation for this class was generated from the following files:
opencog/atomspace/IncomingIndex.h
opencog/atomspace/IncomingIndex.cc