OpenCog Framework: opencog::ZMQClient Class Reference
opencog::ZMQClient Class Reference
atomspace library
#include <ZMQClient.h>
Public Member Functions
ZMQClient (string networkAddres="tcp://127.0.0.1:5555")
~ZMQClient ()
AtomPtr getAtom (Handle &h)
Private Member Functions
void SendMessage (ZMQRequestMessage &requestMessage, ZMQReplyMessage &replyMessage)
Private Attributes
zmq::socket_t * zmqClientSocket
zmq::context_t * zmqContext
Detailed Description
Definition at line 43 of file ZMQClient.h.
Constructor & Destructor Documentation
ZMQClient::ZMQClient (string networkAddres = "tcp://127.0.0.1:5555")
Definition at line 31 of file ZMQClient.cc.
References zmqClientSocket, and zmqContext.
ZMQClient::~ZMQClient ()
Definition at line 38 of file ZMQClient.cc.
References zmqClientSocket, and zmqContext.
Member Function Documentation
AtomPtr ZMQClient::getAtom (Handle & h)
Definition at line 60 of file ZMQClient.cc.
References python.atom_type_names::atom, ZMQReplyMessage::atom(), opencog::ProtocolBufferSerializer::deserialize(), SendMessage(), ZMQRequestMessage::set_function(), ZMQRequestMessage::set_handle(), opencog::Handle::value(), and ZMQgetAtom.
void ZMQClient::SendMessage (ZMQRequestMessage & requestMessage, ZMQReplyMessage & replyMessage) private
Definition at line 44 of file ZMQClient.cc.
References zmqClientSocket.
Member Data Documentation
zmq::socket_t* opencog::ZMQClient::zmqClientSocket private
Definition at line 44 of file ZMQClient.h.
zmq::context_t* opencog::ZMQClient::zmqContext private
Definition at line 45 of file ZMQClient.h.
The documentation for this class was generated from the following files:
opencog/persist/zmq/atomspace/ZMQClient.h
opencog/persist/zmq/atomspace/ZMQClient.cc