OpenCog Framework: opencog::ProtocolBufferSerializer Class Reference
opencog::ProtocolBufferSerializer Class Reference
atomspace library
#include <ProtocolBufferSerializer.h>
Public Member Functions
ProtocolBufferSerializer ()
~ProtocolBufferSerializer ()
Static Public Member Functions
static Atom * deserialize (const ZMQAtomMessage &atomMessage)
static void serialize (Atom &atom, ZMQAtomMessage *atomMessage)
static TruthValue * deserialize (const ZMQTruthValueMessage &truthValueMessage)
static void serialize (TruthValue &tv, ZMQTruthValueMessage *truthValueMessage)
Static Private Member Functions
static void deserializeAtom (const ZMQAtomMessage &atomMessage, Atom &atom)
static void serializeAtom (Atom &atom, ZMQAtomMessage *atomMessage)
static void deserializeAttentionValue (const ZMQAttentionValueHolderMessage &attentionValueHolderMessage, AttentionValue &av)
static void serializeAttentionValue (AttentionValue &av, ZMQAttentionValueHolderMessage *attentionValueHolderMessage)
static void deserializeAttentionValueHolder (const ZMQAttentionValueHolderMessage &attentionValueHolderMessage, AttentionValueHolder &attentionValueHolder)
static void serializeAttentionValueHolder (AttentionValueHolder &attentionValueHolder, ZMQAttentionValueHolderMessage *attentionValueHolderMessage)
static void deserializeLink (const ZMQAtomMessage &atomMessage, Link &link)
static void serializeLink (Link &link, ZMQAtomMessage *atomMessage)
static void deserializeNode (const ZMQAtomMessage &atomMessage, Node &node)
static void serializeNode (Node &node, ZMQAtomMessage *atomMessage)
static void deserializeCompositeTruthValue (const ZMQTruthValueMessage &truthValueMessage, CompositeTruthValue &tv)
static void serializeCompositeTruthValue (CompositeTruthValue &tv, ZMQTruthValueMessage *truthValueMessage)
static void deserializeCountTruthValue (const ZMQSingleTruthValueMessage &singleTruthValue, CountTruthValue &tv)
static void serializeCountTruthValue (CountTruthValue &tv, ZMQTruthValueMessage *truthValueMessage)
static void deserializeIndefiniteTruthValue (const ZMQSingleTruthValueMessage &singleTruthValue, IndefiniteTruthValue &tv)
static void serializeIndefiniteTruthValue (IndefiniteTruthValue &tv, ZMQTruthValueMessage *truthValueMessage)
static void serializeNullTruthValue (NullTruthValue &tv, ZMQTruthValueMessage *truthValueMessage)
static void deserializeSimpleTruthValue (const ZMQSingleTruthValueMessage &singleTruthValue, SimpleTruthValue &tv)
static void serializeSimpleTruthValue (SimpleTruthValue &tv, ZMQTruthValueMessage *truthValueMessage)
static void deserializeTrail (const ZMQTrailMessage &trailMessage, Trail &trail)
static void serializeTrail (Trail &trail, ZMQTrailMessage *trailMessage)
static void deserializeVersionHandle (const ZMQVersionHandleMessage &versionHandleMessage, VersionHandle &vh)
static void serializeVersionHandle (VersionHandle &vh, ZMQVersionHandleMessage *versionHandleMessage)
static TruthValue * deserialize (const ZMQSingleTruthValueMessage &singleTruthValueMessage)
Detailed Description
Definition at line 55 of file ProtocolBufferSerializer.h.
Constructor & Destructor Documentation
ProtocolBufferSerializer::ProtocolBufferSerializer ()
Definition at line 44 of file ProtocolBufferSerializer.cc.
ProtocolBufferSerializer::~ProtocolBufferSerializer ()
Definition at line 48 of file ProtocolBufferSerializer.cc.
Member Function Documentation
TruthValue * ProtocolBufferSerializer::deserialize (const ZMQSingleTruthValueMessage & singleTruthValueMessage) static private
Definition at line 395 of file ProtocolBufferSerializer.cc.
References deserializeCountTruthValue(), deserializeIndefiniteTruthValue(), deserializeSimpleTruthValue(), ZMQSingleTruthValueMessage::truthvaluetype(), tv, ZMQTruthValueTypeCount, ZMQTruthValueTypeIndefinite, ZMQTruthValueTypeNull, and ZMQTruthValueTypeSimple.
Atom * ProtocolBufferSerializer::deserialize (const ZMQAtomMessage & atomMessage) static
Definition at line 102 of file ProtocolBufferSerializer.cc.
References ZMQAtomMessage::atomtype(), deserializeLink(), deserializeNode(), ZMQAtomTypeLink, and ZMQAtomTypeNode.
TruthValue * ProtocolBufferSerializer::deserialize (const ZMQTruthValueMessage & truthValueMessage) static
Definition at line 382 of file ProtocolBufferSerializer.cc.
References deserialize(), deserializeCompositeTruthValue(), ZMQTruthValueMessage::singletruthvalue(), ZMQTruthValueMessage::singletruthvalue_size(), and tv.
void ProtocolBufferSerializer::deserializeAtom (const ZMQAtomMessage & atomMessage, Atom & atom) static private
Definition at line 53 of file ProtocolBufferSerializer.cc.
References python.atom_type_names::atom, ZMQAtomMessage::attentionvalueholder(), deserialize(), deserializeAttentionValueHolder(), ZMQAtomMessage::flags(), ZMQAtomMessage::handle(), ZMQAtomMessage::incoming(), ZMQAtomMessage::incoming_size(), ZMQAtomMessage::truthvalue(), and ZMQAtomMessage::type().
void ProtocolBufferSerializer::deserializeAttentionValue (const ZMQAttentionValueHolderMessage & attentionValueHolderMessage, AttentionValue & av) static private
Definition at line 138 of file ProtocolBufferSerializer.cc.
References ZMQAttentionValueHolderMessage::lti(), opencog::AttentionValue::m_LTI, opencog::AttentionValue::m_STI, opencog::AttentionValue::m_VLTI, ZMQAttentionValueHolderMessage::sti(), and ZMQAttentionValueHolderMessage::vlti().
void ProtocolBufferSerializer::deserializeAttentionValueHolder (const ZMQAttentionValueHolderMessage & attentionValueHolderMessage, AttentionValueHolder & attentionValueHolder) static private
Definition at line 155 of file ProtocolBufferSerializer.cc.
References deserializeAttentionValue().
void ProtocolBufferSerializer::deserializeCompositeTruthValue (const ZMQTruthValueMessage & truthValueMessage, CompositeTruthValue & tv) static private
Definition at line 168 of file ProtocolBufferSerializer.cc.
References deserialize(), deserializeVersionHandle(), ZMQTruthValueMessage::singletruthvalue(), ZMQTruthValueMessage::singletruthvalue_size(), and ZMQSingleTruthValueMessage::versionhandle().
void ProtocolBufferSerializer::deserializeCountTruthValue (const ZMQSingleTruthValueMessage & singleTruthValue, CountTruthValue & tv) static private
Definition at line 196 of file ProtocolBufferSerializer.cc.
References opencog::CountTruthValue::confidence, ZMQSingleTruthValueMessage::confidence(), opencog::CountTruthValue::count, ZMQSingleTruthValueMessage::count(), opencog::CountTruthValue::mean, and ZMQSingleTruthValueMessage::mean().
void ProtocolBufferSerializer::deserializeIndefiniteTruthValue (const ZMQSingleTruthValueMessage & singleTruthValue, IndefiniteTruthValue & tv) static private
Definition at line 214 of file ProtocolBufferSerializer.cc.
References opencog::IndefiniteTruthValue::confidence, ZMQSingleTruthValueMessage::confidence(), opencog::IndefiniteTruthValue::confidenceLevel, ZMQSingleTruthValueMessage::confidencelevel(), opencog::IndefiniteTruthValue::count, ZMQSingleTruthValueMessage::count(), opencog::IndefiniteTruthValue::diff, ZMQSingleTruthValueMessage::diff(), opencog::IndefiniteTruthValue::firstOrderDistribution, ZMQSingleTruthValueMessage::firstorderdistribution(), ZMQSingleTruthValueMessage::firstorderdistribution_size(), opencog::IndefiniteTruthValue::L, ZMQSingleTruthValueMessage::l(), opencog::IndefiniteTruthValue::mean, ZMQSingleTruthValueMessage::mean(), opencog::IndefiniteTruthValue::symmetric, ZMQSingleTruthValueMessage::symmetric(), opencog::IndefiniteTruthValue::U, and ZMQSingleTruthValueMessage::u().
void ProtocolBufferSerializer::deserializeLink (const ZMQAtomMessage & atomMessage, Link & link) static private
Definition at line 252 of file ProtocolBufferSerializer.cc.
References deserializeAtom(), deserializeTrail(), ZMQAtomMessage::has_trail(), ZMQAtomMessage::outgoing(), ZMQAtomMessage::outgoing_size(), and ZMQAtomMessage::trail().
void ProtocolBufferSerializer::deserializeNode (const ZMQAtomMessage & atomMessage, Node & node) static private
Definition at line 285 of file ProtocolBufferSerializer.cc.
References deserializeAtom(), and ZMQAtomMessage::name().
void ProtocolBufferSerializer::deserializeSimpleTruthValue (const ZMQSingleTruthValueMessage & singleTruthValue, SimpleTruthValue & tv) static private
Definition at line 310 of file ProtocolBufferSerializer.cc.
References opencog::SimpleTruthValue::count, ZMQSingleTruthValueMessage::count(), opencog::SimpleTruthValue::mean, and ZMQSingleTruthValueMessage::mean().
void ProtocolBufferSerializer::deserializeTrail (const ZMQTrailMessage & trailMessage, Trail & trail) static private
Definition at line 326 of file ProtocolBufferSerializer.cc.
References ZMQTrailMessage::maxsize(), ZMQTrailMessage::trail(), and ZMQTrailMessage::trail_size().
void ProtocolBufferSerializer::deserializeVersionHandle (const ZMQVersionHandleMessage & versionHandleMessage, VersionHandle & vh) static private
Definition at line 429 of file ProtocolBufferSerializer.cc.
References ZMQVersionHandleMessage::indicator(), and ZMQVersionHandleMessage::substantive().
void ProtocolBufferSerializer::serialize (Atom & atom, ZMQAtomMessage * atomMessage) static
Definition at line 123 of file ProtocolBufferSerializer.cc.
References python.atom_type_names::atom, serializeLink(), and serializeNode().
void ProtocolBufferSerializer::serialize (TruthValue & tv, ZMQTruthValueMessage * truthValueMessage) static
Definition at line 349 of file ProtocolBufferSerializer.cc.
References serializeCountTruthValue(), serializeIndefiniteTruthValue(), serializeNullTruthValue(), serializeSimpleTruthValue(), and tv.
void ProtocolBufferSerializer::serializeAtom (Atom & atom, ZMQAtomMessage * atomMessage) static private
Definition at line 82 of file ProtocolBufferSerializer.cc.
References ZMQAtomMessage::add_incoming(), ZMQAtomMessage::mutable_attentionvalueholder(), ZMQAtomMessage::mutable_truthvalue(), serialize(), serializeAttentionValueHolder(), ZMQAtomMessage::set_flags(), ZMQAtomMessage::set_handle(), and ZMQAtomMessage::set_type().
void ProtocolBufferSerializer::serializeAttentionValue (AttentionValue & av, ZMQAttentionValueHolderMessage * attentionValueHolderMessage) static private
Definition at line 147 of file ProtocolBufferSerializer.cc.
References opencog::AttentionValue::m_LTI, opencog::AttentionValue::m_STI, opencog::AttentionValue::m_VLTI, ZMQAttentionValueHolderMessage::set_lti(), ZMQAttentionValueHolderMessage::set_sti(), and ZMQAttentionValueHolderMessage::set_vlti().
void ProtocolBufferSerializer::serializeAttentionValueHolder (AttentionValueHolder & attentionValueHolder, ZMQAttentionValueHolderMessage * attentionValueHolderMessage) static private
Definition at line 162 of file ProtocolBufferSerializer.cc.
References serializeAttentionValue().
void ProtocolBufferSerializer::serializeCompositeTruthValue (CompositeTruthValue & tv, ZMQTruthValueMessage * truthValueMessage) static private
Definition at line 182 of file ProtocolBufferSerializer.cc.
References ZMQTruthValueMessage::mutable_singletruthvalue(), serialize(), serializeVersionHandle(), and ZMQTruthValueMessage::singletruthvalue_size().
void ProtocolBufferSerializer::serializeCountTruthValue (CountTruthValue & tv, ZMQTruthValueMessage * truthValueMessage) static private
Definition at line 204 of file ProtocolBufferSerializer.cc.
References ZMQTruthValueMessage::add_singletruthvalue(), opencog::CountTruthValue::confidence, opencog::CountTruthValue::count, opencog::CountTruthValue::mean, ZMQSingleTruthValueMessage::set_confidence(), ZMQSingleTruthValueMessage::set_count(), ZMQSingleTruthValueMessage::set_mean(), ZMQSingleTruthValueMessage::set_truthvaluetype(), and ZMQTruthValueTypeCount.
void ProtocolBufferSerializer::serializeIndefiniteTruthValue (IndefiniteTruthValue & tv, ZMQTruthValueMessage * truthValueMessage) static private
Definition at line 233 of file ProtocolBufferSerializer.cc.
References ZMQSingleTruthValueMessage::add_firstorderdistribution(), ZMQTruthValueMessage::add_singletruthvalue(), opencog::IndefiniteTruthValue::confidence, opencog::IndefiniteTruthValue::confidenceLevel, opencog::IndefiniteTruthValue::count, opencog::IndefiniteTruthValue::diff, opencog::IndefiniteTruthValue::firstOrderDistribution, opencog::IndefiniteTruthValue::L, opencog::IndefiniteTruthValue::mean, ZMQSingleTruthValueMessage::set_confidence(), ZMQSingleTruthValueMessage::set_confidencelevel(), ZMQSingleTruthValueMessage::set_count(), ZMQSingleTruthValueMessage::set_diff(), ZMQSingleTruthValueMessage::set_l(), ZMQSingleTruthValueMessage::set_mean(), ZMQSingleTruthValueMessage::set_symmetric(), ZMQSingleTruthValueMessage::set_truthvaluetype(), ZMQSingleTruthValueMessage::set_u(), opencog::IndefiniteTruthValue::symmetric, opencog::IndefiniteTruthValue::U, and ZMQTruthValueTypeIndefinite.
void ProtocolBufferSerializer::serializeLink (Link & link, ZMQAtomMessage * atomMessage) static private
Definition at line 271 of file ProtocolBufferSerializer.cc.
References ZMQAtomMessage::add_outgoing(), ZMQAtomMessage::mutable_trail(), serializeAtom(), serializeTrail(), ZMQAtomMessage::set_atomtype(), opencog::Handle::value(), and ZMQAtomTypeLink.
void ProtocolBufferSerializer::serializeNode (Node & node, ZMQAtomMessage * atomMessage) static private
Definition at line 293 of file ProtocolBufferSerializer.cc.
References serializeAtom(), ZMQAtomMessage::set_atomtype(), ZMQAtomMessage::set_name(), and ZMQAtomTypeNode.
void ProtocolBufferSerializer::serializeNullTruthValue (NullTruthValue & tv, ZMQTruthValueMessage * truthValueMessage) static private
Definition at line 303 of file ProtocolBufferSerializer.cc.
References ZMQTruthValueMessage::add_singletruthvalue(), ZMQSingleTruthValueMessage::set_truthvaluetype(), and ZMQTruthValueTypeNull.
void ProtocolBufferSerializer::serializeSimpleTruthValue (SimpleTruthValue & tv, ZMQTruthValueMessage * truthValueMessage) static private
Definition at line 317 of file ProtocolBufferSerializer.cc.
References ZMQTruthValueMessage::add_singletruthvalue(), opencog::SimpleTruthValue::count, opencog::SimpleTruthValue::mean, ZMQSingleTruthValueMessage::set_count(), ZMQSingleTruthValueMessage::set_mean(), ZMQSingleTruthValueMessage::set_truthvaluetype(), and ZMQTruthValueTypeSimple.
void ProtocolBufferSerializer::serializeTrail (Trail & trail, ZMQTrailMessage * trailMessage) static private
Definition at line 342 of file ProtocolBufferSerializer.cc.
References ZMQTrailMessage::add_trail(), and ZMQTrailMessage::set_maxsize().
void ProtocolBufferSerializer::serializeVersionHandle (VersionHandle & vh, ZMQVersionHandleMessage * versionHandleMessage) static private
Definition at line 436 of file ProtocolBufferSerializer.cc.
References ZMQVersionHandleMessage::set_indicator(), and ZMQVersionHandleMessage::set_substantive().
The documentation for this class was generated from the following files:
opencog/persist/zmq/atomspace/ProtocolBufferSerializer.h
opencog/persist/zmq/atomspace/ProtocolBufferSerializer.cc