OpenCog Framework: ZMQReplyMessage Class Reference
ZMQReplyMessage Class Reference
#include <ZMQMessages.pb.h>
Public Member Functions
ZMQReplyMessage ()
virtual ~ZMQReplyMessage ()
ZMQReplyMessage (const ZMQReplyMessage &from)
ZMQReplyMessage & operator= (const ZMQReplyMessage &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (ZMQReplyMessage *other)
ZMQReplyMessage * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const ZMQReplyMessage &from)
void MergeFrom (const ZMQReplyMessage &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_atom () const
void clear_atom ()
const ::ZMQAtomMessage & atom () const
inline::ZMQAtomMessage * mutable_atom ()
inline::ZMQAtomMessage * release_atom ()
bool has_str () const
void clear_str ()
const ::std::string & str () const
void set_str (const ::std::string &value)
void set_str (const char *value)
void set_str (const char *value, size_t size)
inline::std::string * mutable_str ()
inline::std::string * release_str ()
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const ZMQReplyMessage & default_instance ()
Static Public Attributes
static const int kAtomFieldNumber = 1
static const int kStrFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_atom ()
void clear_has_atom ()
void set_has_str ()
void clear_has_str ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::ZMQAtomMessage * atom_
::std::string * str_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(2+31)/32]
Static Private Attributes
static ZMQReplyMessage * default_instance_ = NULL
Friends
void protobuf_AddDesc_ZMQMessages_2eproto ()
void protobuf_AssignDesc_ZMQMessages_2eproto ()
void protobuf_ShutdownFile_ZMQMessages_2eproto ()
Detailed Description
Definition at line 941 of file ZMQMessages.pb.h.
Constructor & Destructor Documentation
ZMQReplyMessage::ZMQReplyMessage ()
Definition at line 2881 of file ZMQMessages.pb.cc.
References SharedCtor().
ZMQReplyMessage::~ZMQReplyMessage () virtual
Definition at line 2903 of file ZMQMessages.pb.cc.
References SharedDtor().
ZMQReplyMessage::ZMQReplyMessage (const ZMQReplyMessage & from)
Definition at line 2890 of file ZMQMessages.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
const ::ZMQAtomMessage & ZMQReplyMessage::atom () const inline
Definition at line 1849 of file ZMQMessages.pb.h.
References atom_, and default_instance_.
int ZMQReplyMessage::ByteSize () const
Definition at line 3052 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, atom(), has_atom(), has_str(), str(), and unknown_fields().
void ZMQReplyMessage::Clear ()
Definition at line 2936 of file ZMQMessages.pb.cc.
References _has_bits_, atom_, has_atom(), has_str(), mutable_unknown_fields(), and str_.
void ZMQReplyMessage::clear_atom () inline
Definition at line 1845 of file ZMQMessages.pb.h.
References atom_, and clear_has_atom().
void ZMQReplyMessage::clear_has_atom () inline private
Definition at line 1842 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQReplyMessage::clear_has_str () inline private
Definition at line 1871 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQReplyMessage::clear_str () inline
Definition at line 1874 of file ZMQMessages.pb.h.
References clear_has_str(), and str_.
void ZMQReplyMessage::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 3107 of file ZMQMessages.pb.cc.
References Clear(), and MergeFrom().
void ZMQReplyMessage::CopyFrom (const ZMQReplyMessage & from)
Definition at line 3113 of file ZMQMessages.pb.cc.
References Clear(), and MergeFrom().
const ZMQReplyMessage & ZMQReplyMessage::default_instance () static
Definition at line 2926 of file ZMQMessages.pb.cc.
References default_instance_, and protobuf_AddDesc_ZMQMessages_2eproto.
const ::google::protobuf::Descriptor * ZMQReplyMessage::descriptor () static
Definition at line 2921 of file ZMQMessages.pb.cc.
int ZMQReplyMessage::GetCachedSize () const inline
Definition at line 982 of file ZMQMessages.pb.h.
References _cached_size_.
google::protobuf::Metadata ZMQReplyMessage::GetMetadata () const
Definition at line 3137 of file ZMQMessages.pb.cc.
bool ZMQReplyMessage::has_atom () const inline
Definition at line 1836 of file ZMQMessages.pb.h.
References _has_bits_.
bool ZMQReplyMessage::has_str () const inline
Definition at line 1865 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQReplyMessage::InitAsDefaultInstance () private
Definition at line 2886 of file ZMQMessages.pb.cc.
References atom_, and ZMQAtomMessage::default_instance().
bool ZMQReplyMessage::IsInitialized () const
Definition at line 3119 of file ZMQMessages.pb.cc.
References atom(), and has_atom().
void ZMQReplyMessage::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 3082 of file ZMQMessages.pb.cc.
void ZMQReplyMessage::MergeFrom (const ZMQReplyMessage & from)
Definition at line 3094 of file ZMQMessages.pb.cc.
References _has_bits_, atom(), has_atom(), has_str(), mutable_atom(), mutable_unknown_fields(), set_str(), str(), and unknown_fields().
bool ZMQReplyMessage::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 2951 of file ZMQMessages.pb.cc.
References python.atom_type_names::data, DO_, mutable_atom(), mutable_str(), mutable_unknown_fields(), and str().
ZMQAtomMessage * ZMQReplyMessage::mutable_atom () inline
Definition at line 1852 of file ZMQMessages.pb.h.
References atom_, and set_has_atom().
std::string * ZMQReplyMessage::mutable_str () inline
Definition at line 1904 of file ZMQMessages.pb.h.
References set_has_str(), and str_.
inline ::google::protobuf::UnknownFieldSet* ZMQReplyMessage::mutable_unknown_fields () inline
Definition at line 957 of file ZMQMessages.pb.h.
References _unknown_fields_.
ZMQReplyMessage * ZMQReplyMessage::New () const
Definition at line 2932 of file ZMQMessages.pb.cc.
References ZMQReplyMessage().
ZMQReplyMessage& ZMQReplyMessage::operator= (const ZMQReplyMessage & from) inline
Definition at line 948 of file ZMQMessages.pb.h.
References CopyFrom().
ZMQAtomMessage * ZMQReplyMessage::release_atom () inline
Definition at line 1857 of file ZMQMessages.pb.h.
References atom_, and clear_has_atom().
std::string * ZMQReplyMessage::release_str () inline
Definition at line 1911 of file ZMQMessages.pb.h.
References clear_has_str(), and str_.
void ZMQReplyMessage::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 3003 of file ZMQMessages.pb.cc.
References atom(), python.atom_type_names::data, has_atom(), has_str(), str(), and unknown_fields().
google::protobuf::uint8 * ZMQReplyMessage::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 3026 of file ZMQMessages.pb.cc.
References atom(), python.atom_type_names::data, has_atom(), has_str(), str(), and unknown_fields().
void ZMQReplyMessage::set_has_atom () inline private
Definition at line 1839 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQReplyMessage::set_has_str () inline private
Definition at line 1868 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQReplyMessage::set_str (const ::std::string & value) inline
Definition at line 1883 of file ZMQMessages.pb.h.
References set_has_str(), and str_.
void ZMQReplyMessage::set_str (const char * value) inline
Definition at line 1890 of file ZMQMessages.pb.h.
References set_has_str(), and str_.
void ZMQReplyMessage::set_str (const char * value, size_t size) inline
Definition at line 1897 of file ZMQMessages.pb.h.
References set_has_str(), and str_.
void ZMQReplyMessage::SetCachedSize (int size) const private
Definition at line 2916 of file ZMQMessages.pb.cc.
References _cached_size_.
void ZMQReplyMessage::SharedCtor () private
Definition at line 2896 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, atom_, and str_.
void ZMQReplyMessage::SharedDtor () private
Definition at line 2907 of file ZMQMessages.pb.cc.
References atom_, default_instance_, and str_.
const ::std::string & ZMQReplyMessage::str () const inline
Definition at line 1880 of file ZMQMessages.pb.h.
References str_.
void ZMQReplyMessage::Swap (ZMQReplyMessage * other)
Definition at line 3127 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, atom_, and str_.
const ::google::protobuf::UnknownFieldSet& ZMQReplyMessage::unknown_fields () const inline
Definition at line 953 of file ZMQMessages.pb.h.
References _unknown_fields_.
Friends And Related Function Documentation
void protobuf_AddDesc_ZMQMessages_2eproto () friend
Definition at line 254 of file ZMQMessages.pb.cc.
void protobuf_AssignDesc_ZMQMessages_2eproto () friend
Definition at line 49 of file ZMQMessages.pb.cc.
void protobuf_ShutdownFile_ZMQMessages_2eproto () friend
Definition at line 235 of file ZMQMessages.pb.cc.
Member Data Documentation
int ZMQReplyMessage::_cached_size_ mutable private
Definition at line 1026 of file ZMQMessages.pb.h.
::google::protobuf::uint32 ZMQReplyMessage::_has_bits_[(2+31)/32] private
Definition at line 1027 of file ZMQMessages.pb.h.
::google::protobuf::UnknownFieldSet ZMQReplyMessage::_unknown_fields_ private
Definition at line 1021 of file ZMQMessages.pb.h.
::ZMQAtomMessage* ZMQReplyMessage::atom_ private
Definition at line 1023 of file ZMQMessages.pb.h.
ZMQReplyMessage * ZMQReplyMessage::default_instance_ = NULL static private
Definition at line 1034 of file ZMQMessages.pb.h.
const int ZMQReplyMessage::kAtomFieldNumber = 1 static
Definition at line 998 of file ZMQMessages.pb.h.
const int ZMQReplyMessage::kStrFieldNumber = 2 static
Definition at line 1006 of file ZMQMessages.pb.h.
::std::string* ZMQReplyMessage::str_ private
Definition at line 1024 of file ZMQMessages.pb.h.
The documentation for this class was generated from the following files:
opencog/persist/zmq/atomspace/ZMQMessages.pb.h
opencog/persist/zmq/atomspace/ZMQMessages.pb.cc