OpenCog Framework: opencog::NodeIndex Class Reference
opencog::NodeIndex Class Reference
atomspace library
#include <NodeIndex.h>
Public Member Functions
NodeIndex ()
void insertAtom (Atom *a)
void removeAtom (Atom *a)
void resize ()
size_t size () const
Atom * getAtom (Type type, const std::string &str) const
UnorderedHandleSet getHandleSet (Type type, const std::string &, bool subclass) const
template<typename OutputIterator >
OutputIterator getHandleSet (OutputIterator result, Type type, const std::string &name, bool subclass) const
Private Attributes
std::vector< NameIndex > idx
Detailed Description
Implements an (type, name) index array of RB-trees (C++ set) That is, given only the type and name of an atom, this will return the corresponding handle of that atom.
Definition at line 42 of file NodeIndex.h.
Constructor & Destructor Documentation
NodeIndex::NodeIndex ()
Definition at line 29 of file NodeIndex.cc.
References resize().
Member Function Documentation
Atom* opencog::NodeIndex::getAtom (Type type, const std::string & str) const inline
Definition at line 63 of file NodeIndex.h.
References opencog::StringIndex::get(), and idx.
UnorderedHandleSet NodeIndex::getHandleSet (Type type, const std::string & name, bool subclass) const
Definition at line 46 of file NodeIndex.cc.
References python.atom_type_names::atom, opencog::classserver(), getAtom(), opencog::Atom::getHandle(), and idx.
template<typename OutputIterator > OutputIterator opencog::NodeIndex::getHandleSet (OutputIterator result, Type type, const std::string & name, bool subclass) const inline
Definition at line 72 of file NodeIndex.h.
References python.atom_type_names::atom, opencog::classserver(), getAtom(), opencog::Atom::getHandle(), idx, and python.bindlink::result.
void opencog::NodeIndex::insertAtom (Atom * a) inline
Definition at line 50 of file NodeIndex.h.
References opencog::Atom::getType(), idx, and opencog::NameIndex::insertAtom().
void opencog::NodeIndex::removeAtom (Atom * a) inline
Definition at line 55 of file NodeIndex.h.
References opencog::Atom::getType(), idx, and opencog::NameIndex::removeAtom().
void NodeIndex::resize ()
Definition at line 34 of file NodeIndex.cc.
References opencog::classserver(), and idx.
size_t NodeIndex::size (void) const
Definition at line 39 of file NodeIndex.cc.
References idx.
Member Data Documentation
std::vector<NameIndex> opencog::NodeIndex::idx private
Definition at line 45 of file NodeIndex.h.
The documentation for this class was generated from the following files:
opencog/atomspace/NodeIndex.h
opencog/atomspace/NodeIndex.cc