OpenCog Framework: opencog::Substitutor Class Reference
opencog::Substitutor Class Reference
#include <Substitutor.h>
Public Member Functions
Substitutor (AtomSpace *as)
Handle substitute (const Handle &expr, const std::map< Handle, Handle > &vars)
Private Member Functions
Handle walk_tree (const Handle &expr)
Private Attributes
AtomSpace * _as
const std::map< Handle, Handle > * _vmap
Detailed Description
Like the Instantiator but does not execute stuff, and also works for non-VariableNode.
Also a bit like VariableList's substitute, but again also works for non-VariableNode.
Won't recurse into the atom substituted; so if the new atom also contains sub-atom to be subsituted, they will be ignored.
Definition at line 44 of file Substitutor.h.
Constructor & Destructor Documentation
opencog::Substitutor::Substitutor (AtomSpace * as) inline
Definition at line 74 of file Substitutor.h.
Member Function Documentation
Handle opencog::Substitutor::substitute (const Handle & expr, const std::map< Handle, Handle > & vars) inline
The main method to call to substitue sub-atoms.
Parameters
expr the original atom
vars an atom to atom mapping
Returns
a new atom with sub-atoms replaced
Definition at line 83 of file Substitutor.h.
References _as, _vmap, opencog::AtomSpace::add_atom(), opencog::Handle::UNDEFINED, and walk_tree().
Handle opencog::Substitutor::walk_tree (const Handle & expr) inline private
Definition at line 50 of file Substitutor.h.
References _vmap, createLink, opencog::Atom::getTruthValue(), opencog::Atom::getType(), and opencog::LinkCast().
Member Data Documentation
AtomSpace* opencog::Substitutor::_as private
Definition at line 47 of file Substitutor.h.
const std::map<Handle, Handle>* opencog::Substitutor::_vmap private
Definition at line 48 of file Substitutor.h.
The documentation for this class was generated from the following file:
opencog/atomutils/Substitutor.h