OpenCog Framework: ZMQRequestMessage Class Reference
ZMQRequestMessage Class Reference
#include <ZMQMessages.pb.h>
Public Member Functions
ZMQRequestMessage ()
virtual ~ZMQRequestMessage ()
ZMQRequestMessage (const ZMQRequestMessage &from)
ZMQRequestMessage & operator= (const ZMQRequestMessage &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (ZMQRequestMessage *other)
ZMQRequestMessage * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const ZMQRequestMessage &from)
void MergeFrom (const ZMQRequestMessage &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_function () const
void clear_function ()
ZMQFunctionType function () const
void set_function (ZMQFunctionType value)
bool has_handle () const
void clear_handle ()
inline::google::protobuf::uint64 handle () const
void set_handle (::google::protobuf::uint64 value)
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const ZMQRequestMessage & default_instance ()
Static Public Attributes
static const int kFunctionFieldNumber = 1
static const int kHandleFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_function ()
void clear_has_function ()
void set_has_handle ()
void clear_has_handle ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::google::protobuf::uint64 handle_
int function_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(2+31)/32]
Static Private Attributes
static ZMQRequestMessage * default_instance_ = NULL
Friends
void protobuf_AddDesc_ZMQMessages_2eproto ()
void protobuf_AssignDesc_ZMQMessages_2eproto ()
void protobuf_ShutdownFile_ZMQMessages_2eproto ()
Detailed Description
Definition at line 849 of file ZMQMessages.pb.h.
Constructor & Destructor Documentation
ZMQRequestMessage::ZMQRequestMessage ()
Definition at line 2627 of file ZMQMessages.pb.cc.
References SharedCtor().
ZMQRequestMessage::~ZMQRequestMessage () virtual
Definition at line 2648 of file ZMQMessages.pb.cc.
References SharedDtor().
ZMQRequestMessage::ZMQRequestMessage (const ZMQRequestMessage & from)
Definition at line 2635 of file ZMQMessages.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
int ZMQRequestMessage::ByteSize () const
Definition at line 2783 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, handle(), has_function(), has_handle(), and unknown_fields().
void ZMQRequestMessage::Clear ()
Definition at line 2677 of file ZMQMessages.pb.cc.
References _has_bits_, function_, handle_, and mutable_unknown_fields().
void ZMQRequestMessage::clear_function () inline
Definition at line 1796 of file ZMQMessages.pb.h.
References clear_has_function(), and function_.
void ZMQRequestMessage::clear_handle () inline
Definition at line 1819 of file ZMQMessages.pb.h.
References clear_has_handle(), and handle_.
void ZMQRequestMessage::clear_has_function () inline private
Definition at line 1793 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQRequestMessage::clear_has_handle () inline private
Definition at line 1816 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQRequestMessage::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 2837 of file ZMQMessages.pb.cc.
References Clear(), and MergeFrom().
void ZMQRequestMessage::CopyFrom (const ZMQRequestMessage & from)
Definition at line 2843 of file ZMQMessages.pb.cc.
References Clear(), and MergeFrom().
const ZMQRequestMessage & ZMQRequestMessage::default_instance () static
Definition at line 2667 of file ZMQMessages.pb.cc.
References default_instance_, and protobuf_AddDesc_ZMQMessages_2eproto.
const ::google::protobuf::Descriptor * ZMQRequestMessage::descriptor () static
Definition at line 2662 of file ZMQMessages.pb.cc.
ZMQFunctionType ZMQRequestMessage::function () const inline
Definition at line 1800 of file ZMQMessages.pb.h.
References function_.
int ZMQRequestMessage::GetCachedSize () const inline
Definition at line 890 of file ZMQMessages.pb.h.
References _cached_size_.
google::protobuf::Metadata ZMQRequestMessage::GetMetadata () const
Definition at line 2865 of file ZMQMessages.pb.cc.
google::protobuf::uint64 ZMQRequestMessage::handle () const inline
Definition at line 1823 of file ZMQMessages.pb.h.
References handle_.
bool ZMQRequestMessage::has_function () const inline
Definition at line 1787 of file ZMQMessages.pb.h.
References _has_bits_.
bool ZMQRequestMessage::has_handle () const inline
Definition at line 1810 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQRequestMessage::InitAsDefaultInstance () private
Definition at line 2632 of file ZMQMessages.pb.cc.
bool ZMQRequestMessage::IsInitialized () const
Definition at line 2849 of file ZMQMessages.pb.cc.
References _has_bits_.
void ZMQRequestMessage::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 2812 of file ZMQMessages.pb.cc.
void ZMQRequestMessage::MergeFrom (const ZMQRequestMessage & from)
Definition at line 2824 of file ZMQMessages.pb.cc.
References _has_bits_, function(), handle(), has_function(), has_handle(), mutable_unknown_fields(), set_function(), set_handle(), and unknown_fields().
bool ZMQRequestMessage::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 2686 of file ZMQMessages.pb.cc.
References DO_, handle_, mutable_unknown_fields(), set_function(), set_has_handle(), and ZMQFunctionType_IsValid().
inline ::google::protobuf::UnknownFieldSet* ZMQRequestMessage::mutable_unknown_fields () inline
Definition at line 865 of file ZMQMessages.pb.h.
References _unknown_fields_.
ZMQRequestMessage * ZMQRequestMessage::New () const
Definition at line 2673 of file ZMQMessages.pb.cc.
References ZMQRequestMessage().
ZMQRequestMessage& ZMQRequestMessage::operator= (const ZMQRequestMessage & from) inline
Definition at line 856 of file ZMQMessages.pb.h.
References CopyFrom().
void ZMQRequestMessage::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 2744 of file ZMQMessages.pb.cc.
References handle(), has_function(), has_handle(), and unknown_fields().
google::protobuf::uint8 * ZMQRequestMessage::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 2763 of file ZMQMessages.pb.cc.
References handle(), has_function(), has_handle(), and unknown_fields().
void ZMQRequestMessage::set_function (ZMQFunctionType value) inline
Definition at line 1803 of file ZMQMessages.pb.h.
References function_, set_has_function(), and ZMQFunctionType_IsValid().
void ZMQRequestMessage::set_handle (::google::protobuf::uint64 value) inline
Definition at line 1826 of file ZMQMessages.pb.h.
References handle_, and set_has_handle().
void ZMQRequestMessage::set_has_function () inline private
Definition at line 1790 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQRequestMessage::set_has_handle () inline private
Definition at line 1813 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQRequestMessage::SetCachedSize (int size) const private
Definition at line 2657 of file ZMQMessages.pb.cc.
References _cached_size_.
void ZMQRequestMessage::SharedCtor () private
Definition at line 2641 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, function_, and handle_.
void ZMQRequestMessage::SharedDtor () private
Definition at line 2652 of file ZMQMessages.pb.cc.
References default_instance_.
void ZMQRequestMessage::Swap (ZMQRequestMessage * other)
Definition at line 2855 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, function_, and handle_.
const ::google::protobuf::UnknownFieldSet& ZMQRequestMessage::unknown_fields () const inline
Definition at line 861 of file ZMQMessages.pb.h.
References _unknown_fields_.
Friends And Related Function Documentation
void protobuf_AddDesc_ZMQMessages_2eproto () friend
Definition at line 254 of file ZMQMessages.pb.cc.
void protobuf_AssignDesc_ZMQMessages_2eproto () friend
Definition at line 49 of file ZMQMessages.pb.cc.
void protobuf_ShutdownFile_ZMQMessages_2eproto () friend
Definition at line 235 of file ZMQMessages.pb.cc.
Member Data Documentation
int ZMQRequestMessage::_cached_size_ mutable private
Definition at line 929 of file ZMQMessages.pb.h.
::google::protobuf::uint32 ZMQRequestMessage::_has_bits_[(2+31)/32] private
Definition at line 930 of file ZMQMessages.pb.h.
::google::protobuf::UnknownFieldSet ZMQRequestMessage::_unknown_fields_ private
Definition at line 924 of file ZMQMessages.pb.h.
ZMQRequestMessage * ZMQRequestMessage::default_instance_ = NULL static private
Definition at line 937 of file ZMQMessages.pb.h.
int ZMQRequestMessage::function_ private
Definition at line 927 of file ZMQMessages.pb.h.
::google::protobuf::uint64 ZMQRequestMessage::handle_ private
Definition at line 926 of file ZMQMessages.pb.h.
const int ZMQRequestMessage::kFunctionFieldNumber = 1 static
Definition at line 906 of file ZMQMessages.pb.h.
const int ZMQRequestMessage::kHandleFieldNumber = 2 static
Definition at line 913 of file ZMQMessages.pb.h.
The documentation for this class was generated from the following files:
opencog/persist/zmq/atomspace/ZMQMessages.pb.h
opencog/persist/zmq/atomspace/ZMQMessages.pb.cc