OpenCog Framework: ZMQSingleTruthValueMessage Class Reference
ZMQSingleTruthValueMessage Class Reference
#include <ZMQMessages.pb.h>
Public Member Functions
ZMQSingleTruthValueMessage ()
virtual ~ZMQSingleTruthValueMessage ()
ZMQSingleTruthValueMessage (const ZMQSingleTruthValueMessage &from)
ZMQSingleTruthValueMessage & operator= (const ZMQSingleTruthValueMessage &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (ZMQSingleTruthValueMessage *other)
ZMQSingleTruthValueMessage * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const ZMQSingleTruthValueMessage &from)
void MergeFrom (const ZMQSingleTruthValueMessage &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_truthvaluetype () const
void clear_truthvaluetype ()
ZMQTruthValueType truthvaluetype () const
void set_truthvaluetype (ZMQTruthValueType value)
bool has_mean () const
void clear_mean ()
float mean () const
void set_mean (float value)
bool has_confidence () const
void clear_confidence ()
float confidence () const
void set_confidence (float value)
bool has_count () const
void clear_count ()
float count () const
void set_count (float value)
bool has_versionhandle () const
void clear_versionhandle ()
const ::ZMQVersionHandleMessage & versionhandle () const
inline::ZMQVersionHandleMessage * mutable_versionhandle ()
inline::ZMQVersionHandleMessage * release_versionhandle ()
bool has_u () const
void clear_u ()
float u () const
void set_u (float value)
bool has_l () const
void clear_l ()
float l () const
void set_l (float value)
bool has_confidencelevel () const
void clear_confidencelevel ()
float confidencelevel () const
void set_confidencelevel (float value)
bool has_symmetric () const
void clear_symmetric ()
inline::google::protobuf::int32 symmetric () const
void set_symmetric (::google::protobuf::int32 value)
bool has_diff () const
void clear_diff ()
float diff () const
void set_diff (float value)
int firstorderdistribution_size () const
void clear_firstorderdistribution ()
float firstorderdistribution (int index) const
void set_firstorderdistribution (int index, float value)
void add_firstorderdistribution (float value)
const
::google::protobuf::RepeatedField
< float > & firstorderdistribution () const
inline::google::protobuf::RepeatedField
< float > * mutable_firstorderdistribution ()
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const
ZMQSingleTruthValueMessage & default_instance ()
Static Public Attributes
static const int kTruthvaluetypeFieldNumber = 1
static const int kMeanFieldNumber = 2
static const int kConfidenceFieldNumber = 3
static const int kCountFieldNumber = 4
static const int kVersionHandleFieldNumber = 5
static const int kUFieldNumber = 6
static const int kLFieldNumber = 7
static const int kConfidenceLevelFieldNumber = 8
static const int kSymmetricFieldNumber = 9
static const int kDiffFieldNumber = 10
static const int kFirstOrderDistributionFieldNumber = 11
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_truthvaluetype ()
void clear_has_truthvaluetype ()
void set_has_mean ()
void clear_has_mean ()
void set_has_confidence ()
void clear_has_confidence ()
void set_has_count ()
void clear_has_count ()
void set_has_versionhandle ()
void clear_has_versionhandle ()
void set_has_u ()
void clear_has_u ()
void set_has_l ()
void clear_has_l ()
void set_has_confidencelevel ()
void clear_has_confidencelevel ()
void set_has_symmetric ()
void clear_has_symmetric ()
void set_has_diff ()
void clear_has_diff ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
int truthvaluetype_
float mean_
float confidence_
float count_
::ZMQVersionHandleMessage * versionhandle_
float u_
float l_
float confidencelevel_
::google::protobuf::int32 symmetric_
::google::protobuf::RepeatedField
< float > firstorderdistribution_
float diff_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(11+31)/32]
Static Private Attributes
static ZMQSingleTruthValueMessage * default_instance_ = NULL
Friends
void protobuf_AddDesc_ZMQMessages_2eproto ()
void protobuf_AssignDesc_ZMQMessages_2eproto ()
void protobuf_ShutdownFile_ZMQMessages_2eproto ()
Detailed Description
Definition at line 298 of file ZMQMessages.pb.h.
Constructor & Destructor Documentation
ZMQSingleTruthValueMessage::ZMQSingleTruthValueMessage ()
Definition at line 919 of file ZMQMessages.pb.cc.
References SharedCtor().
ZMQSingleTruthValueMessage::~ZMQSingleTruthValueMessage () virtual
Definition at line 949 of file ZMQMessages.pb.cc.
References SharedDtor().
ZMQSingleTruthValueMessage::ZMQSingleTruthValueMessage (const ZMQSingleTruthValueMessage & from)
Definition at line 928 of file ZMQMessages.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
void ZMQSingleTruthValueMessage::add_firstorderdistribution (float value) inline
Definition at line 1402 of file ZMQMessages.pb.h.
References firstorderdistribution_.
int ZMQSingleTruthValueMessage::ByteSize () const
Definition at line 1341 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, firstorderdistribution_size(), has_confidence(), has_confidencelevel(), has_count(), has_diff(), has_l(), has_mean(), has_symmetric(), has_truthvaluetype(), has_u(), has_versionhandle(), symmetric(), truthvaluetype(), unknown_fields(), and versionhandle().
void ZMQSingleTruthValueMessage::Clear ()
Definition at line 979 of file ZMQMessages.pb.cc.
References _has_bits_, confidence_, confidencelevel_, count_, diff_, firstorderdistribution_, has_versionhandle(), l_, mean_, mutable_unknown_fields(), symmetric_, truthvaluetype_, u_, and versionhandle_.
void ZMQSingleTruthValueMessage::clear_confidence () inline
Definition at line 1216 of file ZMQMessages.pb.h.
References clear_has_confidence(), and confidence_.
void ZMQSingleTruthValueMessage::clear_confidencelevel () inline
Definition at line 1333 of file ZMQMessages.pb.h.
References clear_has_confidencelevel(), and confidencelevel_.
void ZMQSingleTruthValueMessage::clear_count () inline
Definition at line 1238 of file ZMQMessages.pb.h.
References clear_has_count(), and count_.
void ZMQSingleTruthValueMessage::clear_diff () inline
Definition at line 1377 of file ZMQMessages.pb.h.
References clear_has_diff(), and diff_.
void ZMQSingleTruthValueMessage::clear_firstorderdistribution () inline
Definition at line 1393 of file ZMQMessages.pb.h.
References firstorderdistribution_.
void ZMQSingleTruthValueMessage::clear_has_confidence () inline private
Definition at line 1213 of file ZMQMessages.pb.h.
References _has_bits_, and u().
void ZMQSingleTruthValueMessage::clear_has_confidencelevel () inline private
Definition at line 1330 of file ZMQMessages.pb.h.
References _has_bits_, and u().
void ZMQSingleTruthValueMessage::clear_has_count () inline private
Definition at line 1235 of file ZMQMessages.pb.h.
References _has_bits_, and u().
void ZMQSingleTruthValueMessage::clear_has_diff () inline private
Definition at line 1374 of file ZMQMessages.pb.h.
References _has_bits_, and u().
void ZMQSingleTruthValueMessage::clear_has_l () inline private
Definition at line 1308 of file ZMQMessages.pb.h.
References _has_bits_, and u().
void ZMQSingleTruthValueMessage::clear_has_mean () inline private
Definition at line 1191 of file ZMQMessages.pb.h.
References _has_bits_, and u().
void ZMQSingleTruthValueMessage::clear_has_symmetric () inline private
Definition at line 1352 of file ZMQMessages.pb.h.
References _has_bits_, and u().
void ZMQSingleTruthValueMessage::clear_has_truthvaluetype () inline private
Definition at line 1168 of file ZMQMessages.pb.h.
References _has_bits_, and u().
void ZMQSingleTruthValueMessage::clear_has_u () inline private
Definition at line 1286 of file ZMQMessages.pb.h.
References _has_bits_, and u().
void ZMQSingleTruthValueMessage::clear_has_versionhandle () inline private
Definition at line 1257 of file ZMQMessages.pb.h.
References _has_bits_, and u().
void ZMQSingleTruthValueMessage::clear_l () inline
Definition at line 1311 of file ZMQMessages.pb.h.
References clear_has_l(), and l_.
void ZMQSingleTruthValueMessage::clear_mean () inline
Definition at line 1194 of file ZMQMessages.pb.h.
References clear_has_mean(), and mean_.
void ZMQSingleTruthValueMessage::clear_symmetric () inline
Definition at line 1355 of file ZMQMessages.pb.h.
References clear_has_symmetric(), and symmetric_.
void ZMQSingleTruthValueMessage::clear_truthvaluetype () inline
Definition at line 1171 of file ZMQMessages.pb.h.
References clear_has_truthvaluetype(), and truthvaluetype_.
void ZMQSingleTruthValueMessage::clear_u () inline
Definition at line 1289 of file ZMQMessages.pb.h.
References clear_has_u(), and u_.
void ZMQSingleTruthValueMessage::clear_versionhandle () inline
Definition at line 1260 of file ZMQMessages.pb.h.
References clear_has_versionhandle(), and versionhandle_.
float ZMQSingleTruthValueMessage::confidence () const inline
Definition at line 1220 of file ZMQMessages.pb.h.
References confidence_.
float ZMQSingleTruthValueMessage::confidencelevel () const inline
Definition at line 1337 of file ZMQMessages.pb.h.
References confidencelevel_.
void ZMQSingleTruthValueMessage::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 1473 of file ZMQMessages.pb.cc.
References Clear(), and MergeFrom().
void ZMQSingleTruthValueMessage::CopyFrom (const ZMQSingleTruthValueMessage & from)
Definition at line 1479 of file ZMQMessages.pb.cc.
References Clear(), and MergeFrom().
float ZMQSingleTruthValueMessage::count () const inline
Definition at line 1242 of file ZMQMessages.pb.h.
References count_.
const ZMQSingleTruthValueMessage & ZMQSingleTruthValueMessage::default_instance () static
Definition at line 969 of file ZMQMessages.pb.cc.
References default_instance_, and protobuf_AddDesc_ZMQMessages_2eproto.
const ::google::protobuf::Descriptor * ZMQSingleTruthValueMessage::descriptor () static
Definition at line 964 of file ZMQMessages.pb.cc.
float ZMQSingleTruthValueMessage::diff () const inline
Definition at line 1381 of file ZMQMessages.pb.h.
References diff_.
float ZMQSingleTruthValueMessage::firstorderdistribution (int index) const inline
Definition at line 1396 of file ZMQMessages.pb.h.
References firstorderdistribution_.
const ::google::protobuf::RepeatedField< float > & ZMQSingleTruthValueMessage::firstorderdistribution () const inline
Definition at line 1406 of file ZMQMessages.pb.h.
References firstorderdistribution_.
int ZMQSingleTruthValueMessage::firstorderdistribution_size () const inline
Definition at line 1390 of file ZMQMessages.pb.h.
References firstorderdistribution_.
int ZMQSingleTruthValueMessage::GetCachedSize () const inline
Definition at line 339 of file ZMQMessages.pb.h.
References _cached_size_.
google::protobuf::Metadata ZMQSingleTruthValueMessage::GetMetadata () const
Definition at line 1513 of file ZMQMessages.pb.cc.
bool ZMQSingleTruthValueMessage::has_confidence () const inline
Definition at line 1207 of file ZMQMessages.pb.h.
References _has_bits_.
bool ZMQSingleTruthValueMessage::has_confidencelevel () const inline
Definition at line 1324 of file ZMQMessages.pb.h.
References _has_bits_.
bool ZMQSingleTruthValueMessage::has_count () const inline
Definition at line 1229 of file ZMQMessages.pb.h.
References _has_bits_.
bool ZMQSingleTruthValueMessage::has_diff () const inline
Definition at line 1368 of file ZMQMessages.pb.h.
References _has_bits_.
bool ZMQSingleTruthValueMessage::has_l () const inline
Definition at line 1302 of file ZMQMessages.pb.h.
References _has_bits_.
bool ZMQSingleTruthValueMessage::has_mean () const inline
Definition at line 1185 of file ZMQMessages.pb.h.
References _has_bits_.
bool ZMQSingleTruthValueMessage::has_symmetric () const inline
Definition at line 1346 of file ZMQMessages.pb.h.
References _has_bits_.
bool ZMQSingleTruthValueMessage::has_truthvaluetype () const inline
Definition at line 1162 of file ZMQMessages.pb.h.
References _has_bits_.
bool ZMQSingleTruthValueMessage::has_u () const inline
Definition at line 1280 of file ZMQMessages.pb.h.
References _has_bits_.
bool ZMQSingleTruthValueMessage::has_versionhandle () const inline
Definition at line 1251 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQSingleTruthValueMessage::InitAsDefaultInstance () private
Definition at line 924 of file ZMQMessages.pb.cc.
References ZMQVersionHandleMessage::default_instance(), and versionhandle_.
bool ZMQSingleTruthValueMessage::IsInitialized () const
Definition at line 1485 of file ZMQMessages.pb.cc.
References _has_bits_, has_versionhandle(), and versionhandle().
float ZMQSingleTruthValueMessage::l () const inline
Definition at line 1315 of file ZMQMessages.pb.h.
References l_.
float ZMQSingleTruthValueMessage::mean () const inline
Definition at line 1198 of file ZMQMessages.pb.h.
References mean_.
void ZMQSingleTruthValueMessage::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 1421 of file ZMQMessages.pb.cc.
void ZMQSingleTruthValueMessage::MergeFrom (const ZMQSingleTruthValueMessage & from)
Definition at line 1433 of file ZMQMessages.pb.cc.
References _has_bits_, confidence(), confidencelevel(), count(), diff(), firstorderdistribution_, has_confidence(), has_confidencelevel(), has_count(), has_diff(), has_l(), has_mean(), has_symmetric(), has_truthvaluetype(), has_u(), has_versionhandle(), l(), mean(), mutable_unknown_fields(), mutable_versionhandle(), set_confidence(), set_confidencelevel(), set_count(), set_diff(), set_l(), set_mean(), set_symmetric(), set_truthvaluetype(), set_u(), symmetric(), truthvaluetype(), u(), unknown_fields(), and versionhandle().
bool ZMQSingleTruthValueMessage::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 1001 of file ZMQMessages.pb.cc.
References confidence_, confidencelevel_, count_, diff_, DO_, l_, mean_, mutable_firstorderdistribution(), mutable_unknown_fields(), mutable_versionhandle(), set_has_confidence(), set_has_confidencelevel(), set_has_count(), set_has_diff(), set_has_l(), set_has_mean(), set_has_symmetric(), set_has_u(), set_truthvaluetype(), symmetric_, u_, and ZMQTruthValueType_IsValid().
google::protobuf::RepeatedField< float > * ZMQSingleTruthValueMessage::mutable_firstorderdistribution () inline
Definition at line 1410 of file ZMQMessages.pb.h.
References firstorderdistribution_.
inline ::google::protobuf::UnknownFieldSet* ZMQSingleTruthValueMessage::mutable_unknown_fields () inline
Definition at line 314 of file ZMQMessages.pb.h.
References _unknown_fields_.
ZMQVersionHandleMessage * ZMQSingleTruthValueMessage::mutable_versionhandle () inline
Definition at line 1267 of file ZMQMessages.pb.h.
References set_has_versionhandle(), and versionhandle_.
ZMQSingleTruthValueMessage * ZMQSingleTruthValueMessage::New () const
Definition at line 975 of file ZMQMessages.pb.cc.
References ZMQSingleTruthValueMessage().
ZMQSingleTruthValueMessage& ZMQSingleTruthValueMessage::operator= (const ZMQSingleTruthValueMessage & from) inline
Definition at line 305 of file ZMQMessages.pb.h.
References CopyFrom().
ZMQVersionHandleMessage * ZMQSingleTruthValueMessage::release_versionhandle () inline
Definition at line 1272 of file ZMQMessages.pb.h.
References clear_has_versionhandle(), and versionhandle_.
void ZMQSingleTruthValueMessage::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 1207 of file ZMQMessages.pb.cc.
References confidence(), confidencelevel(), count(), diff(), firstorderdistribution(), firstorderdistribution_size(), has_confidence(), has_confidencelevel(), has_count(), has_diff(), has_l(), has_mean(), has_symmetric(), has_truthvaluetype(), has_u(), has_versionhandle(), l(), mean(), symmetric(), truthvaluetype(), u(), unknown_fields(), and versionhandle().
google::protobuf::uint8 * ZMQSingleTruthValueMessage::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 1273 of file ZMQMessages.pb.cc.
References confidence(), confidencelevel(), count(), diff(), firstorderdistribution(), firstorderdistribution_size(), has_confidence(), has_confidencelevel(), has_count(), has_diff(), has_l(), has_mean(), has_symmetric(), has_truthvaluetype(), has_u(), has_versionhandle(), l(), mean(), symmetric(), truthvaluetype(), u(), unknown_fields(), and versionhandle().
void ZMQSingleTruthValueMessage::set_confidence (float value) inline
Definition at line 1223 of file ZMQMessages.pb.h.
References confidence_, and set_has_confidence().
void ZMQSingleTruthValueMessage::set_confidencelevel (float value) inline
Definition at line 1340 of file ZMQMessages.pb.h.
References confidencelevel_, and set_has_confidencelevel().
void ZMQSingleTruthValueMessage::set_count (float value) inline
Definition at line 1245 of file ZMQMessages.pb.h.
References count_, and set_has_count().
void ZMQSingleTruthValueMessage::set_diff (float value) inline
Definition at line 1384 of file ZMQMessages.pb.h.
References diff_, and set_has_diff().
void ZMQSingleTruthValueMessage::set_firstorderdistribution (int index, float value) inline
Definition at line 1399 of file ZMQMessages.pb.h.
References firstorderdistribution_.
void ZMQSingleTruthValueMessage::set_has_confidence () inline private
Definition at line 1210 of file ZMQMessages.pb.h.
References _has_bits_, and u().
void ZMQSingleTruthValueMessage::set_has_confidencelevel () inline private
Definition at line 1327 of file ZMQMessages.pb.h.
References _has_bits_, and u().
void ZMQSingleTruthValueMessage::set_has_count () inline private
Definition at line 1232 of file ZMQMessages.pb.h.
References _has_bits_, and u().
void ZMQSingleTruthValueMessage::set_has_diff () inline private
Definition at line 1371 of file ZMQMessages.pb.h.
References _has_bits_, and u().
void ZMQSingleTruthValueMessage::set_has_l () inline private
Definition at line 1305 of file ZMQMessages.pb.h.
References _has_bits_, and u().
void ZMQSingleTruthValueMessage::set_has_mean () inline private
Definition at line 1188 of file ZMQMessages.pb.h.
References _has_bits_, and u().
void ZMQSingleTruthValueMessage::set_has_symmetric () inline private
Definition at line 1349 of file ZMQMessages.pb.h.
References _has_bits_, and u().
void ZMQSingleTruthValueMessage::set_has_truthvaluetype () inline private
Definition at line 1165 of file ZMQMessages.pb.h.
References _has_bits_, and u().
void ZMQSingleTruthValueMessage::set_has_u () inline private
Definition at line 1283 of file ZMQMessages.pb.h.
References _has_bits_, and u().
void ZMQSingleTruthValueMessage::set_has_versionhandle () inline private
Definition at line 1254 of file ZMQMessages.pb.h.
References _has_bits_, and u().
void ZMQSingleTruthValueMessage::set_l (float value) inline
Definition at line 1318 of file ZMQMessages.pb.h.
References l_, and set_has_l().
void ZMQSingleTruthValueMessage::set_mean (float value) inline
Definition at line 1201 of file ZMQMessages.pb.h.
References mean_, and set_has_mean().
void ZMQSingleTruthValueMessage::set_symmetric (::google::protobuf::int32 value) inline
Definition at line 1362 of file ZMQMessages.pb.h.
References set_has_symmetric(), and symmetric_.
void ZMQSingleTruthValueMessage::set_truthvaluetype (ZMQTruthValueType value) inline
Definition at line 1178 of file ZMQMessages.pb.h.
References set_has_truthvaluetype(), truthvaluetype_, and ZMQTruthValueType_IsValid().
void ZMQSingleTruthValueMessage::set_u (float value) inline
Definition at line 1296 of file ZMQMessages.pb.h.
References set_has_u(), and u_.
void ZMQSingleTruthValueMessage::SetCachedSize (int size) const private
Definition at line 959 of file ZMQMessages.pb.cc.
References _cached_size_.
void ZMQSingleTruthValueMessage::SharedCtor () private
Definition at line 934 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, confidence_, confidencelevel_, count_, diff_, l_, mean_, symmetric_, truthvaluetype_, u_, and versionhandle_.
void ZMQSingleTruthValueMessage::SharedDtor () private
Definition at line 953 of file ZMQMessages.pb.cc.
References default_instance_, and versionhandle_.
void ZMQSingleTruthValueMessage::Swap (ZMQSingleTruthValueMessage * other)
Definition at line 1494 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, confidence_, confidencelevel_, count_, diff_, firstorderdistribution_, l_, mean_, symmetric_, truthvaluetype_, u_, and versionhandle_.
google::protobuf::int32 ZMQSingleTruthValueMessage::symmetric () const inline
Definition at line 1359 of file ZMQMessages.pb.h.
References symmetric_.
ZMQTruthValueType ZMQSingleTruthValueMessage::truthvaluetype () const inline
Definition at line 1175 of file ZMQMessages.pb.h.
References truthvaluetype_.
float ZMQSingleTruthValueMessage::u () const inline
Definition at line 1293 of file ZMQMessages.pb.h.
References u_.
const ::google::protobuf::UnknownFieldSet& ZMQSingleTruthValueMessage::unknown_fields () const inline
Definition at line 310 of file ZMQMessages.pb.h.
References _unknown_fields_.
const ::ZMQVersionHandleMessage & ZMQSingleTruthValueMessage::versionhandle () const inline
Definition at line 1264 of file ZMQMessages.pb.h.
References default_instance_, and versionhandle_.
Friends And Related Function Documentation
void protobuf_AddDesc_ZMQMessages_2eproto () friend
Definition at line 254 of file ZMQMessages.pb.cc.
void protobuf_AssignDesc_ZMQMessages_2eproto () friend
Definition at line 49 of file ZMQMessages.pb.cc.
void protobuf_ShutdownFile_ZMQMessages_2eproto () friend
Definition at line 235 of file ZMQMessages.pb.cc.
Member Data Documentation
int ZMQSingleTruthValueMessage::_cached_size_ mutable private
Definition at line 472 of file ZMQMessages.pb.h.
::google::protobuf::uint32 ZMQSingleTruthValueMessage::_has_bits_[(11+31)/32] private
Definition at line 473 of file ZMQMessages.pb.h.
::google::protobuf::UnknownFieldSet ZMQSingleTruthValueMessage::_unknown_fields_ private
Definition at line 458 of file ZMQMessages.pb.h.
float ZMQSingleTruthValueMessage::confidence_ private
Definition at line 462 of file ZMQMessages.pb.h.
float ZMQSingleTruthValueMessage::confidencelevel_ private
Definition at line 467 of file ZMQMessages.pb.h.
float ZMQSingleTruthValueMessage::count_ private
Definition at line 463 of file ZMQMessages.pb.h.
ZMQSingleTruthValueMessage * ZMQSingleTruthValueMessage::default_instance_ = NULL static private
Definition at line 480 of file ZMQMessages.pb.h.
float ZMQSingleTruthValueMessage::diff_ private
Definition at line 470 of file ZMQMessages.pb.h.
::google::protobuf::RepeatedField< float > ZMQSingleTruthValueMessage::firstorderdistribution_ private
Definition at line 469 of file ZMQMessages.pb.h.
const int ZMQSingleTruthValueMessage::kConfidenceFieldNumber = 3 static
Definition at line 369 of file ZMQMessages.pb.h.
const int ZMQSingleTruthValueMessage::kConfidenceLevelFieldNumber = 8 static
Definition at line 405 of file ZMQMessages.pb.h.
const int ZMQSingleTruthValueMessage::kCountFieldNumber = 4 static
Definition at line 376 of file ZMQMessages.pb.h.
const int ZMQSingleTruthValueMessage::kDiffFieldNumber = 10 static
Definition at line 419 of file ZMQMessages.pb.h.
const int ZMQSingleTruthValueMessage::kFirstOrderDistributionFieldNumber = 11 static
Definition at line 426 of file ZMQMessages.pb.h.
const int ZMQSingleTruthValueMessage::kLFieldNumber = 7 static
Definition at line 398 of file ZMQMessages.pb.h.
const int ZMQSingleTruthValueMessage::kMeanFieldNumber = 2 static
Definition at line 362 of file ZMQMessages.pb.h.
const int ZMQSingleTruthValueMessage::kSymmetricFieldNumber = 9 static
Definition at line 412 of file ZMQMessages.pb.h.
const int ZMQSingleTruthValueMessage::kTruthvaluetypeFieldNumber = 1 static
Definition at line 355 of file ZMQMessages.pb.h.
const int ZMQSingleTruthValueMessage::kUFieldNumber = 6 static
Definition at line 391 of file ZMQMessages.pb.h.
const int ZMQSingleTruthValueMessage::kVersionHandleFieldNumber = 5 static
Definition at line 383 of file ZMQMessages.pb.h.
float ZMQSingleTruthValueMessage::l_ private
Definition at line 466 of file ZMQMessages.pb.h.
float ZMQSingleTruthValueMessage::mean_ private
Definition at line 461 of file ZMQMessages.pb.h.
::google::protobuf::int32 ZMQSingleTruthValueMessage::symmetric_ private
Definition at line 468 of file ZMQMessages.pb.h.
int ZMQSingleTruthValueMessage::truthvaluetype_ private
Definition at line 460 of file ZMQMessages.pb.h.
float ZMQSingleTruthValueMessage::u_ private
Definition at line 465 of file ZMQMessages.pb.h.
::ZMQVersionHandleMessage* ZMQSingleTruthValueMessage::versionhandle_ private
Definition at line 464 of file ZMQMessages.pb.h.
The documentation for this class was generated from the following files:
opencog/persist/zmq/atomspace/ZMQMessages.pb.h
opencog/persist/zmq/atomspace/ZMQMessages.pb.cc