OpenCog Framework: viz_graph.Viz_Graph Class Reference
viz_graph.Viz_Graph Class Reference
Public Member Functions
def __init__
def add_edge
def add_edge_unique
def unique_id
def reset_unique
def add_node
def output_node
def output_edge
def neighbors
def set_node_attr
def get_node_attr
def set_edge_attr
def get_edge_attr
def number_of_nodes
def write
def clear
Public Attributes
viz
no_nodes
Private Attributes
_nx_graph
Detailed Description
a wrapper to networkx, which work as a graph drawer
Definition at line 187 of file viz_graph.py.
Constructor & Destructor Documentation
def viz_graph.Viz_Graph.__init__ (self, viz = Dotty_Output())
Definition at line 189 of file viz_graph.py.
Member Function Documentation
def viz_graph.Viz_Graph.add_edge (self, source, target, attr)
Definition at line 194 of file viz_graph.py.
References viz_graph.Viz_Graph.set_edge_attr().
def viz_graph.Viz_Graph.add_edge_unique (self, source, target, attr)
docstring for add_edge_unique
Definition at line 199 of file viz_graph.py.
References viz_graph.Viz_Graph.add_edge(), and viz_graph.Viz_Graph.unique_id().
def viz_graph.Viz_Graph.add_node (self, node_id, attr)
Definition at line 221 of file viz_graph.py.
def viz_graph.Viz_Graph.clear (self)
docstring for clear
Definition at line 292 of file viz_graph.py.
References viz_graph.Viz_Graph.reset_unique().
def viz_graph.Viz_Graph.get_edge_attr (self, source, target)
Definition at line 251 of file viz_graph.py.
References viz_graph.Viz_Graph._nx_graph.
def viz_graph.Viz_Graph.get_node_attr (self, node_id)
Definition at line 244 of file viz_graph.py.
def viz_graph.Viz_Graph.neighbors (self, node_id)
return a list of node's neighbors
Definition at line 236 of file viz_graph.py.
def viz_graph.Viz_Graph.number_of_nodes (self)
docstring for number_of_nodes
Definition at line 254 of file viz_graph.py.
def viz_graph.Viz_Graph.output_edge (self, edge_id, source, target)
docstring for output_edge
Definition at line 231 of file viz_graph.py.
References viz_graph.Viz_Graph.viz.
def viz_graph.Viz_Graph.output_node (self, node_id)
docstring for output_node
Definition at line 226 of file viz_graph.py.
References viz_graph.Viz_Graph.viz.
def viz_graph.Viz_Graph.reset_unique (self)
docstring for reset_unique_no
Definition at line 217 of file viz_graph.py.
def viz_graph.Viz_Graph.set_edge_attr (self, source, target, attr)
Definition at line 247 of file viz_graph.py.
References viz_graph.Viz_Graph._nx_graph.
def viz_graph.Viz_Graph.set_node_attr (self, node_id, attr)
Definition at line 240 of file viz_graph.py.
def viz_graph.Viz_Graph.unique_id (self, node)
supposed to added this node later
Definition at line 207 of file viz_graph.py.
References viz_graph.Viz_Graph.no_nodes.
def viz_graph.Viz_Graph.write (self, filename)
draw the graph
Definition at line 258 of file viz_graph.py.
References viz_graph.Viz_Graph.viz.
Member Data Documentation
viz_graph.Viz_Graph._nx_graph private
Definition at line 190 of file viz_graph.py.
viz_graph.Viz_Graph.no_nodes
Definition at line 192 of file viz_graph.py.
viz_graph.Viz_Graph.viz
Definition at line 191 of file viz_graph.py.
The documentation for this class was generated from the following file:
examples/python/untested/viz_graph.py