OpenCog Framework: benchmark Namespace Reference
benchmark Namespace Reference
Classes
class SmartFormatter
Functions
def loop_time_per_op
def prep_none
def prep_traverse_10K
def prep_traverse_100K
def prep_traverse_1M
def prep_get_100K
def prep_get_outgoing
def prep_scheme
def prep_bind
def prep_bind_python
def prep_bind_scheme
def prep_predicates
def test_add_nodes
def test_add_nodes_large
def test_add_connected
def test_bare_traversal
def test_resolve_traversal
def test_get_traverse
def test_xget_traverse
def test_get_outgoing
def test_get_outgoing_no_list
def test_xget_outgoing
def test_stub_bindlink
def test_bind
def test_scheme_eval
def test_bind_scheme
def test_add_nodes_scheme
def test_add_nodes_sugar
def test_get_predicates
def test_get_predicates_for
def test_get_predicates_scheme
def do_test
Variables
string __authors__ = 'Cosmo Harrigan, Curtis Faith'
tuple parser
tuple verbosity_group = parser.add_mutually_exclusive_group()
tuple test_group = parser.add_mutually_exclusive_group()
list choices = ['spread','node', 'bindlink', 'traverse', 'scheme', 'get_vs_xget', 'predicates']
string help = "R|Test to benchmark, where:\n"
tuple args = parser.parse_args()
test_iterations = args.iterations
list scheme_preload
list tests
tuple op_time_adjustment = loop_time_per_op()
Function Documentation
def benchmark.do_test (prep, test, description, op_time_adjustment)
Runs tests and prints the test name and performance
Definition at line 417 of file benchmark.py.
def benchmark.loop_time_per_op ()
Definition at line 92 of file benchmark.py.
def benchmark.prep_bind (atomspace)
Definition at line 155 of file benchmark.py.
def benchmark.prep_bind_python (atomspace)
Definition at line 170 of file benchmark.py.
References prep_bind().
def benchmark.prep_bind_scheme (atomspace)
Definition at line 190 of file benchmark.py.
References prep_bind().
def benchmark.prep_get_100K (atomspace)
Add n nodes in atomspace with python bindings
Definition at line 127 of file benchmark.py.
def benchmark.prep_get_outgoing (atomspace)
Add n nodes and create a complete (fully-connected) graph in atomspace
and returns the number of items processed
Definition at line 134 of file benchmark.py.
def benchmark.prep_none (atomspace)
Definition at line 103 of file benchmark.py.
def benchmark.prep_predicates (atomspace)
Definition at line 213 of file benchmark.py.
def benchmark.prep_scheme (atomspace)
Definition at line 152 of file benchmark.py.
def benchmark.prep_traverse_100K (atomspace)
Add n nodes in atomspace with python bindings
Definition at line 113 of file benchmark.py.
def benchmark.prep_traverse_10K (atomspace)
Add n nodes in atomspace with python bindings
Definition at line 106 of file benchmark.py.
def benchmark.prep_traverse_1M (atomspace)
Add n nodes in atomspace with python bindings
Definition at line 120 of file benchmark.py.
def benchmark.test_add_connected (atomspace, prep_handle)
Add n nodes and create a complete (fully-connected) graph in atomspace
and returns the number of items processed
Definition at line 264 of file benchmark.py.
def benchmark.test_add_nodes (atomspace, prep_handle)
Add n nodes in atomspace with python bindings
Definition at line 250 of file benchmark.py.
def benchmark.test_add_nodes_large (atomspace, prep_handle)
Add n nodes in atomspace with python bindings
Definition at line 257 of file benchmark.py.
def benchmark.test_add_nodes_scheme (atomspace, prep_handle)
Add n nodes in atomspace using scheme
Definition at line 375 of file benchmark.py.
def benchmark.test_add_nodes_sugar (atomspace, prep_handle)
Add n nodes in atomspace using scheme with syntactic sugar
Definition at line 384 of file benchmark.py.
def benchmark.test_bare_traversal (atomspace, prep_traverse_result)
Definition at line 284 of file benchmark.py.
def benchmark.test_bind (atomspace, prep_handle)
Definition at line 354 of file benchmark.py.
References opencog.bindlink().
def benchmark.test_bind_scheme (atomspace, prep_handle)
Definition at line 369 of file benchmark.py.
def benchmark.test_get_outgoing (atomspace, prep_result)
Definition at line 319 of file benchmark.py.
def benchmark.test_get_outgoing_no_list (atomspace, prep_result)
Definition at line 329 of file benchmark.py.
def benchmark.test_get_predicates (atomspace, prep_result)
Definition at line 393 of file benchmark.py.
def benchmark.test_get_predicates_for (atomspace, prep_result)
Definition at line 400 of file benchmark.py.
def benchmark.test_get_predicates_scheme (atomspace, prep_result)
Definition at line 407 of file benchmark.py.
def benchmark.test_get_traverse (atomspace, prep_result)
Definition at line 302 of file benchmark.py.
def benchmark.test_resolve_traversal (atomspace, prep_traverse_result)
Definition at line 292 of file benchmark.py.
def benchmark.test_scheme_eval (atomspace, prep_handle)
Definition at line 363 of file benchmark.py.
def benchmark.test_stub_bindlink (atomspace, prep_handle)
Definition at line 348 of file benchmark.py.
References opencog.stub_bindlink().
def benchmark.test_xget_outgoing (atomspace, prep_result)
Definition at line 337 of file benchmark.py.
def benchmark.test_xget_traverse (atomspace, prep_result)
Definition at line 311 of file benchmark.py.
Variable Documentation
string benchmark.__authors__ = 'Cosmo Harrigan, Curtis Faith'
Definition at line 49 of file benchmark.py.
tuple benchmark.args = parser.parse_args()
Definition at line 79 of file benchmark.py.
list benchmark.choices = ['spread','node', 'bindlink', 'traverse', 'scheme', 'get_vs_xget', 'predicates']
Definition at line 69 of file benchmark.py.
string benchmark.help = "R|Test to benchmark, where:\n"
Definition at line 70 of file benchmark.py.
tuple benchmark.op_time_adjustment = loop_time_per_op()
Definition at line 505 of file benchmark.py.
tuple benchmark.parser
Initial value:
 = argparse.ArgumentParser(description="OpenCog Python Benchmark",
         formatter_class=SmartFormatter)
Definition at line 60 of file benchmark.py.
list benchmark.scheme_preload
Initial value:
 = [
                     "opencog/atomspace/core_types.scm",
                     "opencog/scm/utilities.scm"
                  ]
Definition at line 87 of file benchmark.py.
tuple benchmark.test_group = parser.add_mutually_exclusive_group()
Definition at line 66 of file benchmark.py.
benchmark.test_iterations = args.iterations
Definition at line 85 of file benchmark.py.
list benchmark.tests
Definition at line 464 of file benchmark.py.
tuple benchmark.verbosity_group = parser.add_mutually_exclusive_group()
Definition at line 62 of file benchmark.py.