OpenCog Framework: ZMQAttentionValueHolderMessage Class Reference
ZMQAttentionValueHolderMessage Class Reference
#include <ZMQMessages.pb.h>
Public Member Functions
ZMQAttentionValueHolderMessage ()
virtual ~ZMQAttentionValueHolderMessage ()
ZMQAttentionValueHolderMessage (const ZMQAttentionValueHolderMessage &from)
ZMQAttentionValueHolderMessage & operator= (const ZMQAttentionValueHolderMessage &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (ZMQAttentionValueHolderMessage *other)
ZMQAttentionValueHolderMessage * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const ZMQAttentionValueHolderMessage &from)
void MergeFrom (const ZMQAttentionValueHolderMessage &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_sti () const
void clear_sti ()
inline::google::protobuf::int32 sti () const
void set_sti (::google::protobuf::int32 value)
bool has_lti () const
void clear_lti ()
inline::google::protobuf::int32 lti () const
void set_lti (::google::protobuf::int32 value)
bool has_vlti () const
void clear_vlti ()
inline::google::protobuf::int32 vlti () const
void set_vlti (::google::protobuf::int32 value)
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const
ZMQAttentionValueHolderMessage & default_instance ()
Static Public Attributes
static const int kSTIFieldNumber = 1
static const int kLTIFieldNumber = 2
static const int kVLTIFieldNumber = 3
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_sti ()
void clear_has_sti ()
void set_has_lti ()
void clear_has_lti ()
void set_has_vlti ()
void clear_has_vlti ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::google::protobuf::int32 sti_
::google::protobuf::int32 lti_
::google::protobuf::int32 vlti_
int _cached_size_
::google::protobuf::uint32 _has_bits_ [(3+31)/32]
Static Private Attributes
static
ZMQAttentionValueHolderMessage * default_instance_ = NULL
Friends
void protobuf_AddDesc_ZMQMessages_2eproto ()
void protobuf_AssignDesc_ZMQMessages_2eproto ()
void protobuf_ShutdownFile_ZMQMessages_2eproto ()
Detailed Description
Definition at line 104 of file ZMQMessages.pb.h.
Constructor & Destructor Documentation
ZMQAttentionValueHolderMessage::ZMQAttentionValueHolderMessage ()
Definition at line 375 of file ZMQMessages.pb.cc.
References SharedCtor().
ZMQAttentionValueHolderMessage::~ZMQAttentionValueHolderMessage () virtual
Definition at line 397 of file ZMQMessages.pb.cc.
References SharedDtor().
ZMQAttentionValueHolderMessage::ZMQAttentionValueHolderMessage (const ZMQAttentionValueHolderMessage & from)
Definition at line 383 of file ZMQMessages.pb.cc.
References MergeFrom(), and SharedCtor().
Member Function Documentation
int ZMQAttentionValueHolderMessage::ByteSize () const
Definition at line 552 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, has_lti(), has_sti(), has_vlti(), lti(), sti(), unknown_fields(), and vlti().
void ZMQAttentionValueHolderMessage::Clear ()
Definition at line 426 of file ZMQMessages.pb.cc.
References _has_bits_, lti_, mutable_unknown_fields(), sti_, and vlti_.
void ZMQAttentionValueHolderMessage::clear_has_lti () inline private
Definition at line 1072 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAttentionValueHolderMessage::clear_has_sti () inline private
Definition at line 1050 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAttentionValueHolderMessage::clear_has_vlti () inline private
Definition at line 1094 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAttentionValueHolderMessage::clear_lti () inline
Definition at line 1075 of file ZMQMessages.pb.h.
References clear_has_lti(), and lti_.
void ZMQAttentionValueHolderMessage::clear_sti () inline
Definition at line 1053 of file ZMQMessages.pb.h.
References clear_has_sti(), and sti_.
void ZMQAttentionValueHolderMessage::clear_vlti () inline
Definition at line 1097 of file ZMQMessages.pb.h.
References clear_has_vlti(), and vlti_.
void ZMQAttentionValueHolderMessage::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 617 of file ZMQMessages.pb.cc.
References Clear(), and MergeFrom().
void ZMQAttentionValueHolderMessage::CopyFrom (const ZMQAttentionValueHolderMessage & from)
Definition at line 623 of file ZMQMessages.pb.cc.
References Clear(), and MergeFrom().
const ZMQAttentionValueHolderMessage & ZMQAttentionValueHolderMessage::default_instance () static
Definition at line 416 of file ZMQMessages.pb.cc.
References default_instance_, and protobuf_AddDesc_ZMQMessages_2eproto.
const ::google::protobuf::Descriptor * ZMQAttentionValueHolderMessage::descriptor () static
Definition at line 411 of file ZMQMessages.pb.cc.
int ZMQAttentionValueHolderMessage::GetCachedSize () const inline
Definition at line 145 of file ZMQMessages.pb.h.
References _cached_size_.
google::protobuf::Metadata ZMQAttentionValueHolderMessage::GetMetadata () const
Definition at line 646 of file ZMQMessages.pb.cc.
bool ZMQAttentionValueHolderMessage::has_lti () const inline
Definition at line 1066 of file ZMQMessages.pb.h.
References _has_bits_.
bool ZMQAttentionValueHolderMessage::has_sti () const inline
Definition at line 1044 of file ZMQMessages.pb.h.
References _has_bits_.
bool ZMQAttentionValueHolderMessage::has_vlti () const inline
Definition at line 1088 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAttentionValueHolderMessage::InitAsDefaultInstance () private
Definition at line 380 of file ZMQMessages.pb.cc.
bool ZMQAttentionValueHolderMessage::IsInitialized () const
Definition at line 629 of file ZMQMessages.pb.cc.
References _has_bits_.
google::protobuf::int32 ZMQAttentionValueHolderMessage::lti () const inline
Definition at line 1079 of file ZMQMessages.pb.h.
References lti_.
void ZMQAttentionValueHolderMessage::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 589 of file ZMQMessages.pb.cc.
void ZMQAttentionValueHolderMessage::MergeFrom (const ZMQAttentionValueHolderMessage & from)
Definition at line 601 of file ZMQMessages.pb.cc.
References _has_bits_, has_lti(), has_sti(), has_vlti(), lti(), mutable_unknown_fields(), set_lti(), set_sti(), set_vlti(), sti(), unknown_fields(), and vlti().
bool ZMQAttentionValueHolderMessage::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 436 of file ZMQMessages.pb.cc.
References DO_, lti_, mutable_unknown_fields(), set_has_lti(), set_has_sti(), set_has_vlti(), sti_, and vlti_.
inline ::google::protobuf::UnknownFieldSet* ZMQAttentionValueHolderMessage::mutable_unknown_fields () inline
Definition at line 120 of file ZMQMessages.pb.h.
References _unknown_fields_.
ZMQAttentionValueHolderMessage * ZMQAttentionValueHolderMessage::New () const
Definition at line 422 of file ZMQMessages.pb.cc.
References ZMQAttentionValueHolderMessage().
ZMQAttentionValueHolderMessage& ZMQAttentionValueHolderMessage::operator= (const ZMQAttentionValueHolderMessage & from) inline
Definition at line 111 of file ZMQMessages.pb.h.
References CopyFrom().
void ZMQAttentionValueHolderMessage::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 505 of file ZMQMessages.pb.cc.
References has_lti(), has_sti(), has_vlti(), lti(), sti(), unknown_fields(), and vlti().
google::protobuf::uint8 * ZMQAttentionValueHolderMessage::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 528 of file ZMQMessages.pb.cc.
References has_lti(), has_sti(), has_vlti(), lti(), sti(), unknown_fields(), and vlti().
void ZMQAttentionValueHolderMessage::set_has_lti () inline private
Definition at line 1069 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAttentionValueHolderMessage::set_has_sti () inline private
Definition at line 1047 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAttentionValueHolderMessage::set_has_vlti () inline private
Definition at line 1091 of file ZMQMessages.pb.h.
References _has_bits_.
void ZMQAttentionValueHolderMessage::set_lti (::google::protobuf::int32 value) inline
Definition at line 1082 of file ZMQMessages.pb.h.
References lti_, and set_has_lti().
void ZMQAttentionValueHolderMessage::set_sti (::google::protobuf::int32 value) inline
Definition at line 1060 of file ZMQMessages.pb.h.
References set_has_sti(), and sti_.
void ZMQAttentionValueHolderMessage::set_vlti (::google::protobuf::int32 value) inline
Definition at line 1104 of file ZMQMessages.pb.h.
References set_has_vlti(), and vlti_.
void ZMQAttentionValueHolderMessage::SetCachedSize (int size) const private
Definition at line 406 of file ZMQMessages.pb.cc.
References _cached_size_.
void ZMQAttentionValueHolderMessage::SharedCtor () private
Definition at line 389 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, lti_, sti_, and vlti_.
void ZMQAttentionValueHolderMessage::SharedDtor () private
Definition at line 401 of file ZMQMessages.pb.cc.
References default_instance_.
google::protobuf::int32 ZMQAttentionValueHolderMessage::sti () const inline
Definition at line 1057 of file ZMQMessages.pb.h.
References sti_.
void ZMQAttentionValueHolderMessage::Swap (ZMQAttentionValueHolderMessage * other)
Definition at line 635 of file ZMQMessages.pb.cc.
References _cached_size_, _has_bits_, _unknown_fields_, lti_, sti_, and vlti_.
const ::google::protobuf::UnknownFieldSet& ZMQAttentionValueHolderMessage::unknown_fields () const inline
Definition at line 116 of file ZMQMessages.pb.h.
References _unknown_fields_.
google::protobuf::int32 ZMQAttentionValueHolderMessage::vlti () const inline
Definition at line 1101 of file ZMQMessages.pb.h.
References vlti_.
Friends And Related Function Documentation
void protobuf_AddDesc_ZMQMessages_2eproto () friend
Definition at line 254 of file ZMQMessages.pb.cc.
void protobuf_AssignDesc_ZMQMessages_2eproto () friend
Definition at line 49 of file ZMQMessages.pb.cc.
void protobuf_ShutdownFile_ZMQMessages_2eproto () friend
Definition at line 235 of file ZMQMessages.pb.cc.
Member Data Documentation
int ZMQAttentionValueHolderMessage::_cached_size_ mutable private
Definition at line 194 of file ZMQMessages.pb.h.
::google::protobuf::uint32 ZMQAttentionValueHolderMessage::_has_bits_[(3+31)/32] private
Definition at line 195 of file ZMQMessages.pb.h.
::google::protobuf::UnknownFieldSet ZMQAttentionValueHolderMessage::_unknown_fields_ private
Definition at line 188 of file ZMQMessages.pb.h.
ZMQAttentionValueHolderMessage * ZMQAttentionValueHolderMessage::default_instance_ = NULL static private
Definition at line 202 of file ZMQMessages.pb.h.
const int ZMQAttentionValueHolderMessage::kLTIFieldNumber = 2 static
Definition at line 168 of file ZMQMessages.pb.h.
const int ZMQAttentionValueHolderMessage::kSTIFieldNumber = 1 static
Definition at line 161 of file ZMQMessages.pb.h.
const int ZMQAttentionValueHolderMessage::kVLTIFieldNumber = 3 static
Definition at line 175 of file ZMQMessages.pb.h.
::google::protobuf::int32 ZMQAttentionValueHolderMessage::lti_ private
Definition at line 191 of file ZMQMessages.pb.h.
::google::protobuf::int32 ZMQAttentionValueHolderMessage::sti_ private
Definition at line 190 of file ZMQMessages.pb.h.
::google::protobuf::int32 ZMQAttentionValueHolderMessage::vlti_ private
Definition at line 192 of file ZMQMessages.pb.h.
The documentation for this class was generated from the following files:
opencog/persist/zmq/atomspace/ZMQMessages.pb.h
opencog/persist/zmq/atomspace/ZMQMessages.pb.cc