OpenCog Framework: opencog::GenericTruthValue Class Reference
opencog::GenericTruthValue Class Reference
#include <GenericTruthValue.h>
Public Member Functions
GenericTruthValue (count_t, count_t, strength_t, strength_t, confidence_t, entropy_t)
GenericTruthValue (GenericTruthValue const &)
count_t getPositiveEvidence () const
count_t getLogPositiveEvidence () const
count_t getTotalEvidence () const
count_t getLogTotalEvidence () const
strength_t getFrequency () const
strength_t getLogFrequency () const
strength_t getFuzzyStrength () const
strength_t getLogFuzzyStrength () const
confidence_t getConfidence () const
confidence_t getLogConfidence () const
entropy_t getEntropy () const
GenericTruthValuePtr merge (GenericTruthValuePtr) const
GenericTruthValuePtr clone () const
GenericTruthValue * rawclone () const
virtual bool operator== (const GenericTruthValue &rhs) const
std::string toString () const
Protected Attributes
count_t positiveEvidence
count_t totalEvidence
strength_t frequency
strength_t fuzzyStrength
confidence_t confidence
entropy_t entropy
Private Member Functions
GenericTruthValue & operator= (const GenericTruthValue &rhs)
Detailed Description
Definition at line 43 of file GenericTruthValue.h.
Constructor & Destructor Documentation
GenericTruthValue::GenericTruthValue (count_t pe, count_t te, strength_t f, strength_t fs, confidence_t c, entropy_t e)
Definition at line 32 of file GenericTruthValue.cc.
References confidence, entropy, frequency, fuzzyStrength, positiveEvidence, and totalEvidence.
GenericTruthValue::GenericTruthValue (GenericTruthValue const & gtv)
Definition at line 44 of file GenericTruthValue.cc.
References confidence, entropy, frequency, fuzzyStrength, positiveEvidence, and totalEvidence.
Member Function Documentation
GenericTruthValuePtr opencog::GenericTruthValue::clone () const inline
Definition at line 76 of file GenericTruthValue.h.
confidence_t GenericTruthValue::getConfidence () const
Definition at line 94 of file GenericTruthValue.cc.
References confidence.
entropy_t GenericTruthValue::getEntropy () const
Definition at line 104 of file GenericTruthValue.cc.
References entropy.
strength_t GenericTruthValue::getFrequency () const
Definition at line 74 of file GenericTruthValue.cc.
References frequency.
strength_t GenericTruthValue::getFuzzyStrength () const
Definition at line 84 of file GenericTruthValue.cc.
References fuzzyStrength.
confidence_t GenericTruthValue::getLogConfidence () const
Definition at line 99 of file GenericTruthValue.cc.
References confidence.
strength_t GenericTruthValue::getLogFrequency () const
Definition at line 79 of file GenericTruthValue.cc.
References frequency.
strength_t GenericTruthValue::getLogFuzzyStrength () const
Definition at line 89 of file GenericTruthValue.cc.
References fuzzyStrength.
count_t GenericTruthValue::getLogPositiveEvidence () const
Definition at line 59 of file GenericTruthValue.cc.
References positiveEvidence.
count_t GenericTruthValue::getLogTotalEvidence () const
Definition at line 69 of file GenericTruthValue.cc.
References totalEvidence.
count_t GenericTruthValue::getPositiveEvidence () const
Definition at line 54 of file GenericTruthValue.cc.
References positiveEvidence.
count_t GenericTruthValue::getTotalEvidence () const
Definition at line 64 of file GenericTruthValue.cc.
References totalEvidence.
GenericTruthValuePtr GenericTruthValue::merge (GenericTruthValuePtr gtv) const
Definition at line 109 of file GenericTruthValue.cc.
References CVAL, entropy, frequency, fuzzyStrength, KKK, positiveEvidence, and totalEvidence.
GenericTruthValue& opencog::GenericTruthValue::operator= (const GenericTruthValue & rhs) inline private
Definition at line 47 of file GenericTruthValue.h.
bool GenericTruthValue::operator== (const GenericTruthValue & rhs) const virtual
Definition at line 128 of file GenericTruthValue.cc.
References confidence, DOUBLE_ACCEPTABLE_ERROR, entropy, FLOAT_ACCEPTABLE_ERROR, frequency, fuzzyStrength, positiveEvidence, and totalEvidence.
GenericTruthValue* opencog::GenericTruthValue::rawclone () const inline
Definition at line 81 of file GenericTruthValue.h.
References GenericTruthValue().
std::string GenericTruthValue::toString () const
Definition at line 151 of file GenericTruthValue.cc.
References getConfidence(), getEntropy(), getFrequency(), getFuzzyStrength(), getPositiveEvidence(), and getTotalEvidence().
Member Data Documentation
confidence_t opencog::GenericTruthValue::confidence protected
Definition at line 101 of file GenericTruthValue.h.
entropy_t opencog::GenericTruthValue::entropy protected
Definition at line 103 of file GenericTruthValue.h.
strength_t opencog::GenericTruthValue::frequency protected
Definition at line 96 of file GenericTruthValue.h.
strength_t opencog::GenericTruthValue::fuzzyStrength protected
Definition at line 99 of file GenericTruthValue.h.
count_t opencog::GenericTruthValue::positiveEvidence protected
Definition at line 90 of file GenericTruthValue.h.
count_t opencog::GenericTruthValue::totalEvidence protected
Definition at line 93 of file GenericTruthValue.h.
The documentation for this class was generated from the following files:
opencog/atomspace/GenericTruthValue.h
opencog/atomspace/GenericTruthValue.cc