OpenCog Framework: opencog::ProbabilisticTruthValue Class Reference
opencog::ProbabilisticTruthValue Class Reference
atomspace library
a TruthValue that stores a mean, a confidence and the number of observations
#include <ProbabilisticTruthValue.h>
Public Member Functions
ProbabilisticTruthValue (strength_t, confidence_t, count_t)
ProbabilisticTruthValue (const TruthValue &)
ProbabilisticTruthValue (ProbabilisticTruthValue const &)
virtual bool operator== (const TruthValue &rhs) const
std::string toString () const
TruthValueType getType () const
strength_t getMean () const
count_t getCount () const
confidence_t getConfidence () const
virtual TruthValuePtr merge (TruthValuePtr, TVMergeStyle ms=DEFAULT) const
TruthValuePtr clone () const
TruthValue * rawclone () const
Public Member Functions inherited from opencog::TruthValue
virtual ~TruthValue ()
bool operator!= (const TruthValue &rhs) const
virtual bool isNullTv () const
virtual bool isDefaultTV () const
Static Public Member Functions
static TruthValuePtr createTV (strength_t s, confidence_t f, count_t c)
Static Public Member Functions inherited from opencog::TruthValue
static TruthValuePtr NULL_TV ()
static TruthValuePtr TRUE_TV ()
static TruthValuePtr DEFAULT_TV ()
static TruthValuePtr FALSE_TV ()
static TruthValuePtr TRIVIAL_TV ()
Protected Attributes
strength_t mean
confidence_t confidence
count_t count
Detailed Description
a TruthValue that stores a mean, a confidence and the number of observations
Definition at line 42 of file ProbabilisticTruthValue.h.
Constructor & Destructor Documentation
ProbabilisticTruthValue::ProbabilisticTruthValue (strength_t m, confidence_t n, count_t c)
Definition at line 37 of file ProbabilisticTruthValue.cc.
References confidence, count, reorder_log::m, and mean.
ProbabilisticTruthValue::ProbabilisticTruthValue (const TruthValue & source)
Definition at line 44 of file ProbabilisticTruthValue.cc.
References confidence, count, opencog::TruthValue::getConfidence(), opencog::TruthValue::getCount(), opencog::TruthValue::getMean(), and mean.
ProbabilisticTruthValue::ProbabilisticTruthValue (ProbabilisticTruthValue const & source)
Definition at line 50 of file ProbabilisticTruthValue.cc.
References confidence, count, and mean.
Member Function Documentation
TruthValuePtr opencog::ProbabilisticTruthValue::clone () const inline virtual
Implements opencog::TruthValue.
Definition at line 73 of file ProbabilisticTruthValue.h.
static TruthValuePtr opencog::ProbabilisticTruthValue::createTV (strength_t s, confidence_t f, count_t c) inline static
Definition at line 67 of file ProbabilisticTruthValue.h.
confidence_t ProbabilisticTruthValue::getConfidence () const virtual
Implements opencog::TruthValue.
Definition at line 67 of file ProbabilisticTruthValue.cc.
References confidence.
count_t ProbabilisticTruthValue::getCount () const virtual
Implements opencog::TruthValue.
Definition at line 62 of file ProbabilisticTruthValue.cc.
References count.
strength_t ProbabilisticTruthValue::getMean () const virtual
Implements opencog::TruthValue.
Definition at line 57 of file ProbabilisticTruthValue.cc.
References mean.
TruthValueType ProbabilisticTruthValue::getType () const virtual
Implements opencog::TruthValue.
Definition at line 96 of file ProbabilisticTruthValue.cc.
References opencog::PROBABILISTIC_TRUTH_VALUE.
TruthValuePtr ProbabilisticTruthValue::merge (TruthValuePtr , TVMergeStyle ms = DEFAULT) const virtual
Merge this TV object with the given TV object argument. It always returns a new TV object with the result of the merge, even if it is equal to one of the merged TV objects.
Parameters
ms the merge style as described in https://github.com/opencog/opencog/issues/1295
Implements opencog::TruthValue.
Definition at line 104 of file ProbabilisticTruthValue.cc.
References clone(), count, and mean.
bool ProbabilisticTruthValue::operator== (const TruthValue & rhs) const virtual
Equality. Used to determine if two truth values are the same, or not. Primarily useful see if a TV is equal to NULL_TV, TRUE_TV, FALSE_TV, etc.
Implements opencog::TruthValue.
Definition at line 82 of file ProbabilisticTruthValue.cc.
References confidence, count, DOUBLE_ACCEPTABLE_ERROR, FLOAT_ACCEPTABLE_ERROR, and mean.
TruthValue* opencog::ProbabilisticTruthValue::rawclone () const inline virtual
Implements opencog::TruthValue.
Definition at line 77 of file ProbabilisticTruthValue.h.
References ProbabilisticTruthValue().
std::string ProbabilisticTruthValue::toString () const virtual
Implements opencog::TruthValue.
Definition at line 72 of file ProbabilisticTruthValue.cc.
References getConfidence(), getCount(), and getMean().
Member Data Documentation
confidence_t opencog::ProbabilisticTruthValue::confidence protected
Definition at line 47 of file ProbabilisticTruthValue.h.
count_t opencog::ProbabilisticTruthValue::count protected
Definition at line 48 of file ProbabilisticTruthValue.h.
strength_t opencog::ProbabilisticTruthValue::mean protected
Definition at line 46 of file ProbabilisticTruthValue.h.
The documentation for this class was generated from the following files:
opencog/atomspace/ProbabilisticTruthValue.h
opencog/atomspace/ProbabilisticTruthValue.cc