OpenCog Framework: opencog/persist/hypertable/test.cc File Reference
test.cc File Reference
#include "AtomspaceHTabler.h"
#include "opencog/atomspace/Atom.h"
#include "opencog/atomspace/Link.h"
#include "opencog/atomspace/Node.h"
#include "opencog/atomspace/SimpleTruthValue.h"
Functions
int atomCompare (Atom *a, Atom *b)
int main (int argc, char **argv)
Function Documentation
int atomCompare (Atom * a, Atom * b)
Definition at line 9 of file test.cc.
References python.create_atoms_by_type::a, opencog::Link::getArity(), opencog::Atom::getAttentionValue(), opencog::TruthValue::getCount(), opencog::AttentionValue::getLTI(), opencog::TruthValue::getMean(), opencog::Link::getOutgoingSet(), opencog::AttentionValue::getSTI(), opencog::Atom::getTruthValue(), opencog::Atom::getType(), and opencog::AttentionValue::getVLTI().
int main (int argc, char ** argv)
Definition at line 61 of file test.cc.
References python.create_atoms_by_type::a, atomCompare(), av, opencog::AtomspaceHTabler::getAtom(), opencog::AtomspaceHTabler::getLink(), opencog::AtomspaceHTabler::getNode(), opencog::Link::getOutgoingSet(), opencog::Atom::getType(), opencog::Atom::setAttentionValue(), opencog::Atom::setTruthValue(), and opencog::AtomspaceHTabler::storeAtom().