OpenCog Framework: opencog::FunctionWrap Class Reference
opencog::FunctionWrap Class Reference
Wrapper class, to invoke misc extension code from guile.
#include <SchemeModule.h>
Public Member Functions
FunctionWrap (Handle(*)(AtomSpace *, const Handle &), const char *, const char *)
FunctionWrap (Handle(*)(AtomSpace *, const Handle &, Type, const HandleSeq &), const char *, const char *)
FunctionWrap (TruthValuePtr(*)(AtomSpace *, const Handle &), const char *, const char *)
Private Member Functions
Handle wrapper (Handle)
Handle wrapper_htq (Handle, Type, const HandleSeq &)
TruthValuePtr prapper (Handle)
Private Attributes
Handle(* _func)(AtomSpace *, const Handle &)
Handle(* _func_htq)(AtomSpace *, const Handle &, Type, const HandleSeq &)
TruthValuePtr(* _pred)(AtomSpace *, const Handle &)
const char * _name
Detailed Description
Wrapper class, to invoke misc extension code from guile.
Definition at line 20 of file SchemeModule.h.
Constructor & Destructor Documentation
opencog::FunctionWrap::FunctionWrap (Handle(*)(AtomSpace *, const Handle &) , const char * , const char *)
opencog::FunctionWrap::FunctionWrap (Handle(*)(AtomSpace *, const Handle &, Type, const HandleSeq &) , const char * , const char *)
opencog::FunctionWrap::FunctionWrap (TruthValuePtr(*)(AtomSpace *, const Handle &) , const char * , const char *)
Member Function Documentation
TruthValuePtr FunctionWrap::prapper (Handle h) private
Definition at line 49 of file SchemeModule.cc.
References _name, _pred, and opencog::SchemeSmob::ss_get_env_as().
Handle FunctionWrap::wrapper (Handle h) private
Definition at line 36 of file SchemeModule.cc.
References _func, _name, and opencog::SchemeSmob::ss_get_env_as().
Handle FunctionWrap::wrapper_htq (Handle h, Type t, const HandleSeq & seq) private
Definition at line 43 of file SchemeModule.cc.
References _func_htq, _name, and opencog::SchemeSmob::ss_get_env_as().
Member Data Documentation
Handle(* opencog::FunctionWrap::_func)(AtomSpace *, const Handle &) private
Definition at line 23 of file SchemeModule.h.
Handle(* opencog::FunctionWrap::_func_htq)(AtomSpace *, const Handle &, Type, const HandleSeq &) private
Definition at line 24 of file SchemeModule.h.
const char* opencog::FunctionWrap::_name private
Definition at line 32 of file SchemeModule.h.
TruthValuePtr(* opencog::FunctionWrap::_pred)(AtomSpace *, const Handle &) private
Definition at line 29 of file SchemeModule.h.
The documentation for this class was generated from the following files:
opencog/guile/SchemeModule.h
opencog/guile/SchemeModule.cc