OpenCog Framework: python.undocumented.blocksworld Namespace Reference
python.undocumented.blocksworld Namespace Reference
Functions
def action_template
def not_template
def parse_params
def parse_conditions_list
def new_rule
def blocksworld_rules
def blocksworld_test
Variables
t = types
dictionary blocks = {}
dictionary actions = {}
dictionary predicates = {}
Function Documentation
def python.undocumented.blocksworld.action_template (action, arguments)
Definition at line 13 of file blocksworld.py.
def python.undocumented.blocksworld.blocksworld_rules (atomspace)
Definition at line 78 of file blocksworld.py.
References python.undocumented.blocksworld.new_rule(), and python.undocumented.blocksworld.parse_conditions_list().
def python.undocumented.blocksworld.blocksworld_test (atomspace)
Definition at line 157 of file blocksworld.py.
References python.undocumented.blocksworld.parse_conditions_list().
def python.undocumented.blocksworld.new_rule (atomspace, action_str, pre_str, post_str)
Definition at line 47 of file blocksworld.py.
References python.undocumented.blocksworld.action_template(), python.undocumented.blocksworld.parse_conditions_list(), and python.undocumented.blocksworld.parse_params().
def python.undocumented.blocksworld.not_template (link)
Definition at line 18 of file blocksworld.py.
def python.undocumented.blocksworld.parse_conditions_list (vars, conditions_str)
Definition at line 24 of file blocksworld.py.
References python.undocumented.blocksworld.not_template(), and python.undocumented.blocksworld.parse_params().
def python.undocumented.blocksworld.parse_params (vars, relation_l)
Definition at line 21 of file blocksworld.py.
Variable Documentation
dictionary python.undocumented.blocksworld.actions = {}
Definition at line 75 of file blocksworld.py.
dictionary python.undocumented.blocksworld.blocks = {}
Definition at line 74 of file blocksworld.py.
dictionary python.undocumented.blocksworld.predicates = {}
Definition at line 76 of file blocksworld.py.
python.undocumented.blocksworld.t = types
Definition at line 11 of file blocksworld.py.