OpenCog Framework: opencog::PersistSCM Class Reference
opencog::PersistSCM Class Reference
Communications and Persistence
#include <PersistSCM.h>
Public Member Functions
PersistSCM (void)
Private Member Functions
void init (void)
Handle fetch_atom (Handle)
Handle fetch_incoming_set (Handle)
Handle store_atom (Handle)
void load_type (Type)
void barrier (void)
Static Private Member Functions
static void * init_in_guile (void *)
static void init_in_module (void *)
Detailed Description
Definition at line 36 of file PersistSCM.h.
Constructor & Destructor Documentation
PersistSCM::PersistSCM (void)
Definition at line 31 of file PersistSCM.cc.
References init_in_guile().
Member Function Documentation
void PersistSCM::barrier (void) private
Definition at line 100 of file PersistSCM.cc.
References opencog::AtomSpace::barrier(), and opencog::SchemeSmob::ss_get_env_as().
Handle PersistSCM::fetch_atom (Handle h) private
Definition at line 68 of file PersistSCM.cc.
References opencog::AtomSpace::fetch_atom(), and opencog::SchemeSmob::ss_get_env_as().
Handle PersistSCM::fetch_incoming_set (Handle h) private
Definition at line 75 of file PersistSCM.cc.
References opencog::AtomSpace::fetch_incoming_set(), and opencog::SchemeSmob::ss_get_env_as().
void PersistSCM::init (void) private
Definition at line 52 of file PersistSCM.cc.
References barrier(), fetch_atom(), fetch_incoming_set(), load_type(), and store_atom().
void * PersistSCM::init_in_guile (void * self) static private
Definition at line 39 of file PersistSCM.cc.
References init_in_module().
void PersistSCM::init_in_module (void * data) static private
Definition at line 46 of file PersistSCM.cc.
References init().
void PersistSCM::load_type (Type t) private
Definition at line 94 of file PersistSCM.cc.
References opencog::AtomSpace::fetch_all_atoms_of_type(), and opencog::SchemeSmob::ss_get_env_as().
Handle PersistSCM::store_atom (Handle h) private
Store the single atom to the backing store hanging off the atom-space
Definition at line 87 of file PersistSCM.cc.
References opencog::SchemeSmob::ss_get_env_as(), and opencog::AtomSpace::store_atom().
The documentation for this class was generated from the following files:
opencog/persist/guile/PersistSCM.h
opencog/persist/guile/PersistSCM.cc