OpenCog Framework: opencog::ModuleWrap Class Reference
opencog::ModuleWrap Class Reference abstract
#include <SchemeModule.h>
Public Member Functions
ModuleWrap (const char *)
void module_init (void)
virtual ~ModuleWrap ()
Protected Member Functions
virtual void init (void)=0
Static Private Member Functions
static void * init_in_guile (void *)
static void init_in_module (void *)
Private Attributes
const char * _modname
Detailed Description
Definition at line 42 of file SchemeModule.h.
Constructor & Destructor Documentation
ModuleWrap::ModuleWrap (const char * m)
Definition at line 58 of file SchemeModule.cc.
ModuleWrap::~ModuleWrap () virtual
Definition at line 86 of file SchemeModule.cc.
Member Function Documentation
virtual void opencog::ModuleWrap::init (void) protected pure virtual
Implemented in opencog::ExampleSCM, opencog::ExecSCM, and opencog::PatternSCM.
void * ModuleWrap::init_in_guile (void * data) static private
Definition at line 67 of file SchemeModule.cc.
References init_in_module().
void ModuleWrap::init_in_module (void * data) static private
This is called while _modname is the current module. Thus, all the definitions below happen in that module.
Definition at line 80 of file SchemeModule.cc.
References init().
void ModuleWrap::module_init (void)
Definition at line 62 of file SchemeModule.cc.
References init_in_guile().
Member Data Documentation
const char* opencog::ModuleWrap::_modname private
Definition at line 47 of file SchemeModule.h.
The documentation for this class was generated from the following files:
opencog/guile/SchemeModule.h
opencog/guile/SchemeModule.cc