OpenCog Framework: opencog/atoms/reduct/ArithmeticLink.cc File Reference
ArithmeticLink.cc File Reference
#include <limits>
#include <opencog/atomspace/atom_types.h>
#include <opencog/atomspace/ClassServer.h>
#include <opencog/atoms/NumberNode.h>
#include <opencog/atoms/execution/Instantiator.h>
#include "ArithmeticLink.h"
Functions
static double get_double (AtomSpace *as, Handle h)
Function Documentation
static double get_double (AtomSpace * as, Handle h) inline static
execute() – Execute the expression, returning a number
Similar to reduce(), above, except that this can only work on fully grounded (closed) sentences: after executation, everything must be a number, and there can be no variables in sight.
Definition at line 148 of file ArithmeticLink.cc.
References opencog::classserver(), opencog::Atom::getType(), and opencog::NumberNodeCast().