OpenCog Framework: opencog/atomspace/AtomTable.cc File Reference
AtomTable.cc File Reference
#include "AtomTable.h"
#include <iterator>
#include <set>
#include <stdlib.h>
#include <boost/bind.hpp>
#include <opencog/atomspace/ClassServer.h>
#include <opencog/atomspace/Link.h>
#include <opencog/atomspace/Node.h>
#include <opencog/atomspace/TLB.h>
#include <opencog/atoms/NumberNode.h>
#include <opencog/atoms/TypeNode.h>
#include <opencog/atoms/bind/BindLink.h>
#include <opencog/atoms/bind/DefineLink.h>
#include <opencog/atoms/bind/LambdaLink.h>
#include <opencog/atoms/bind/PatternLink.h>
#include <opencog/atoms/bind/VariableList.h>
#include <opencog/atoms/execution/EvaluationLink.h>
#include <opencog/atoms/execution/ExecutionOutputLink.h>
#include <opencog/atoms/reduct/DeleteLink.h>
#include <opencog/atoms/reduct/FunctionLink.h>
#include <opencog/atoms/core/PutLink.h>
#include <opencog/util/exceptions.h>
#include <opencog/util/functional.h>
#include <opencog/util/Logger.h>
Macros
#define DPRINTF(...)
Functions
static AtomPtr clone_factory (Type atom_type, AtomPtr atom)
static void prt_diag (AtomPtr atom, size_t i, size_t arity, const HandleSeq &ogs)
Macro Definition Documentation
#define DPRINTF (...)
Definition at line 58 of file AtomTable.cc.
Function Documentation
static AtomPtr clone_factory (Type atom_type, AtomPtr atom) static
Definition at line 328 of file AtomTable.cc.
References opencog::classserver(), createBindLink, createDefineLink, createLambdaLink, createLink, createNode, createNumberNode, createPatternLink, createPutLink, createTypeNode, createVariableList, opencog::LinkCast(), and opencog::NodeCast().
static void prt_diag (AtomPtr atom, size_t i, size_t arity, const HandleSeq & ogs) static
Definition at line 376 of file AtomTable.cc.